import { defineConfig } from "tsdown";

const sharedConfig = {
	outDir: "dist",
	format: "esm" as const,
	target: "node22" as const,
	platform: "node" as const,
	// Root tsconfig sets sourceMap/declarationMap: true; without these
	// overrides tsdown inherits them and ships ~2.7 MB of maps in the package.
	sourcemap: false,
	outputOptions: { sourcemap: false },
	// Keep tsup-era filenames: package.json "main"/"exports" and
	// openclaw.plugin.json point at dist/**/*.js, not .mjs.
	outExtensions: () => ({ js: ".js", dts: ".d.ts" }),
	dts: {
		// oxc: isolated-declarations generator — no dependency on the TypeScript
		// compiler API, so the TS7 native compiler can't break dts emit. Pinned
		// so TS7's presence doesn't auto-select the experimental tsgo generator.
		generator: "oxc",
		// eager: workspace deps are consumed as .ts source (exports -> ./src);
		// without it the dts generator skips files outside this app's program.
		eager: true,
		compilerOptions: { declarationMap: false },
	},
};

export default defineConfig([
{ ...sharedConfig, entry: {
  "index": "src/index.ts",
  "internal/engine/rem/index": "src/engine/rem/index.ts",
  "internal/engine/rem/types": "src/engine/rem/types.ts",
  "internal/engine/rem/classifier": "src/engine/rem/classifier.ts",
  "cli": "src/contract/cli.ts",
  "client": "src/contract/client.ts",
  "release-download": "src/contract/release-download.ts",
  "internal/config/plugin-config-schema": "config/plugin-config-schema.ts",
  "internal/config/product-mode": "config/plugin-config-mode-schema.ts",
  "internal/config/skin-defaults": "config/skin-defaults.ts",
  "coding-skin": "config/coding-skin.ts",
  "internal/contract/discovery": "src/contract/discovery.ts",
  "internal/contract/routes": "src/contract/routes.ts",
  "internal/contract/profile": "src/contract/profile.ts",
  "internal/config/installation-settings": "config/installation-settings.ts",
  "internal/engine/bindings/memory-tool-formatting": "src/engine/bindings/memory-tool-formatting.ts",
  "memdump": "src/engine/diagnostics/memdump.ts",
  "diagnostic-encoder": "src/engine/observability/early-diagnostics.ts",
  "internal/config/index": "config/index.ts",
  "internal/engine/bindings/embedder-config-files": "src/engine/bindings/embedder-config-files.ts",
  "internal/engine/security/memory-scope-policy": "src/engine/security/memory-scope-policy.ts",
  "internal/engine/bindings/memory-cli-shared": "src/engine/bindings/memory-cli-shared.ts",
  "internal/engine/bindings/memory-forget-tool": "src/engine/bindings/memory-forget-tool.ts",
  "internal/engine/bindings/memory-list-tool": "src/engine/bindings/memory-list-tool.ts",
  "internal/engine/bindings/memory-recall-tool": "src/engine/bindings/memory-recall-tool.ts",
  "internal/engine/bindings/memory-reflection-resolve-tool": "src/engine/bindings/memory-reflection-resolve-tool.ts",
  "internal/engine/bindings/memory-stats-tool": "src/engine/bindings/memory-stats-tool.ts",
  "internal/engine/bindings/memory-store-tool": "src/engine/bindings/memory-store-tool.ts",
  "internal/engine/bindings/memory-tool-access": "src/engine/bindings/memory-tool-access.ts",
  "internal/engine/bindings/memory-tool-results": "src/engine/bindings/memory-tool-results.ts",
  "internal/engine/bindings/memory-tool-schemas": "src/engine/bindings/memory-tool-schemas.ts",
  "internal/engine/bindings/memory-update-tool": "src/engine/bindings/memory-update-tool.ts",
  "internal/engine/bindings/sno-station-mem-ambient-learning-hook": "src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
  "internal/engine/bindings/sno-station-mem-auto-recall-hook": "src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
  "internal/engine/bindings/sno-station-mem-hook-types": "src/engine/bindings/sno-station-mem-hook-types.ts",
  "internal/engine/bindings/sno-station-mem-insight-distill-factory": "src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
  "internal/engine/bindings/sno-station-mem-message-transcript": "src/engine/bindings/sno-station-mem-message-transcript.ts",
  "internal/engine/bindings/sno-station-mem-reset-hook": "src/engine/bindings/sno-station-mem-reset-hook.ts",
  "internal/engine/bindings/sno-station-mem-runtime-mode": "src/engine/bindings/sno-station-mem-runtime-mode.ts",
  "internal/engine/bindings/sno-station-mem-session-state": "src/engine/bindings/sno-station-mem-session-state.ts",
  "internal/engine/eval/trace": "src/engine/eval/trace.ts",
  "internal/engine/extraction/ambient-learning-text-normalizer": "src/engine/extraction/ambient-learning-text-normalizer.ts",
  "internal/engine/extraction/atomic-memory-extraction": "src/engine/extraction/atomic-memory-extraction.ts",
  "internal/engine/extraction/b-profile-section-dictionary-provider": "src/engine/extraction/b-profile-section-dictionary-provider.ts",
  "internal/engine/extraction/b-profile-section-rekey": "src/engine/extraction/b-profile-section-rekey.ts",
  "internal/engine/extraction/capture-policy-detector": "src/engine/extraction/capture-policy-detector.ts",
  "internal/engine/extraction/embedding-provider-client": "src/engine/extraction/embedding-provider-client.ts",
  "internal/engine/extraction/extraction-text-sanitizer": "src/engine/extraction/extraction-text-sanitizer.ts",
  "internal/engine/extraction/memory-metadata-codec": "src/engine/extraction/memory-metadata-codec.ts",
  "internal/engine/extraction/memory-temporality-classifier": "src/engine/extraction/memory-temporality-classifier.ts",
  "internal/engine/i18n/all-resources": "src/engine/i18n/all-resources.ts",
  "internal/engine/i18n/locales": "src/engine/i18n/locales.ts",
  "internal/engine/i18n/res/_types": "src/engine/i18n/res/_types.ts",
  "internal/engine/observability/adapter": "src/engine/observability/adapter.ts",
  "internal/engine/observability/best-effort": "src/engine/observability/best-effort.ts",
  "internal/engine/observability/early-diagnostics": "src/engine/observability/early-diagnostics.ts",
  "internal/engine/observability/memory-snapshot": "src/engine/observability/memory-snapshot.ts",
  "internal/engine/observability/observable-embedder": "src/engine/observability/observable-embedder.ts",
  "internal/engine/observability/observable-llm-client": "src/engine/observability/observable-llm-client.ts",
  "internal/engine/observability/observable-memory-store": "src/engine/observability/observable-memory-store.ts",
  "internal/engine/observability/observable-retriever": "src/engine/observability/observable-retriever.ts",
  "internal/engine/observability/runtime-diagnostics": "src/engine/observability/runtime-diagnostics.ts",
  "internal/engine/observability/session-registry": "src/engine/observability/session-registry.ts",
  "internal/engine/observability/version-metadata": "src/engine/observability/version-metadata.ts",
  "internal/engine/operations/daily-spend-estimator": "src/engine/operations/daily-spend-estimator.ts",
  "internal/engine/operations/learning-file-maintenance": "src/engine/operations/learning-file-maintenance.ts",
  "internal/engine/operations/memory-tier-promoter": "src/engine/operations/memory-tier-promoter.ts",
  "internal/engine/operations/runtime-audit-log": "src/engine/operations/runtime-audit-log.ts",
  "internal/engine/provider/canonical-memory-corpus": "src/engine/provider/canonical-memory-corpus.ts",
  "internal/engine/provider/provider-registration": "src/engine/provider/provider-registration.ts",
  "internal/engine/provider/provider-row-renderer": "src/engine/provider/provider-row-renderer.ts",
  "internal/engine/provider/provider-types": "src/engine/provider/provider-types.ts",
  "internal/engine/reflection/daily-log-generator": "src/engine/reflection/daily-log-generator.ts",
  "internal/engine/reflection/reflection-command-hooks": "src/engine/reflection/reflection-command-hooks.ts",
  "internal/engine/reflection/reflection-deps": "src/engine/reflection/reflection-deps.ts",
  "internal/engine/reflection/reflection-embedded-generator": "src/engine/reflection/reflection-embedded-generator.ts",
  "internal/engine/reflection/reflection-injection-hooks": "src/engine/reflection/reflection-injection-hooks.ts",
  "internal/engine/reflection/reflection-lifecycle-hooks": "src/engine/reflection/reflection-lifecycle-hooks.ts",
  "internal/engine/reflection/strategy-hook-runner": "src/engine/reflection/strategy-hook-runner.ts",
  "internal/engine/retrieval/access-tracker": "src/engine/retrieval/access-tracker.ts",
  "internal/engine/retrieval/intent-analyzer": "src/engine/retrieval/intent-analyzer.ts",
  "internal/engine/retrieval/retrieval-gate": "src/engine/retrieval/retrieval-gate.ts",
  "internal/engine/retrieval/retriever": "src/engine/retrieval/retriever.ts",
  "internal/engine/security/redact": "src/engine/security/redact.ts",
  "internal/engine/security/scopes": "src/engine/security/scopes.ts",
  "internal/engine/shared/errors": "src/engine/shared/errors.ts",
  "internal/engine/shared/i18n-text": "src/engine/shared/i18n-text.ts",
  "internal/engine/shared/iso-date-time": "src/engine/shared/iso-date-time.ts",
  "internal/engine/shared/lru": "src/engine/shared/lru.ts",
  "internal/engine/shared/memory-kind-policy": "src/engine/shared/memory-kind-policy.ts",
  "internal/engine/shared/paths": "src/engine/shared/paths.ts",
  "internal/engine/shared/types": "src/engine/shared/types.ts",
  "internal/engine/shared/utils": "src/engine/shared/utils.ts",
  "internal/engine/telemetry/memory-telemetry-api": "src/engine/telemetry/memory-telemetry-api.ts",
  "internal/engine/telemetry/memory-telemetry-outbox": "src/engine/telemetry/memory-telemetry-outbox.ts",
  "internal/engine/telemetry/memory-telemetry-sno-observe": "src/engine/telemetry/memory-telemetry-sno-observe.ts",
  "internal/engine/telemetry/memory-telemetry-types": "src/engine/telemetry/memory-telemetry-types.ts",
  "internal/model/agent-llm-port": "src/model/agent-llm-port.ts",
  "internal/model/llm-client": "src/model/llm-client.ts",
  "internal/model/llm-failure": "src/model/llm-failure.ts",
  "internal/model/llm-mode-routing": "src/model/llm-mode-routing.ts",
  "internal/store/atomic-memory-cutover-sql": "src/store/atomic-memory-cutover-sql.ts",
  "internal/store/connection": "src/store/connection.ts",
  "internal/store/data-bootstrap": "src/store/data-bootstrap.ts",
  "internal/store/data-paths": "src/store/data-paths.ts",
  "internal/store/maintenance": "src/store/maintenance.ts",
  "internal/store/memory-kinds-cutover-migrator": "src/store/memory-kinds-cutover-migrator.ts",
  "internal/store/migrations": "src/store/migrations.ts",
  "internal/store/sqlite-runtime": "src/store/sqlite-runtime.ts",
  "internal/store/store": "src/store/store.ts"
}, clean: true },
{ ...sharedConfig, entry: { "sidecar/main": "src/sidecar/main.ts" }, clean: false, deps: { alwaysBundle: ["@snoai/embedder"] } }
]);
