// Generated by scripts/build-log-catalog.ts.
import type { LogSiteCatalog } from "@snoai/utils";
export const logSiteCatalog: LogSiteCatalog = {
	"build_id": "ee19fed288c78eea5dc547bce6ab2f005924df196ef0ed171f13652dd893164e",
	"sites": {
		"memdump.command.failed": {
			"file": "apps/mem-claw/bin/sno-memdump.js",
			"function": "<module>",
			"line": 7,
			"column": 2,
			"file_hash": "be6452ce54d6db519bd8608dfb03c2c9ffc9b5f147c352a88aa5fc42c2c70609"
		},
		"plugin.openclaw-observe-controller.finalizeObserveSession.8cc8e6a683": {
			"file": "apps/mem-claw/src/hooks/openclaw-observe-controller.ts",
			"function": "finalizeObserveSession",
			"line": 170,
			"column": 4,
			"file_hash": "da840b5690cd8f9b001ce90ae78131d85b8c5ce431c9fd9fc5c375c12c53140b"
		},
		"hooks.openclaw-runtime-hooks.contained.memory-hook-skipped": {
			"file": "apps/mem-claw/src/hooks/openclaw-runtime-hooks.ts",
			"function": "contained",
			"line": 25,
			"column": 5,
			"file_hash": "98e87e7e660607461203683033bf009fcf77343dd9a990416180d40b084e623d"
		},
		"hooks.openclaw-runtime-hooks.registerRuntimeHooks.context-degraded": {
			"file": "apps/mem-claw/src/hooks/openclaw-runtime-hooks.ts",
			"function": "registerRuntimeHooks",
			"line": 97,
			"column": 30,
			"file_hash": "98e87e7e660607461203683033bf009fcf77343dd9a990416180d40b084e623d"
		},
		"conversation-access-policy.ensureConversationAccessGranted.2e15c2b7fb": {
			"file": "apps/mem-claw/src/install/conversation-access-policy.ts",
			"function": "ensureConversationAccessGranted",
			"line": 82,
			"column": 2,
			"file_hash": "1b7ded4db053a7765b67b07759adead5195852aca79b82fd2de3ba393955f043"
		},
		"plugin.conversation-access-policy.ensureConversationAccessGranted.d508d2f9f8": {
			"file": "apps/mem-claw/src/install/conversation-access-policy.ts",
			"function": "ensureConversationAccessGranted",
			"line": 106,
			"column": 4,
			"file_hash": "1b7ded4db053a7765b67b07759adead5195852aca79b82fd2de3ba393955f043"
		},
		"tool.execute.completed": {
			"file": "apps/mem-claw/src/tools/with-tool-observability.ts",
			"function": "wrapTool.execute",
			"line": 112,
			"column": 5,
			"file_hash": "f283b562f01583f308b4710e79998fa188d01203a39428085bd05c17dd04e670"
		}
	}
};
