import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildLogCatalog, collectLogSources } from "../../../packages/utils/scripts/build-log-catalog.ts";
export { buildLogCatalog };
import type { LogSiteCatalog } from "../../../packages/utils/src/log-site-catalog.ts";

const ROOT = resolve(import.meta.dirname, "../../..");
const GENERATED_PATH = "apps/mem-claw/src/observability/log-site-catalog.generated.ts";
export function generateLogCatalog(artifactOnly = false): LogSiteCatalog {
	const catalog = buildLogCatalog(collectLogSources(ROOT));
	if (artifactOnly) {
		const generated = readFileSync(resolve(ROOT, GENERATED_PATH), "utf8");
		const assignment = "export const logSiteCatalog: LogSiteCatalog = ";
		const start = generated.indexOf(assignment);
		if (start < 0) throw new Error("Generated diagnostic catalog is missing");
		const built: unknown = JSON.parse(generated.slice(start + assignment.length).trim().replace(/;$/, ""));
		if (typeof built !== "object" || built === null || !("build_id" in built)
			|| built.build_id !== catalog.build_id) throw new Error("Source changed during diagnostic build");
		mkdirSync(resolve(ROOT, "apps/mem-claw/dist"), { recursive: true });
		writeFileSync(resolve(ROOT, "apps/mem-claw/dist/log-site-catalog.json"), `${JSON.stringify(catalog)}\n`);
		mkdirSync(resolve(ROOT, "packages/utils/dist"), { recursive: true });
		writeFileSync(resolve(ROOT, "packages/utils/dist/log-site-catalog.json"), `${JSON.stringify(catalog)}\n`);
	} else {
		writeFileSync(resolve(ROOT, GENERATED_PATH),
			`// Generated by scripts/build-log-catalog.ts. Do not edit source positions.\n` +
			`import type { LogSiteCatalog } from "@snoai/utils";\n` +
			`export const logSiteCatalog: LogSiteCatalog = ${JSON.stringify(catalog, null, "\t")};\n`);
	}
	return catalog;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const catalog = generateLogCatalog(process.argv.includes("--artifact-only"));
	process.stdout.write(`Generated ${Object.keys(catalog.sites).length} diagnostic source sites\n`);
}
