import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { buildLogCatalog, collectLogSources } from "../../../packages/utils/scripts/build-log-catalog.ts";
import type { LogSiteCatalog } from "../../../packages/utils/src/log-site-catalog.ts";

const ROOT = resolve(import.meta.dirname, "../../..");
const PACKAGE = "packages/sno-station-mem";
const GENERATED = "src/engine/observability/log-site-catalog.generated.ts";

export function generateLogCatalog(artifactOnly = false): LogSiteCatalog {
 const sources = collectLogSources(ROOT).filter(source =>
  (source.path.startsWith(`${PACKAGE}/src/`) || source.path.startsWith(`${PACKAGE}/bin/`))
  && !source.path.endsWith("log-site-catalog.generated.ts"));
 // STP-2 leaves source annotations until STP-3. Resolve catalog positions against the real file.
 const normalized = sources.map(source => ({ ...source,
  text: source.text.replace(/\bfile:\s*"[^"\n]+"/g, () => `file: ${JSON.stringify(source.path)}`) }));
 const catalog = buildLogCatalog(normalized);
 const originals = new Map(sources.map(source => [source.path, source.text]));
 for (const site of Object.values(catalog.sites)) {
  const text = originals.get(site.file);
  if (text === undefined) throw new Error(`Catalog source missing: ${site.file}`);
  site.file_hash = createHash("sha256").update(text).digest("hex");
 }
 catalog.build_id = createHash("sha256").update(JSON.stringify(sources.map(source => [source.path, createHash("sha256").update(source.text).digest("hex")]).sort())).digest("hex");
 const generatedPath = resolve(ROOT, PACKAGE, GENERATED);
 const source = `// Generated by scripts/build-log-catalog.ts.\nimport type { LogSiteCatalog } from "@snoai/utils";\nexport const logSiteCatalog: LogSiteCatalog = ${JSON.stringify(catalog, null, "\t")};\n`;
 if (artifactOnly) {
  if (readFileSync(generatedPath, "utf8") !== source) throw new Error("Source changed during diagnostic build");
  mkdirSync(resolve(ROOT, PACKAGE, "dist"), { recursive: true });
  writeFileSync(resolve(ROOT, PACKAGE, "dist/log-site-catalog.json"), `${JSON.stringify(catalog)}\n`);
 } else {
  mkdirSync(dirname(generatedPath), { recursive: true });
  writeFileSync(generatedPath, source);
 }
 return catalog;
}

generateLogCatalog(process.argv.includes("--artifact-only"));
