// Generated by scripts/build-log-catalog.ts.
import type { LogSiteCatalog } from "@snoai/utils";
export const logSiteCatalog: LogSiteCatalog = {
	"build_id": "9d64c8f99821d251345fc9a11ede33bceed2b453af796c3f7ffd4feeb106723c",
	"sites": {
		"memory.binding.read.failed": {
			"file": "packages/memory/src/contract/profile.ts",
			"function": "readBoundStorePath",
			"line": 25,
			"column": 4,
			"file_hash": "f4e791a12f215796bdd45233dc1d0c2861a0ee66f12e04ed0591887625665264"
		},
		"memory.recall.budget.checked": {
			"file": "packages/memory/src/engine/bindings/memory-recall-tool.ts",
			"function": "execute",
			"line": 370,
			"column": 6,
			"file_hash": "5318e595b0082703c7119d727226c95a6815e108f9eb58b9f2f63c802c8369b9"
		},
		"memory.recall.completed": {
			"file": "packages/memory/src/engine/bindings/memory-recall-tool.ts",
			"function": "execute",
			"line": 424,
			"column": 5,
			"file_hash": "5318e595b0082703c7119d727226c95a6815e108f9eb58b9f2f63c802c8369b9"
		},
		"memory.tool.operation.failed": {
			"file": "packages/memory/src/engine/bindings/memory-tool-results.ts",
			"function": "makeResult",
			"line": 22,
			"column": 15,
			"file_hash": "ee320af446188c11d6dad1a99b05d663d2d58d5c78c2b46414d87336ed809f3e"
		},
		"memory.capture.local.write.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "runLocalFirstCapture",
			"line": 106,
			"column": 4,
			"file_hash": "d6aac88a9eced36f737484a5d662ba1b426e8ee72a9daebd0f5dca60f8365c12"
		},
		"memory.capture.local.completed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "runLocalFirstCapture",
			"line": 117,
			"column": 2,
			"file_hash": "d6aac88a9eced36f737484a5d662ba1b426e8ee72a9daebd0f5dca60f8365c12"
		},
		"memory.capture.hook.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "onAgentEnd",
			"line": 236,
			"column": 3,
			"file_hash": "d6aac88a9eced36f737484a5d662ba1b426e8ee72a9daebd0f5dca60f8365c12"
		},
		"memory.capture.hook.completed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "onAgentEnd",
			"line": 246,
			"column": 3,
			"file_hash": "d6aac88a9eced36f737484a5d662ba1b426e8ee72a9daebd0f5dca60f8365c12"
		},
		"memory.auto_recall.query.limited": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 134,
			"column": 3,
			"file_hash": "e1f8d75d4fcb54d80eea32f01b2d791705ef41f52d5f81c2c75864585d07a461"
		},
		"memory.auto_recall.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 301,
			"column": 4,
			"file_hash": "e1f8d75d4fcb54d80eea32f01b2d791705ef41f52d5f81c2c75864585d07a461"
		},
		"memory.auto_recall.completed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 310,
			"column": 3,
			"file_hash": "e1f8d75d4fcb54d80eea32f01b2d791705ef41f52d5f81c2c75864585d07a461"
		},
		"memory.auto_recall.telemetry.skipped": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "recordAutoRecallUsage",
			"line": 332,
			"column": 4,
			"file_hash": "e1f8d75d4fcb54d80eea32f01b2d791705ef41f52d5f81c2c75864585d07a461"
		},
		"memory.auto_recall.telemetry.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "recordAutoRecallUsage",
			"line": 367,
			"column": 4,
			"file_hash": "e1f8d75d4fcb54d80eea32f01b2d791705ef41f52d5f81c2c75864585d07a461"
		},
		"plugin.sno-station-mem-insight-distill-factory.buildInsightDistiller.8b084be5ca": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 50,
			"column": 3,
			"file_hash": "3e812050249d4a1852007f1d15578aa11c0f5bf11e4f537346eb5364c0815884"
		},
		"plugin.sno-station-mem-insight-distill-factory.buildInsightDistiller.6cdc733c64": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 57,
			"column": 3,
			"file_hash": "3e812050249d4a1852007f1d15578aa11c0f5bf11e4f537346eb5364c0815884"
		},
		"sno-station-mem-insight-distill-factory.buildInsightDistiller.847c5ab779": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 61,
			"column": 3,
			"file_hash": "3e812050249d4a1852007f1d15578aa11c0f5bf11e4f537346eb5364c0815884"
		},
		"plugin.sno-station-mem-insight-distill-factory.buildInsightDistiller.888f96bfef": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 113,
			"column": 3,
			"file_hash": "3e812050249d4a1852007f1d15578aa11c0f5bf11e4f537346eb5364c0815884"
		},
		"plugin.sno-station-mem-runtime-mode.runObserveLifecycleTask.d1856ccb13": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-runtime-mode.ts",
			"function": "runObserveLifecycleTask",
			"line": 55,
			"column": 6,
			"file_hash": "895ae8495019cdde4e33fa6f561a70cf8c14a1082e982fd5ea033401ddfed92d"
		},
		"plugin.sno-station-mem-runtime-mode.auditMissingHookAgentIdentity.f06795892a": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-runtime-mode.ts",
			"function": "auditMissingHookAgentIdentity",
			"line": 123,
			"column": 2,
			"file_hash": "895ae8495019cdde4e33fa6f561a70cf8c14a1082e982fd5ea033401ddfed92d"
		},
		"memdump.main.failed": {
			"file": "packages/memory/src/engine/diagnostics/memdump.ts",
			"function": "<module>",
			"line": 316,
			"column": 3,
			"file_hash": "85996639d8c10ba1f1c010c1ca902295cacae214b1f22e13a7412620af9fff91"
		},
		"trace.appendQaTrace.164bcaddd4": {
			"file": "packages/memory/src/engine/eval/trace.ts",
			"function": "appendQaTrace",
			"line": 141,
			"column": 3,
			"file_hash": "fd7c6b9f090f1d04ac5da17beb511ef559857ee8c96373b82ce2302ab65286c8"
		},
		"trace.writeConfigSnapshot.completed": {
			"file": "packages/memory/src/engine/eval/trace.ts",
			"function": "writeConfigSnapshot",
			"line": 225,
			"column": 4,
			"file_hash": "fd7c6b9f090f1d04ac5da17beb511ef559857ee8c96373b82ce2302ab65286c8"
		},
		"extraction.atomic-extraction-gauntlet.runAtomicExtractionGauntlet.365701f979": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-gauntlet.ts",
			"function": "runAtomicExtractionGauntlet",
			"line": 216,
			"column": 3,
			"file_hash": "5eff966a46b157425288ddd28391fc796cbcc201299450a9313d11794a45652e"
		},
		"extraction.atomic-extraction-reply.invalid_time": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "wireTimeSchema",
			"line": 90,
			"column": 2,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.projectRecord.327508ac5f": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 145,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.omitted_time": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 152,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.projectRecord.aac5440fc2": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 157,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.projectRecord.b92c90f285": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 164,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.salvage_ids": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "parseAtomicCaptureReply",
			"line": 318,
			"column": 4,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.salvage_spans": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "parseAtomicCaptureReply",
			"line": 323,
			"column": 4,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.unresolved_enrichment_time": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "warnUnresolvedEnrichmentTime",
			"line": 349,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-generic-extractor.enrichAtomicBatch": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "enrichAtomicBatch",
			"line": 237,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.7456414b06": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 462,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.a373dfa454": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 470,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.dc917b09a1": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 485,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.5264647de8": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 494,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.5f797c1175": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 570,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.fdcb677e24": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 572,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicGenericExtractionPass.cce4a719a3": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "captureAtomicWindow",
			"line": 792,
			"column": 4,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-generic-extractor.runAtomicGenericExtractionPass.98a701bd95": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "captureAtomicWindow",
			"line": 816,
			"column": 3,
			"file_hash": "1bfd06f955cb387f94240b0be53cb7ce65f7f31c55b755f312dc5f19588664d4"
		},
		"extraction.atomic-memory-extraction.extractAndPersist.7e1c9d2660": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "extractAndPersist",
			"line": 697,
			"column": 4,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"memory.capture.completed": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "extractAndPersist",
			"line": 850,
			"column": 4,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.readStandingSubjectCandidates.b88c6fb3aa": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "readStandingSubjectCandidates",
			"line": 988,
			"column": 5,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.reaskStandingSubjects.1288498dec": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "reaskStandingSubjects",
			"line": 1242,
			"column": 4,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.reaskStandingSubjects.2b8785b171": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "reaskStandingSubjects",
			"line": 1251,
			"column": 2,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.runAtomicMemoryExtraction.304a5a8d5c": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1521,
			"column": 3,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.over_token_ceiling": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1603,
			"column": 3,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.runAtomicMemoryExtraction.0d9673d494": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1670,
			"column": 4,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"memory.extraction.window.completed": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1688,
			"column": 3,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.judgeArrivalRetirementPair.call_failed": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "judgeArrivalRetirementPair",
			"line": 1725,
			"column": 3,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-memory-extraction.judgeArrivalRetirementPair.reply_invalid": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "judgeArrivalRetirementPair",
			"line": 1733,
			"column": 3,
			"file_hash": "1f3a0611b1a3f3ec86d854e47b22c1d9f8f26f87bbabca9c01ea6f2edeb92575"
		},
		"extraction.atomic-progress-boundary.salvage_decisions": {
			"file": "packages/memory/src/engine/extraction/atomic-progress-boundary.ts",
			"function": "parseProgressTurns",
			"line": 27,
			"column": 3,
			"file_hash": "c57ad88dba4fde39aaf635b57e556a8380c7cc9252d655de32a43045e402abc1"
		},
		"extraction.atomic-subject-guard.runAtomicSubjectGuard.037dc017c1": {
			"file": "packages/memory/src/engine/extraction/atomic-subject-guard.ts",
			"function": "runAtomicSubjectGuard",
			"line": 277,
			"column": 3,
			"file_hash": "573e80974a2d733677afbb5e5249b18676cf80cc2ab8d16f13f8a892836ab5c7"
		},
		"extraction.atomic-subject-guard.runAtomicSubjectGuard.7fbb9c4f6d": {
			"file": "packages/memory/src/engine/extraction/atomic-subject-guard.ts",
			"function": "runAtomicSubjectGuard",
			"line": 296,
			"column": 3,
			"file_hash": "573e80974a2d733677afbb5e5249b18676cf80cc2ab8d16f13f8a892836ab5c7"
		},
		"b-profile-section-dictionary-provider.restoreCachedSectionDictionary.a4518aedd5": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "restoreCachedSectionDictionary",
			"line": 252,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.ac5ddcab10": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 292,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.a8ecb1a4f2": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 322,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.15ee874f33": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 345,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.b452a7657e": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 94,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.4494531e35": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 116,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.5276d7dfea": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 125,
			"column": 4,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.1acb6c65f8": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 141,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.d8bb76de51": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 150,
			"column": 4,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.ce06a215a3": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 175,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.<anonymous callback>.9cc8218e54": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "<anonymous callback>",
			"line": 196,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.assertPlanReconciles.03748b5c20": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "assertPlanReconciles",
			"line": 890,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.assertCanonicalPlanReconciles.2ad72089d1": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "assertCanonicalPlanReconciles",
			"line": 902,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.throwReconciliationError.b59b599311": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "throwReconciliationError",
			"line": 912,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"date-resolution.model_unavailable": {
			"file": "packages/memory/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 80,
			"column": 3,
			"file_hash": "4cf43ad529310dab414d0c56a4cba835d1b62f401269edde7c0fff07d2718180"
		},
		"date-resolution.resolveMemoryDate.1224fa35b2": {
			"file": "packages/memory/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 88,
			"column": 2,
			"file_hash": "4cf43ad529310dab414d0c56a4cba835d1b62f401269edde7c0fff07d2718180"
		},
		"embedding-provider-client.<anonymous callback>.3c8d5ee192": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 72,
			"column": 3,
			"file_hash": "da458d3ba4d41e8b87027b996c516530f99933bc4b6a245bfe7ddc91fc8f7e83"
		},
		"embedding-provider-client.embed.ab60111378": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embed",
			"line": 173,
			"column": 3,
			"file_hash": "da458d3ba4d41e8b87027b996c516530f99933bc4b6a245bfe7ddc91fc8f7e83"
		},
		"embedding-provider-client.embedDirect.c6998ac2fb": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedDirect",
			"line": 206,
			"column": 4,
			"file_hash": "da458d3ba4d41e8b87027b996c516530f99933bc4b6a245bfe7ddc91fc8f7e83"
		},
		"embedding-provider-client.embedMany.8ffe2fb365": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedMany",
			"line": 224,
			"column": 3,
			"file_hash": "da458d3ba4d41e8b87027b996c516530f99933bc4b6a245bfe7ddc91fc8f7e83"
		},
		"embedding-provider-client.embedMany.71b35eadaf": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedMany",
			"line": 243,
			"column": 4,
			"file_hash": "da458d3ba4d41e8b87027b996c516530f99933bc4b6a245bfe7ddc91fc8f7e83"
		},
		"embedding-provider-client.<anonymous callback>.32cc9ec43e": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 294,
			"column": 5,
			"file_hash": "da458d3ba4d41e8b87027b996c516530f99933bc4b6a245bfe7ddc91fc8f7e83"
		},
		"embedding-provider-client.<anonymous callback>.d7a3f8337c": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 301,
			"column": 5,
			"file_hash": "da458d3ba4d41e8b87027b996c516530f99933bc4b6a245bfe7ddc91fc8f7e83"
		},
		"extraction.extraction-text-sanitizer.boundSectionContent.ceiling": {
			"file": "packages/memory/src/engine/extraction/extraction-text-sanitizer.ts",
			"function": "boundSectionContent",
			"line": 48,
			"column": 2,
			"file_hash": "57c114de4c1c67ea85455288b3892f1153173e64b1b967fd95eb1e50e2924a81"
		},
		"insight-distill-write-actions.sessionTimestampField.29d4b22da7": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "sessionTimestampField",
			"line": 417,
			"column": 3,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.storeCandidate.138415ce64": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "storeCandidate",
			"line": 508,
			"column": 3,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.storeCandidate.6754f6ee4b": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "storeCandidate",
			"line": 519,
			"column": 3,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.handleSupport.c98c47eeb9": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleSupport",
			"line": 555,
			"column": 2,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.handleContextualize.bd66df2159": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleContextualize",
			"line": 615,
			"column": 2,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.handleContradict.c6164031da": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleContradict",
			"line": 692,
			"column": 2,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"profile-section-writer.deferLifecycleRetirement.f94b354ff4": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "deferLifecycleRetirement",
			"line": 323,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"memory.profile.task.completed": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 451,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"memory.profile.section.completed": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 481,
			"column": 2,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"memory.profile.failed": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 492,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.28936dcd3c": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 676,
			"column": 4,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.e3afdfb6d8": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 749,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.80241da6d8": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 805,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.recheckProfileRetirements.613c569527": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "recheckProfileRetirements",
			"line": 982,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.mergeProfileSection.c707285ef3": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "mergeProfileSection",
			"line": 1087,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.writeEpisodicSafetyNet.ae69446388": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "writeEpisodicSafetyNet",
			"line": 1390,
			"column": 2,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.capRetireByNameWorkItems.3c47653418": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "capRetireByNameWorkItems",
			"line": 1630,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.writeProfileRow.3e3e26a255": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "writeProfileRow",
			"line": 1668,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.planProfileConflicts.e5bcea94ce": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2139,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.planProfileConflicts.97b6a2e824": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2205,
			"column": 5,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.planProfileConflicts.b4962bc7f0": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2225,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.logProfileConflictFenceRejection.b0669b40b3": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "logProfileConflictFenceRejection",
			"line": 2249,
			"column": 2,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"profile-section-writer.adjudicateSafely.d3f7ab0ac5": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "adjudicateSafely",
			"line": 2296,
			"column": 3,
			"file_hash": "e310161e611c7279215d36f13e1b6630f37b36a8bb4d6fac5309cc3927e1fd9f"
		},
		"language.detector.unavailable": {
			"file": "packages/memory/src/engine/i18n/detector.ts",
			"function": "markDetectorBroken",
			"line": 29,
			"column": 2,
			"file_hash": "40e7e7a9f28c2bc552645bbeb6b6df4dd73f03b80144d5fe306cce2eff3eee52"
		},
		"registry.loadLocale.aad78d489e": {
			"file": "packages/memory/src/engine/i18n/registry.ts",
			"function": "loadLocale",
			"line": 58,
			"column": 3,
			"file_hash": "d06faf72925fb311d6439b3fe47c44d3df19ce8b7ddfe4f8a6b4710103455f8e"
		},
		"memory.group_crud.host_calls_skipped": {
			"file": "packages/memory/src/engine/maintenance/run-group-crud-maintenance.ts",
			"function": "main",
			"line": 50,
			"column": 4,
			"file_hash": "44448861cd3ea5fa9d6da20bd4e5cd58309727ea63122217f9e492749de8f07e"
		},
		"observability.emit.failed": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "PluginObservability.tryEmit",
			"line": 127,
			"column": 4,
			"file_hash": "584c28e6e23aaed613d88fcc0998a5ec2abdc0b3b0186cb1fddf7c798c217f9d"
		},
		"adapter.<anonymous callback>.82f49c57a7": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 151,
			"column": 7,
			"file_hash": "584c28e6e23aaed613d88fcc0998a5ec2abdc0b3b0186cb1fddf7c798c217f9d"
		},
		"observability.background.timed_out": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "PluginObservability.runBackgroundTask",
			"line": 205,
			"column": 7,
			"file_hash": "584c28e6e23aaed613d88fcc0998a5ec2abdc0b3b0186cb1fddf7c798c217f9d"
		},
		"adapter.<anonymous callback>.f036514cb8": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 242,
			"column": 9,
			"file_hash": "584c28e6e23aaed613d88fcc0998a5ec2abdc0b3b0186cb1fddf7c798c217f9d"
		},
		"adapter.<anonymous callback>.9aedc01548": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 281,
			"column": 9,
			"file_hash": "584c28e6e23aaed613d88fcc0998a5ec2abdc0b3b0186cb1fddf7c798c217f9d"
		},
		"adapter.<anonymous callback>.52f64c2607": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 323,
			"column": 9,
			"file_hash": "584c28e6e23aaed613d88fcc0998a5ec2abdc0b3b0186cb1fddf7c798c217f9d"
		},
		"observability.bestEffort.failed": {
			"file": "packages/memory/src/engine/observability/best-effort.ts",
			"function": "bestEffort",
			"line": 23,
			"column": 3,
			"file_hash": "fadc0065ebbb451c41b27b4371383815f97eefcb845bab26d36a2cffd2ad0540"
		},
		"observability.bestEffortSync.failed": {
			"file": "packages/memory/src/engine/observability/best-effort.ts",
			"function": "bestEffortSync",
			"line": 40,
			"column": 3,
			"file_hash": "fadc0065ebbb451c41b27b4371383815f97eefcb845bab26d36a2cffd2ad0540"
		},
		"runtime.process.started": {
			"file": "packages/memory/src/engine/observability/runtime-diagnostics.ts",
			"function": "emitRuntimeStartSnapshot",
			"line": 64,
			"column": 2,
			"file_hash": "062ff3cb79ceccc652070d5c6ea3f1fc451577e20c1337425ff9509d60c1ef6d"
		},
		"memory.operation.aborted": {
			"file": "packages/memory/src/engine/operation-cancellation.ts",
			"function": "withMemoryOperation",
			"line": 24,
			"column": 24,
			"file_hash": "e4b79bb7c3033ee9e03af8e9c580a5f695c4ce24740ee8d0d5671a350f66823b"
		},
		"memory.spend.stat.failed": {
			"file": "packages/memory/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 39,
			"column": 4,
			"file_hash": "d84c2c09924ba4013d03677cb00d8748394ff903d87bf215c6845378e1f4c186"
		},
		"memory.spend.stream.failed": {
			"file": "packages/memory/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 103,
			"column": 3,
			"file_hash": "d84c2c09924ba4013d03677cb00d8748394ff903d87bf215c6845378e1f4c186"
		},
		"memory.spend.rows.invalid": {
			"file": "packages/memory/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 109,
			"column": 26,
			"file_hash": "d84c2c09924ba4013d03677cb00d8748394ff903d87bf215c6845378e1f4c186"
		},
		"memory.jsonl.read.failed": {
			"file": "packages/memory/src/engine/operations/jsonl-lines.ts",
			"function": "readJsonlLines",
			"line": 15,
			"column": 3,
			"file_hash": "d3833ca8d82845c46163b92ce720917961a6dd543676bb57ff0e53930a17cba8"
		},
		"memory.learning.lock.close.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 105,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.lock.cleanup.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 110,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.lock.stat.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 124,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.lock.stale.cleanup.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 133,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.history.read.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "nextLearningId",
			"line": 155,
			"column": 4,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.ensure.read.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "ensureLearningFile",
			"line": 175,
			"column": 4,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.append.read.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "appendSelfImprovementEntry",
			"line": 306,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.audit.append.failed": {
			"file": "packages/memory/src/engine/operations/runtime-audit-log.ts",
			"function": "enqueueAuditWrite",
			"line": 297,
			"column": 4,
			"file_hash": "0c6396aee17b5450a4a285cdaee2241a30f49e4a822899a8bd17554dbe939825"
		},
		"memory.audit.detail.unknown": {
			"file": "packages/memory/src/engine/operations/runtime-audit-log.ts",
			"function": "prepareAuditEntry",
			"line": 356,
			"column": 4,
			"file_hash": "0c6396aee17b5450a4a285cdaee2241a30f49e4a822899a8bd17554dbe939825"
		},
		"memory.audit.sync.failed": {
			"file": "packages/memory/src/engine/operations/runtime-audit-log.ts",
			"function": "appendAuditEntrySync",
			"line": 406,
			"column": 3,
			"file_hash": "0c6396aee17b5450a4a285cdaee2241a30f49e4a822899a8bd17554dbe939825"
		},
		"memory.session.file.stat.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "sortFileNamesByMtimeDesc",
			"line": 33,
			"column": 6,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.read.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionMessages",
			"line": 135,
			"column": 4,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.rows.invalid": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionMessages",
			"line": 141,
			"column": 40,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.reset.discovery.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionContentWithResetFallback",
			"line": 179,
			"column": 4,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.previous.discovery.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "findPreviousSessionFile",
			"line": 238,
			"column": 4,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"stale-memory-demotion.runStaleDemotion.e86f004935": {
			"file": "packages/memory/src/engine/operations/stale-memory-demotion.ts",
			"function": "runStaleDemotion",
			"line": 96,
			"column": 4,
			"file_hash": "a30813cb8831d3d79008b715c8b51163020c607296cf67a3e1beffed82995718"
		},
		"stale-memory-demotion.runStaleDemotion.d7a77107bb": {
			"file": "packages/memory/src/engine/operations/stale-memory-demotion.ts",
			"function": "runStaleDemotion",
			"line": 108,
			"column": 2,
			"file_hash": "a30813cb8831d3d79008b715c8b51163020c607296cf67a3e1beffed82995718"
		},
		"memory.provider.canonical.discovery.degraded": {
			"file": "packages/memory/src/engine/provider/canonical-memory-corpus.ts",
			"function": "listCanonicalMemoryFiles",
			"line": 243,
			"column": 40,
			"file_hash": "9f11af337ab01fec185f3a6401346d3e98757259425ac413c762e7416b3843a7"
		},
		"memory.provider.manager.resolved": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.getMemorySearchManager",
			"line": 157,
			"column": 5,
			"file_hash": "ad6dc413ac3a62631c4be5c47a0abd51e341185cf3644f8d13682da29f0fa72b"
		},
		"memory.provider.manager.close.skipped": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeMemorySearchManager",
			"line": 175,
			"column": 5,
			"file_hash": "ad6dc413ac3a62631c4be5c47a0abd51e341185cf3644f8d13682da29f0fa72b"
		},
		"memory.provider.manager.close.failed": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeMemorySearchManager",
			"line": 193,
			"column": 5,
			"file_hash": "ad6dc413ac3a62631c4be5c47a0abd51e341185cf3644f8d13682da29f0fa72b"
		},
		"memory.provider.managers.shutdown.completed": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeAllMemorySearchManagers",
			"line": 221,
			"column": 5,
			"file_hash": "ad6dc413ac3a62631c4be5c47a0abd51e341185cf3644f8d13682da29f0fa72b"
		},
		"memory.provider.search.completed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.search",
			"line": 200,
			"column": 4,
			"file_hash": "2849bddd7c2cdabfd9d438dc4c4c139795b26a955befe846f10314ef03446e2c"
		},
		"memory.provider.read.completed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.readFile",
			"line": 259,
			"column": 4,
			"file_hash": "2849bddd7c2cdabfd9d438dc4c4c139795b26a955befe846f10314ef03446e2c"
		},
		"memory.provider.status.completed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.status",
			"line": 286,
			"column": 3,
			"file_hash": "2849bddd7c2cdabfd9d438dc4c4c139795b26a955befe846f10314ef03446e2c"
		},
		"memory.provider.status.failed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.status",
			"line": 318,
			"column": 4,
			"file_hash": "2849bddd7c2cdabfd9d438dc4c4c139795b26a955befe846f10314ef03446e2c"
		},
		"memory.provider.manager.closed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.close",
			"line": 389,
			"column": 3,
			"file_hash": "2849bddd7c2cdabfd9d438dc4c4c139795b26a955befe846f10314ef03446e2c"
		},
		"reflection.daily-log-generator.onRetryLog.b52810f5af": {
			"file": "packages/memory/src/engine/reflection/daily-log-generator.ts",
			"function": "onRetryLog",
			"line": 225,
			"column": 25,
			"file_hash": "aeec7e0634526bb3da69fa073076e632cfcd48a13745e59d9897dcad49d5dbe4"
		},
		"reflection.daily-log-generator.onRetryLog.977c99d43c": {
			"file": "packages/memory/src/engine/reflection/daily-log-generator.ts",
			"function": "onRetryLog",
			"line": 226,
			"column": 8,
			"file_hash": "aeec7e0634526bb3da69fa073076e632cfcd48a13745e59d9897dcad49d5dbe4"
		},
		"reflection.daily-log-generator.generateReflectionText.c0c554e65c": {
			"file": "packages/memory/src/engine/reflection/daily-log-generator.ts",
			"function": "generateReflectionText",
			"line": 256,
			"column": 4,
			"file_hash": "aeec7e0634526bb3da69fa073076e632cfcd48a13745e59d9897dcad49d5dbe4"
		},
		"memory.reflection.command.completed": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "createRunMemoryReflection",
			"line": 131,
			"column": 4,
			"file_hash": "41a41a5385b4bf5f790c2c4a48f75d512c39ccbdb93624ca5f5917ccafdb678e"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.be803e8310": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 224,
			"column": 4,
			"file_hash": "41a41a5385b4bf5f790c2c4a48f75d512c39ccbdb93624ca5f5917ccafdb678e"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.2a047c8826": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 259,
			"column": 3,
			"file_hash": "41a41a5385b4bf5f790c2c4a48f75d512c39ccbdb93624ca5f5917ccafdb678e"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.55c5adf2a5": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 264,
			"column": 3,
			"file_hash": "41a41a5385b4bf5f790c2c4a48f75d512c39ccbdb93624ca5f5917ccafdb678e"
		},
		"reflection.reflection-command-hooks.appendGovernanceEntries.805fa046d0": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "appendGovernanceEntries",
			"line": 414,
			"column": 4,
			"file_hash": "41a41a5385b4bf5f790c2c4a48f75d512c39ccbdb93624ca5f5917ccafdb678e"
		},
		"reflection.reflection-injection-hooks.registerInheritedRulesHook.43c14eb8b9": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerInheritedRulesHook",
			"line": 165,
			"column": 5,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerDerivedFocusHook.d23bb07c04": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerDerivedFocusHook",
			"line": 187,
			"column": 6,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerDerivedFocusHook.bbe1a0ae1e": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerDerivedFocusHook",
			"line": 223,
			"column": 5,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerV3SliceHook.d23bb07c04": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerV3SliceHook",
			"line": 267,
			"column": 6,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerV3SliceHook.1800747d30": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerV3SliceHook",
			"line": 293,
			"column": 5,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.d4cb1a8408": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 108,
			"column": 3,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.4f891b1d21": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 112,
			"column": 3,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.78a7536d17": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 165,
			"column": 6,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.38fe983443": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 250,
			"column": 4,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.b692a46de7": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 259,
			"column": 3,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.session-serial-guard.runWithSerialGuard.edb3193695": {
			"file": "packages/memory/src/engine/reflection/session-serial-guard.ts",
			"function": "runWithSerialGuard",
			"line": 110,
			"column": 3,
			"file_hash": "5441ac8f03d8760fc68261917bc9deab52ee775389f5eef28282fef555a3c08b"
		},
		"reflection.session-serial-guard.runWithSerialGuard.2e95bc0994": {
			"file": "packages/memory/src/engine/reflection/session-serial-guard.ts",
			"function": "runWithSerialGuard",
			"line": 116,
			"column": 3,
			"file_hash": "5441ac8f03d8760fc68261917bc9deab52ee775389f5eef28282fef555a3c08b"
		},
		"rem.stage.journal.failed": {
			"file": "packages/memory/src/engine/rem/runner.ts",
			"function": "runRemStages",
			"line": 41,
			"column": 4,
			"file_hash": "87abefc5c865c82a6946d21e0d0e6faa50aa09f6d1ccf58db5103b3994a49674"
		},
		"access-tracker.destroy.5991e0f580": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "destroy",
			"line": 320,
			"column": 4,
			"file_hash": "7fb932287e54de3bd003e2a23df3902dd6a3cd7842bc1e9c3d0cfbd6cbd49253"
		},
		"access-tracker.doFlush.b3bb3939f2": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "doFlush",
			"line": 367,
			"column": 6,
			"file_hash": "7fb932287e54de3bd003e2a23df3902dd6a3cd7842bc1e9c3d0cfbd6cbd49253"
		},
		"access-tracker.doFlush.f82865a307": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "doFlush",
			"line": 382,
			"column": 4,
			"file_hash": "7fb932287e54de3bd003e2a23df3902dd6a3cd7842bc1e9c3d0cfbd6cbd49253"
		},
		"access-tracker.buildAccessDelta.4ac8f20936": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "buildAccessDelta",
			"line": 427,
			"column": 5,
			"file_hash": "7fb932287e54de3bd003e2a23df3902dd6a3cd7842bc1e9c3d0cfbd6cbd49253"
		},
		"query_manifest.capture.written": {
			"file": "packages/memory/src/engine/retrieval/query-manifest-capture-cli.ts",
			"function": "main",
			"line": 220,
			"column": 3,
			"file_hash": "ecfc057eacaef7ed933f7b5a9cbb0e14d5fe3150ac1458dd4afe64b6d449c28c"
		},
		"query_manifest.capture.failed": {
			"file": "packages/memory/src/engine/retrieval/query-manifest-capture-cli.ts",
			"function": "<module>",
			"line": 227,
			"column": 2,
			"file_hash": "ecfc057eacaef7ed933f7b5a9cbb0e14d5fe3150ac1458dd4afe64b6d449c28c"
		},
		"memory.retrieval.started": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 41,
			"column": 3,
			"file_hash": "0eb0825667d74033232bc305d6d94e155900b659880c8e57d7d3d5526bb03b43"
		},
		"memory.retrieval.completed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 173,
			"column": 4,
			"file_hash": "0eb0825667d74033232bc305d6d94e155900b659880c8e57d7d3d5526bb03b43"
		},
		"memory.retrieval.failed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 185,
			"column": 4,
			"file_hash": "0eb0825667d74033232bc305d6d94e155900b659880c8e57d7d3d5526bb03b43"
		},
		"memory.retrieval.traced.completed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieveWithTrace",
			"line": 260,
			"column": 4,
			"file_hash": "0eb0825667d74033232bc305d6d94e155900b659880c8e57d7d3d5526bb03b43"
		},
		"memory.retrieval.traced.failed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieveWithTrace",
			"line": 268,
			"column": 4,
			"file_hash": "0eb0825667d74033232bc305d6d94e155900b659880c8e57d7d3d5526bb03b43"
		},
		"memory.retrieval.tier.failed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "evaluateTopKTierTransitions",
			"line": 337,
			"column": 5,
			"file_hash": "0eb0825667d74033232bc305d6d94e155900b659880c8e57d7d3d5526bb03b43"
		},
		"retrieval.retriever-rerank.rerank.6fbc6b3a22": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 192,
			"column": 4,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.rerank.query_over_window": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 240,
			"column": 4,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.rerank.candidate_over_ceiling": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 255,
			"column": 4,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.runBatch.over_window_repair": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 338,
			"column": 8,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.runBatch.76d7d1fac6": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 348,
			"column": 7,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.runBatch.4429b8bd8a": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 363,
			"column": 7,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.rerank.7847c6248a": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 477,
			"column": 4,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.rerank.4af9c17c75": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 502,
			"column": 5,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.rerank.2c5fc67dbf": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 509,
			"column": 5,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.rerankLightweight.70eb2031f1": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerankLightweight",
			"line": 581,
			"column": 4,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-rerank.rerankLightweight.7e8d0eee29": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerankLightweight",
			"line": 586,
			"column": 3,
			"file_hash": "cf891f3fe78835c2bbb1e4d9d203c7798716b00c90b9869f45be67003d1b46e5"
		},
		"retrieval.retriever-search-modes.aggregationComplete.5a3b7f9337": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "aggregationComplete",
			"line": 71,
			"column": 3,
			"file_hash": "2a2324e4415451d65b62382434b86411098b187928f489467ee5e13756c0c3f2"
		},
		"retrieval.retriever-search-modes.precisionRecall.97b8770f50": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 245,
			"column": 4,
			"file_hash": "2a2324e4415451d65b62382434b86411098b187928f489467ee5e13756c0c3f2"
		},
		"retrieval.retriever-search-modes.precisionRecall.c20ade60c4": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 253,
			"column": 4,
			"file_hash": "2a2324e4415451d65b62382434b86411098b187928f489467ee5e13756c0c3f2"
		},
		"retrieval.retriever-search-modes.precisionRecall.aaf0b2eb17": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 305,
			"column": 3,
			"file_hash": "2a2324e4415451d65b62382434b86411098b187928f489467ee5e13756c0c3f2"
		},
		"scope-helpers.resolveScopeFilter.0d7f91dae7": {
			"file": "packages/memory/src/engine/security/scope-helpers.ts",
			"function": "resolveScopeFilter",
			"line": 54,
			"column": 3,
			"file_hash": "ec85e30d2a1a110e7844fe4af9ae9c19e47f503ab04444ed9a5ae3bdec71b506"
		},
		"scope-helpers.resolveScopeFilter.720935590d": {
			"file": "packages/memory/src/engine/security/scope-helpers.ts",
			"function": "resolveScopeFilter",
			"line": 67,
			"column": 4,
			"file_hash": "ec85e30d2a1a110e7844fe4af9ae9c19e47f503ab04444ed9a5ae3bdec71b506"
		},
		"scope-identity.isSystemBypassId.1d89371f35": {
			"file": "packages/memory/src/engine/security/scope-identity.ts",
			"function": "isSystemBypassId",
			"line": 36,
			"column": 3,
			"file_hash": "0df23c80fb2db236266fe91a2904be6d2a7cf6bf6e28baae36fb9669a995352e"
		},
		"memory-telemetry-events.<anonymous callback>.23cfef2d08": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-events.ts",
			"function": "<anonymous callback>",
			"line": 100,
			"column": 4,
			"file_hash": "ac7e51647d45930d2f0c85673ea3a889b835a6392a758cff37af19f994d6e823"
		},
		"memory.usage.accept.failed": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.tryAcceptUsage",
			"line": 114,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.claim_failed": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 148,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.empty": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 160,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.rollback": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 215,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.completed": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 233,
			"column": 3,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"observe.ledger.failed": {
			"file": "packages/memory/src/engine/telemetry/observe-ledger.ts",
			"function": "forwardObserveLedger",
			"line": 58,
			"column": 7,
			"file_hash": "d55aceca369305bdba14768ebdeb98c0654b3d67817e01884d82d754f11294a8"
		},
		"shared.llm-client.resolveRequestTransport.8f631601af": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "resolveRequestTransport",
			"line": 369,
			"column": 4,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"shared.llm-client.resolveRequestTransport.ffa933b519": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "resolveRequestTransport",
			"line": 375,
			"column": 4,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.host.request.completed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 422,
			"column": 6,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.client.host_cancelled": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 440,
			"column": 5,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.client.host_error": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 454,
			"column": 5,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"shared.llm-client.requestContent.ff17976562": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 486,
			"column": 5,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.client.raw_pipeline_failed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 508,
			"column": 5,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.client.chat_pipeline_failed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 536,
			"column": 4,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.client.empty_reply": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 550,
			"column": 4,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"shared.llm-client.requestContentRetryingEmpty.cd874fefff": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContentRetryingEmpty",
			"line": 577,
			"column": 4,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.client.json.deadline_exhausted": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 603,
			"column": 7,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"shared.llm-client.completeJson.e04c8e7e82": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 618,
			"column": 5,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.client.json.request_failed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 624,
			"column": 5,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"shared.llm-client.completeText.ffa933b519": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeText",
			"line": 645,
			"column": 5,
			"file_hash": "b946f36ced54d1fb89dc1097df1e788612759fff968df557a3b9ac1b562cf547"
		},
		"llm.transport.request.completed": {
			"file": "packages/memory/src/model/llm-provider-transport.ts",
			"function": "observeRequest",
			"line": 68,
			"column": 4,
			"file_hash": "9c6ab2f8ad159409334ac0adcd8caf351209b16c3f72072938a8959c892e03f6"
		},
		"memory.host.degraded": {
			"file": "packages/memory/src/model/registered-agent-port.ts",
			"function": "run",
			"line": 34,
			"column": 17,
			"file_hash": "b477adf0a693cdfa03376f058f63864ae082e91e3348c8b676a63d9c4176a95f"
		},
		"sidecar.config.failed": {
			"file": "packages/memory/src/sidecar/config.ts",
			"function": "reportConfigFailure",
			"line": 87,
			"column": 2,
			"file_hash": "2062c1f8fabf5d2e0141b7f3669916286937d644eb293093e00028d1ea8bf88b"
		},
		"sidecar.main.startup.failed": {
			"file": "packages/memory/src/sidecar/main.ts",
			"function": "<module>",
			"line": 21,
			"column": 3,
			"file_hash": "ab8eb29a22012e9c52b1518bfd42df26b008feb90885a9312bb461d3527e1acc"
		},
		"sidecar.main.start_snapshot.skipped": {
			"file": "packages/memory/src/sidecar/main.ts",
			"function": "<module>",
			"line": 35,
			"column": 2,
			"file_hash": "ab8eb29a22012e9c52b1518bfd42df26b008feb90885a9312bb461d3527e1acc"
		},
		"memory.sidecar.request.failed": {
			"file": "packages/memory/src/sidecar/memory-routes.ts",
			"function": "serveMemoryRoute",
			"line": 44,
			"column": 4,
			"file_hash": "5f99f837b74d477142a84ff23dcde601f6e18ea9227fbb078de77c04dad51071"
		},
		"memory.sidecar.engine.message": {
			"file": "packages/memory/src/sidecar/memory-runtime.ts",
			"function": "engineLog",
			"line": 61,
			"column": 2,
			"file_hash": "15fb85141106859b0cc8566dd0bf0829722898f368a23fa741bc7d85ad787782"
		},
		"memory.sidecar.usage.failed": {
			"file": "packages/memory/src/sidecar/memory-runtime.ts",
			"function": "<anonymous callback>",
			"line": 346,
			"column": 5,
			"file_hash": "15fb85141106859b0cc8566dd0bf0829722898f368a23fa741bc7d85ad787782"
		},
		"rem-batch-executor.onStageError.d5f24d50d3": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "onStageError",
			"line": 374,
			"column": 6,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.runRemBatchJobUnlocked.55c52b91cf": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runRemBatchJobUnlocked",
			"line": 511,
			"column": 5,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"sidecar.batch.completed": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runRemBatchJobUnlocked",
			"line": 582,
			"column": 4,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.openBatchRuntime.86fa720e8f": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "openBatchRuntime",
			"line": 652,
			"column": 3,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.onProviderResponse.df4f2d4fa1": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "onProviderResponse",
			"line": 674,
			"column": 5,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.runUpdate.dbf2a836db": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 939,
			"column": 3,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.runUpdate.7dfc387204": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 1014,
			"column": 4,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.runUpdate.7ffc737c24": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 1058,
			"column": 4,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.runReplace.e1e35e40e9": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2381,
			"column": 3,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.runReplace.de3a5f3ce3": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2588,
			"column": 4,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.runReplace.e4be8cfe8f": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2834,
			"column": 4,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"memory.rem.refusal.release_failed": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2960,
			"column": 6,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.buildRemReplaceCandidateQueue.25aa1a67a6": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "buildRemReplaceCandidateQueue",
			"line": 3180,
			"column": 3,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem-batch-executor.reserveReplaceStage.4e67e45fd5": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "reserveReplaceStage",
			"line": 3688,
			"column": 2,
			"file_hash": "8117e2ea2eb9c0181bc41e35b9f9768cb75eecde4062289727e8068996133664"
		},
		"rem.journal.failed": {
			"file": "packages/memory/src/sidecar/rem-job-store.ts",
			"function": "reportFailure",
			"line": 364,
			"column": 3,
			"file_hash": "edbc3ba019efdda1b84402247fac659b1fbcff1cb4537fea48f15943de737291"
		},
		"memory.rem.trigger.configuration.unavailable": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "readRemAutomaticOperations",
			"line": 91,
			"column": 3,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"memory.rem.trigger.state.unavailable": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 151,
			"column": 3,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.1d59077a5c": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 179,
			"column": 4,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.ebe1cdd204": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 191,
			"column": 5,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.46669e66ff": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 201,
			"column": 5,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"memory.rem.trigger.state.write.failed": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 222,
			"column": 18,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"sidecar.trigger.dispatch.accepted": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "dispatchRemWave",
			"line": 349,
			"column": 3,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"sidecar.trigger.audit_read.failed": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "applyCompletedBaselines",
			"line": 368,
			"column": 3,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"sidecar.trigger.audit_records.skipped": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "applyCompletedBaselines",
			"line": 461,
			"column": 3,
			"file_hash": "452c80174290c56976360d8a4ab641dc667aef6449a9022f252aa4e685922bfe"
		},
		"sidecar.duplicate.exit": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "bindSidecarSocket",
			"line": 148,
			"column": 6,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.<anonymous callback>.5eb5a60e6b": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "<anonymous callback>",
			"line": 204,
			"column": 3,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.<anonymous callback>.47c4662916": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "recordRequest",
			"line": 239,
			"column": 4,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.<anonymous callback>.a7a2656a08": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "<anonymous callback>",
			"line": 272,
			"column": 5,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"sidecar.discovery.published": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "publishDiscovery",
			"line": 302,
			"column": 30,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"sidecar.discovery.failed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "publishDiscovery",
			"line": 307,
			"column": 4,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.startLockedRemSidecar.96a92b085b": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startLockedRemSidecar",
			"line": 327,
			"column": 2,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"sidecar.shutdown.timeout": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startRemSidecar.stop",
			"line": 362,
			"column": 7,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"sidecar.shutdown.task.running": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startRemSidecar.stop",
			"line": 370,
			"column": 8,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"sidecar.shutdown.completed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startRemSidecar.stop",
			"line": 385,
			"column": 5,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.routeRequest.0ea180a77c": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "routeRequest",
			"line": 455,
			"column": 3,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.runChassisJob.e7639bd8fc": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "runChassisJob",
			"line": 658,
			"column": 6,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"sidecar.job.completed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "runChassisJob",
			"line": 683,
			"column": 4,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.failNonTerminalJob.cf84e07c6d": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "failNonTerminalJob",
			"line": 753,
			"column": 3,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"server.recoverInterruptedJobs.15309ea841": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "recoverInterruptedJobs",
			"line": 788,
			"column": 4,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"sidecar.operation.failed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "reportSidecarFailure",
			"line": 964,
			"column": 2,
			"file_hash": "3b947c33cb7da9e587b71b29faf117ddfdf0792ce09f2b9f0a49245403a88b60"
		},
		"active-task-carrier-backfill.backfillActiveTaskCarriers.facdae917f": {
			"file": "packages/memory/src/store/active-task-carrier-backfill.ts",
			"function": "backfillActiveTaskCarriers",
			"line": 221,
			"column": 2,
			"file_hash": "08a4ad11a94a5dc4ee8766a4a286179658d761754063faae7bae4ce8f06084d0"
		},
		"active-task-carrier-backfill.<anonymous callback>.0bf95b1f61": {
			"file": "packages/memory/src/store/active-task-carrier-backfill.ts",
			"function": "<anonymous callback>",
			"line": 245,
			"column": 3,
			"file_hash": "08a4ad11a94a5dc4ee8766a4a286179658d761754063faae7bae4ce8f06084d0"
		},
		"backup.pruneOldBackups.1dca69b51b": {
			"file": "packages/memory/src/store/backup.ts",
			"function": "removeBackups",
			"line": 97,
			"column": 3,
			"file_hash": "a93ea8f2c18e1fb7c2ce116c66ca59d99453e380f0fcdf693cd83c3fa12aa0e9"
		},
		"backup.runBackup.ca114973f1": {
			"file": "packages/memory/src/store/backup.ts",
			"function": "runBackup",
			"line": 186,
			"column": 2,
			"file_hash": "a93ea8f2c18e1fb7c2ce116c66ca59d99453e380f0fcdf693cd83c3fa12aa0e9"
		},
		"storage.vector.configuration.mismatch": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "ensureChunkVecTable",
			"line": 167,
			"column": 4,
			"file_hash": "79b7a598cd50d029bfc12abd12eb6896bc64e446f51216c733b40005c5c1e727"
		},
		"connection.loadSimpleTokenizer.778ee7da6c": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "loadSimpleTokenizer",
			"line": 221,
			"column": 2,
			"file_hash": "79b7a598cd50d029bfc12abd12eb6896bc64e446f51216c733b40005c5c1e727"
		},
		"connection.initDb.ee37a0a971": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "initDb",
			"line": 286,
			"column": 2,
			"file_hash": "79b7a598cd50d029bfc12abd12eb6896bc64e446f51216c733b40005c5c1e727"
		},
		"storage.setup.failed": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "retrySetup",
			"line": 306,
			"column": 5,
			"file_hash": "79b7a598cd50d029bfc12abd12eb6896bc64e446f51216c733b40005c5c1e727"
		},
		"data-bootstrap.bootstrapDataLayout.4fc42585ae": {
			"file": "packages/memory/src/store/data-bootstrap.ts",
			"function": "bootstrapDataLayout",
			"line": 78,
			"column": 3,
			"file_hash": "2fc676e9779f8ca9d9ad7dfe615225b032f729559581b11ca54d2c913e3a5e68"
		},
		"data-bootstrap.bootstrapDataLayout.4af3189946": {
			"file": "packages/memory/src/store/data-bootstrap.ts",
			"function": "bootstrapDataLayout",
			"line": 108,
			"column": 2,
			"file_hash": "2fc676e9779f8ca9d9ad7dfe615225b032f729559581b11ca54d2c913e3a5e68"
		},
		"maintenance.recoverDerivedFts.753697bd94": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 215,
			"column": 2,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.recoverDerivedFts.2cf5f62053": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 232,
			"column": 3,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.recoverDerivedFts.c07ad948a2": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 243,
			"column": 3,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.failClosed.dd7955e647": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recordIntegrityFailure",
			"line": 266,
			"column": 2,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.runMaintenancePass.747b7cbef0": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 351,
			"column": 3,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.runMaintenancePass.c72575daaa": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 375,
			"column": 4,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.runMaintenancePass.ef7a1e225c": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 392,
			"column": 3,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.runMaintenancePass.90f01cc543": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 404,
			"column": 3,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.runMaintenancePass.3a7c9e73cf": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 417,
			"column": 3,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.runMaintenancePass.11beb09895": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 431,
			"column": 3,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.runMaintenancePass.6a1e15dc18": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 439,
			"column": 2,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.tick.e111b66415": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "tick",
			"line": 497,
			"column": 4,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.tick.6bd3e0102c": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "tick",
			"line": 506,
			"column": 4,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.<anonymous callback>.f90713a2e3": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "<anonymous callback>",
			"line": 536,
			"column": 5,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"maintenance.startMaintenanceTimer.06c1e98584": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "startMaintenanceTimer",
			"line": 555,
			"column": 2,
			"file_hash": "db5b4fb8a9aa33fca9e40726ea915373d9d53551ebf74acb080d8f9c365522d2"
		},
		"memory-store-admin-api.delete.5a8c32b1ed": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "delete",
			"line": 57,
			"column": 3,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.deleteMany.e73022fb31": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "deleteMany",
			"line": 101,
			"column": 3,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.bulkDelete.2631f303e5": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "bulkDelete",
			"line": 167,
			"column": 3,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.<anonymous callback>.130719fdd0": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "<anonymous callback>",
			"line": 263,
			"column": 5,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.closeSqlite.61a563b112": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "closeSqlite",
			"line": 312,
			"column": 4,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-atomic-extraction-ledger-api.reopenAtomicExtractionChunk.e05258e34b": {
			"file": "packages/memory/src/store/memory-store-atomic-extraction-ledger-api.ts",
			"function": "reopenAtomicExtractionChunk",
			"line": 315,
			"column": 4,
			"file_hash": "b43bc6512fd75096a2c9711cd913d46da9b7ce65744917765b6c9828ff929f9d"
		},
		"memory-store-backfill.backfillMissingChunks.7094298b4a": {
			"file": "packages/memory/src/store/memory-store-backfill.ts",
			"function": "backfillMissingChunks",
			"line": 40,
			"column": 6,
			"file_hash": "c246982a9fc8dcd6ef9e198727f7a1cd11655e4c982a96571b9748032fa132cb"
		},
		"memory-store-backfill.<anonymous callback>.c483e84a68": {
			"file": "packages/memory/src/store/memory-store-backfill.ts",
			"function": "<anonymous callback>",
			"line": 110,
			"column": 6,
			"file_hash": "c246982a9fc8dcd6ef9e198727f7a1cd11655e4c982a96571b9748032fa132cb"
		},
		"memory-store-backfill.<anonymous callback>.c4019a929d": {
			"file": "packages/memory/src/store/memory-store-backfill.ts",
			"function": "<anonymous callback>",
			"line": 129,
			"column": 5,
			"file_hash": "c246982a9fc8dcd6ef9e198727f7a1cd11655e4c982a96571b9748032fa132cb"
		},
		"memory-store-base.<anonymous callback>.3dd5e75e4f": {
			"file": "packages/memory/src/store/memory-store-base.ts",
			"function": "<anonymous callback>",
			"line": 970,
			"column": 3,
			"file_hash": "208e450c10bfc850e4c92e6b70d9e1275ff63318d01539ef978b4a8a0f54976d"
		},
		"storage.vector.search.unavailable": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 158,
			"column": 4,
			"file_hash": "360cc1b3155d8782673002cc57b2d42071fc97247ef5698f51552b9bb419aab0"
		},
		"memory-store-chunk-search.searchChunksSemantic.7d889feb61": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 209,
			"column": 6,
			"file_hash": "360cc1b3155d8782673002cc57b2d42071fc97247ef5698f51552b9bb419aab0"
		},
		"memory-store-chunk-search.searchChunksSemantic.fa074292e0": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 233,
			"column": 4,
			"file_hash": "360cc1b3155d8782673002cc57b2d42071fc97247ef5698f51552b9bb419aab0"
		},
		"memory-store-chunk-search.searchChunksKeyword.26628a27c1": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksKeyword",
			"line": 341,
			"column": 4,
			"file_hash": "360cc1b3155d8782673002cc57b2d42071fc97247ef5698f51552b9bb419aab0"
		},
		"memory-store-chunk-search.searchChunksKeyword.36ca2cc1d7": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksKeyword",
			"line": 354,
			"column": 4,
			"file_hash": "360cc1b3155d8782673002cc57b2d42071fc97247ef5698f51552b9bb419aab0"
		},
		"memory-store-persistence-api.store.8fd6a993e7": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 116,
			"column": 3,
			"file_hash": "979247cd1f0484226bed6c45b724814a3835b8338e699f0331fc723174e00e0c"
		},
		"memory-store-persistence-api.store.2f479e68bf": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 193,
			"column": 5,
			"file_hash": "979247cd1f0484226bed6c45b724814a3835b8338e699f0331fc723174e00e0c"
		},
		"memory-store-persistence-api.store.14bfc8e321": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 211,
			"column": 4,
			"file_hash": "979247cd1f0484226bed6c45b724814a3835b8338e699f0331fc723174e00e0c"
		},
		"memory-store-persistence-api.<anonymous callback>.b07cd1be28": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "<anonymous callback>",
			"line": 233,
			"column": 6,
			"file_hash": "979247cd1f0484226bed6c45b724814a3835b8338e699f0331fc723174e00e0c"
		},
		"memory-store-persistence-api.<anonymous callback>.087a18a049": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "<anonymous callback>",
			"line": 247,
			"column": 5,
			"file_hash": "979247cd1f0484226bed6c45b724814a3835b8338e699f0331fc723174e00e0c"
		},
		"memory-store-persistence-api.supersede.77de7ddab1": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "supersede",
			"line": 765,
			"column": 3,
			"file_hash": "979247cd1f0484226bed6c45b724814a3835b8338e699f0331fc723174e00e0c"
		},
		"memory-store-read-api.getMemoryMetadata.35e63c5534": {
			"file": "packages/memory/src/store/memory-store-read-api.ts",
			"function": "getMemoryMetadata",
			"line": 190,
			"column": 4,
			"file_hash": "8d4e8ffa32b180ea4829cdc611bef9b8d34c142dc535e8e6e810f0718110f96d"
		},
		"memory-store-rem-api.applyRemTextVersion.6422a9ebd1": {
			"file": "packages/memory/src/store/memory-store-rem-api.ts",
			"function": "applyRemTextVersion",
			"line": 83,
			"column": 5,
			"file_hash": "a488e86d43b4fd2b6102c0270ef53b3ee557f1e7b65fce95576116cda9f4bf1e"
		},
		"memory-store-rem-api.applyTransaction.47fe85179a": {
			"file": "packages/memory/src/store/memory-store-rem-api.ts",
			"function": "applyTransaction",
			"line": 204,
			"column": 3,
			"file_hash": "a488e86d43b4fd2b6102c0270ef53b3ee557f1e7b65fce95576116cda9f4bf1e"
		},
		"memory-store-search-api.searchSemantic.a8cee42447": {
			"file": "packages/memory/src/store/memory-store-search-api.ts",
			"function": "searchSemantic",
			"line": 268,
			"column": 3,
			"file_hash": "892971bc9b006571ae1ad62ee30ca8b945818246084477fc2f97dc2fa275dd9a"
		},
		"memory-store-search-api.searchKeyword.f4293a3f14": {
			"file": "packages/memory/src/store/memory-store-search-api.ts",
			"function": "searchKeyword",
			"line": 322,
			"column": 3,
			"file_hash": "892971bc9b006571ae1ad62ee30ca8b945818246084477fc2f97dc2fa275dd9a"
		},
		"memory-store-search-api.attachSnippets.896a3e960a": {
			"file": "packages/memory/src/store/memory-store-search-api.ts",
			"function": "attachSnippets",
			"line": 375,
			"column": 5,
			"file_hash": "892971bc9b006571ae1ad62ee30ca8b945818246084477fc2f97dc2fa275dd9a"
		},
		"memory-store-update-api.update.31162cf4e4": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "update",
			"line": 184,
			"column": 3,
			"file_hash": "0c2b4175052874929e98379f53c0744bef62a9e74d96992f0f5880ad13a253be"
		},
		"memory-store-update-api.updateTier.feb5a5165b": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "updateTier",
			"line": 452,
			"column": 3,
			"file_hash": "0c2b4175052874929e98379f53c0744bef62a9e74d96992f0f5880ad13a253be"
		},
		"memory-store-update-api.updateMetadata.6e33353e47": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "updateMetadata",
			"line": 480,
			"column": 3,
			"file_hash": "0c2b4175052874929e98379f53c0744bef62a9e74d96992f0f5880ad13a253be"
		},
		"memory-store-update-api.resolveReflectionItem.f1d6aa0eab": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "resolveReflectionItem",
			"line": 510,
			"column": 3,
			"file_hash": "0c2b4175052874929e98379f53c0744bef62a9e74d96992f0f5880ad13a253be"
		},
		"memory-store-update-api.applyMetadataDeltas.49983b35b4": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "applyMetadataDeltas",
			"line": 561,
			"column": 3,
			"file_hash": "0c2b4175052874929e98379f53c0744bef62a9e74d96992f0f5880ad13a253be"
		},
		"memory-store-update-api.applyMetadataDelta.6961c06549": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "applyMetadataDelta",
			"line": 598,
			"column": 3,
			"file_hash": "0c2b4175052874929e98379f53c0744bef62a9e74d96992f0f5880ad13a253be"
		},
		"memory-store-write-validation.shapeAlarm.3383666e9c": {
			"file": "packages/memory/src/store/memory-store-write-validation.ts",
			"function": "shapeAlarm",
			"line": 110,
			"column": 2,
			"file_hash": "ca90c6b0300952883746aeb7dbb2898f0fd2473c547083175750629e2c969ba7"
		},
		"rem-sqlite-adapter.mutateAttempt.4c4b5764ca": {
			"file": "packages/memory/src/store/rem-sqlite-adapter.ts",
			"function": "mutateAttempt",
			"line": 478,
			"column": 6,
			"file_hash": "93b57fc9ea349bc694dc82d22625f081dfcd620338b145a6211c8037b1eada82"
		}
	}
};
