// Generated by scripts/build-log-catalog.ts.
import type { LogSiteCatalog } from "@snoai/utils";
export const logSiteCatalog: LogSiteCatalog = {
	"build_id": "bece2a49abd90cd7668cb8651021b9d2bc74660002f53ce2f5054ebba749717c",
	"sites": {
		"plugin-config-schema.normalizeProductMode.834ccfc110": {
			"file": "packages/sno-station-mem/src/contract/config/plugin-config-schema.ts",
			"function": "normalizeProductMode",
			"line": 116,
			"column": 3,
			"file_hash": "04e0ad5e0ee9c2fa37eb516232f68715788ecd504d3705515e59c0e4607895ad"
		},
		"memory.recall.budget.checked": {
			"file": "packages/sno-station-mem/src/engine/bindings/memory-recall-tool.ts",
			"function": "execute",
			"line": 363,
			"column": 6,
			"file_hash": "04f7758e607dec3c55f669b82e9762e79848948721268c08319b4ac84c9f6ae5"
		},
		"memory.recall.completed": {
			"file": "packages/sno-station-mem/src/engine/bindings/memory-recall-tool.ts",
			"function": "execute",
			"line": 417,
			"column": 5,
			"file_hash": "04f7758e607dec3c55f669b82e9762e79848948721268c08319b4ac84c9f6ae5"
		},
		"memory.capture.local.write.failed": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "runLocalFirstCapture",
			"line": 101,
			"column": 4,
			"file_hash": "6a6e8dc65a80ca056b9714e152bc847c9e5a24e281abceb7bd38338426766417"
		},
		"memory.capture.local.completed": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "runLocalFirstCapture",
			"line": 110,
			"column": 2,
			"file_hash": "6a6e8dc65a80ca056b9714e152bc847c9e5a24e281abceb7bd38338426766417"
		},
		"memory.capture.hook.failed": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "onAgentEnd",
			"line": 244,
			"column": 3,
			"file_hash": "6a6e8dc65a80ca056b9714e152bc847c9e5a24e281abceb7bd38338426766417"
		},
		"memory.capture.hook.completed": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "onAgentEnd",
			"line": 254,
			"column": 3,
			"file_hash": "6a6e8dc65a80ca056b9714e152bc847c9e5a24e281abceb7bd38338426766417"
		},
		"memory.auto_recall.query.limited": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 157,
			"column": 3,
			"file_hash": "f62c91d86d7064e9d06e006458cbde5dfd5631567ce59448105eb6496e57777c"
		},
		"memory.auto_recall.failed": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 317,
			"column": 4,
			"file_hash": "f62c91d86d7064e9d06e006458cbde5dfd5631567ce59448105eb6496e57777c"
		},
		"memory.auto_recall.completed": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 326,
			"column": 3,
			"file_hash": "f62c91d86d7064e9d06e006458cbde5dfd5631567ce59448105eb6496e57777c"
		},
		"memory.auto_recall.telemetry.skipped": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "recordAutoRecallUsage",
			"line": 348,
			"column": 4,
			"file_hash": "f62c91d86d7064e9d06e006458cbde5dfd5631567ce59448105eb6496e57777c"
		},
		"memory.auto_recall.telemetry.failed": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "recordAutoRecallUsage",
			"line": 379,
			"column": 4,
			"file_hash": "f62c91d86d7064e9d06e006458cbde5dfd5631567ce59448105eb6496e57777c"
		},
		"plugin.openclaw-insight-distill-factory.buildInsightDistiller.8b084be5ca": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 54,
			"column": 3,
			"file_hash": "87ca4a4752a4cd1e593c5d282de60f4bb5e9cd3becc5f98f86349056744dc38a"
		},
		"plugin.openclaw-insight-distill-factory.buildInsightDistiller.6cdc733c64": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 61,
			"column": 3,
			"file_hash": "87ca4a4752a4cd1e593c5d282de60f4bb5e9cd3becc5f98f86349056744dc38a"
		},
		"openclaw-insight-distill-factory.buildInsightDistiller.847c5ab779": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 65,
			"column": 3,
			"file_hash": "87ca4a4752a4cd1e593c5d282de60f4bb5e9cd3becc5f98f86349056744dc38a"
		},
		"plugin.openclaw-insight-distill-factory.buildInsightDistiller.888f96bfef": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 117,
			"column": 3,
			"file_hash": "87ca4a4752a4cd1e593c5d282de60f4bb5e9cd3becc5f98f86349056744dc38a"
		},
		"plugin.openclaw-runtime-mode.runObserveLifecycleTask.d1856ccb13": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-runtime-mode.ts",
			"function": "runObserveLifecycleTask",
			"line": 59,
			"column": 6,
			"file_hash": "e6564e39a9e80dc47f2f3d4da0ac573a33b39fd36427f25a2a459caa0b7b1e99"
		},
		"plugin.openclaw-runtime-mode.auditMissingHookAgentIdentity.f06795892a": {
			"file": "packages/sno-station-mem/src/engine/bindings/sno-station-mem-runtime-mode.ts",
			"function": "auditMissingHookAgentIdentity",
			"line": 127,
			"column": 2,
			"file_hash": "e6564e39a9e80dc47f2f3d4da0ac573a33b39fd36427f25a2a459caa0b7b1e99"
		},
		"memdump.main.failed": {
			"file": "packages/sno-station-mem/src/engine/diagnostics/memdump.ts",
			"function": "<module>",
			"line": 316,
			"column": 3,
			"file_hash": "a0752e075f695b673315c81f9d8b7d9097192303d3e44ff9c10ac3a2bc83b639"
		},
		"trace.appendQaTrace.164bcaddd4": {
			"file": "packages/sno-station-mem/src/engine/eval/trace.ts",
			"function": "appendQaTrace",
			"line": 141,
			"column": 3,
			"file_hash": "2d8c3df32d69fe98cba57761d86e5d5b72685475fd7af2649514b0e254d1e83d"
		},
		"trace.writeConfigSnapshot.completed": {
			"file": "packages/sno-station-mem/src/engine/eval/trace.ts",
			"function": "writeConfigSnapshot",
			"line": 225,
			"column": 4,
			"file_hash": "2d8c3df32d69fe98cba57761d86e5d5b72685475fd7af2649514b0e254d1e83d"
		},
		"extraction.atomic-extraction-gauntlet.runAtomicExtractionGauntlet.365701f979": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-extraction-gauntlet.ts",
			"function": "runAtomicExtractionGauntlet",
			"line": 216,
			"column": 3,
			"file_hash": "c635e7535561cd4b6b1b82737f8a8d739e22e304feef47494f09ed8a5385a370"
		},
		"extraction.atomic-extraction-reply.projectRecord.327508ac5f": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 138,
			"column": 3,
			"file_hash": "6edf819b72c3c542722e97046ad958d65cbfc90ef9872f9c3559955364c16edc"
		},
		"extraction.atomic-extraction-reply.projectRecord.aac5440fc2": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 145,
			"column": 3,
			"file_hash": "6edf819b72c3c542722e97046ad958d65cbfc90ef9872f9c3559955364c16edc"
		},
		"extraction.atomic-extraction-reply.projectRecord.b92c90f285": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 152,
			"column": 3,
			"file_hash": "6edf819b72c3c542722e97046ad958d65cbfc90ef9872f9c3559955364c16edc"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.7456414b06": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 301,
			"column": 3,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.a373dfa454": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 309,
			"column": 3,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.dc917b09a1": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 324,
			"column": 3,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.5264647de8": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 333,
			"column": 3,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.5f797c1175": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 390,
			"column": 3,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.fdcb677e24": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 392,
			"column": 3,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-generic-extractor.runAtomicGenericExtractionPass.cce4a719a3": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicGenericExtractionPass",
			"line": 509,
			"column": 4,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-generic-extractor.runAtomicGenericExtractionPass.98a701bd95": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicGenericExtractionPass",
			"line": 535,
			"column": 3,
			"file_hash": "3812e1dca6003cfb5a5500e2d8b0c948dcc8d85ae2d487103bf6adec6ec07ed1"
		},
		"extraction.atomic-memory-extraction.extractAndPersist.7e1c9d2660": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "extractAndPersist",
			"line": 639,
			"column": 4,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"memory.capture.completed": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "extractAndPersist",
			"line": 789,
			"column": 4,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"extraction.atomic-memory-extraction.readStandingSubjectCandidates.b88c6fb3aa": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "readStandingSubjectCandidates",
			"line": 927,
			"column": 5,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"extraction.atomic-memory-extraction.reaskStandingSubjects.1288498dec": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "reaskStandingSubjects",
			"line": 1178,
			"column": 4,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"extraction.atomic-memory-extraction.reaskStandingSubjects.2b8785b171": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "reaskStandingSubjects",
			"line": 1187,
			"column": 2,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"extraction.atomic-memory-extraction.runAtomicMemoryExtraction.304a5a8d5c": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1434,
			"column": 3,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"extraction.atomic-memory-extraction.runAtomicMemoryExtraction.0d9673d494": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1565,
			"column": 4,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"memory.extraction.window.completed": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1583,
			"column": 3,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"extraction.atomic-memory-extraction.judgeRetirementBatch.64b641b407": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "judgeRetirementBatch",
			"line": 1626,
			"column": 4,
			"file_hash": "d747691c5cb09320f982443b90d75df306dbd8d3f7a0906e87fb4b49da88b0a4"
		},
		"extraction.atomic-subject-guard.runAtomicSubjectGuard.037dc017c1": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-subject-guard.ts",
			"function": "runAtomicSubjectGuard",
			"line": 275,
			"column": 3,
			"file_hash": "7616ee96632c7086f336dce7317ac54c673b973771d382162d6165758c4a2cee"
		},
		"extraction.atomic-subject-guard.runAtomicSubjectGuard.7fbb9c4f6d": {
			"file": "packages/sno-station-mem/src/engine/extraction/atomic-subject-guard.ts",
			"function": "runAtomicSubjectGuard",
			"line": 294,
			"column": 3,
			"file_hash": "7616ee96632c7086f336dce7317ac54c673b973771d382162d6165758c4a2cee"
		},
		"b-profile-section-dictionary-provider.restoreCachedSectionDictionary.a4518aedd5": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "restoreCachedSectionDictionary",
			"line": 252,
			"column": 3,
			"file_hash": "dd246c3b98eaddf8eaac0b85d7e51cd83f74007dbef45710e473e26ec18e8adb"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.ac5ddcab10": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 292,
			"column": 3,
			"file_hash": "dd246c3b98eaddf8eaac0b85d7e51cd83f74007dbef45710e473e26ec18e8adb"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.a8ecb1a4f2": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 322,
			"column": 3,
			"file_hash": "dd246c3b98eaddf8eaac0b85d7e51cd83f74007dbef45710e473e26ec18e8adb"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.15ee874f33": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 345,
			"column": 3,
			"file_hash": "dd246c3b98eaddf8eaac0b85d7e51cd83f74007dbef45710e473e26ec18e8adb"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.b452a7657e": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 93,
			"column": 3,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.4494531e35": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 115,
			"column": 3,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.5276d7dfea": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 124,
			"column": 4,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.1acb6c65f8": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 140,
			"column": 3,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.d8bb76de51": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 149,
			"column": 4,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.ce06a215a3": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 174,
			"column": 2,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.<anonymous callback>.9cc8218e54": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "<anonymous callback>",
			"line": 195,
			"column": 3,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.assertPlanReconciles.03748b5c20": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "assertPlanReconciles",
			"line": 877,
			"column": 2,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.assertCanonicalPlanReconciles.2ad72089d1": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "assertCanonicalPlanReconciles",
			"line": 889,
			"column": 2,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"b-profile-section-rekey.throwReconciliationError.b59b599311": {
			"file": "packages/sno-station-mem/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "throwReconciliationError",
			"line": 899,
			"column": 2,
			"file_hash": "b285b282d931efebcc3ebbbb4dc8050e8d130d38392cf9f58279d04de199b64b"
		},
		"date-resolution.resolveMemoryDate.1224fa35b2": {
			"file": "packages/sno-station-mem/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 558,
			"column": 3,
			"file_hash": "c03bad8697545b9c40e252f3b2881fd14e302e37687f304d92daba3468a9deab"
		},
		"date-resolution.resolveMemoryDate.f9d5985547": {
			"file": "packages/sno-station-mem/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 604,
			"column": 5,
			"file_hash": "c03bad8697545b9c40e252f3b2881fd14e302e37687f304d92daba3468a9deab"
		},
		"date-resolution.resolveMemoryDate.c2334f61f6": {
			"file": "packages/sno-station-mem/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 614,
			"column": 5,
			"file_hash": "c03bad8697545b9c40e252f3b2881fd14e302e37687f304d92daba3468a9deab"
		},
		"date-resolution.resolveMemoryDate.5e94847eb6": {
			"file": "packages/sno-station-mem/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 634,
			"column": 2,
			"file_hash": "c03bad8697545b9c40e252f3b2881fd14e302e37687f304d92daba3468a9deab"
		},
		"embedding-provider-client.<anonymous callback>.3c8d5ee192": {
			"file": "packages/sno-station-mem/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 75,
			"column": 3,
			"file_hash": "824c4631edc058051e0e8d3e2600f3b8485a0c2cdf45a3e3ef7de88071b3c840"
		},
		"embedding-provider-client.embed.ab60111378": {
			"file": "packages/sno-station-mem/src/engine/extraction/embedding-provider-client.ts",
			"function": "embed",
			"line": 159,
			"column": 3,
			"file_hash": "824c4631edc058051e0e8d3e2600f3b8485a0c2cdf45a3e3ef7de88071b3c840"
		},
		"embedding-provider-client.embedDirect.c6998ac2fb": {
			"file": "packages/sno-station-mem/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedDirect",
			"line": 192,
			"column": 4,
			"file_hash": "824c4631edc058051e0e8d3e2600f3b8485a0c2cdf45a3e3ef7de88071b3c840"
		},
		"embedding-provider-client.embedMany.8ffe2fb365": {
			"file": "packages/sno-station-mem/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedMany",
			"line": 210,
			"column": 3,
			"file_hash": "824c4631edc058051e0e8d3e2600f3b8485a0c2cdf45a3e3ef7de88071b3c840"
		},
		"embedding-provider-client.embedMany.71b35eadaf": {
			"file": "packages/sno-station-mem/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedMany",
			"line": 229,
			"column": 4,
			"file_hash": "824c4631edc058051e0e8d3e2600f3b8485a0c2cdf45a3e3ef7de88071b3c840"
		},
		"embedding-provider-client.<anonymous callback>.32cc9ec43e": {
			"file": "packages/sno-station-mem/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 279,
			"column": 5,
			"file_hash": "824c4631edc058051e0e8d3e2600f3b8485a0c2cdf45a3e3ef7de88071b3c840"
		},
		"embedding-provider-client.<anonymous callback>.d7a3f8337c": {
			"file": "packages/sno-station-mem/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 286,
			"column": 5,
			"file_hash": "824c4631edc058051e0e8d3e2600f3b8485a0c2cdf45a3e3ef7de88071b3c840"
		},
		"insight-distill-write-actions.sessionTimestampField.29d4b22da7": {
			"file": "packages/sno-station-mem/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "sessionTimestampField",
			"line": 414,
			"column": 3,
			"file_hash": "f220349e45819699b73901fa9827eefbb27fb6a16e089ef8b16e1d220342f172"
		},
		"insight-distill-write-actions.storeCandidate.138415ce64": {
			"file": "packages/sno-station-mem/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "storeCandidate",
			"line": 505,
			"column": 3,
			"file_hash": "f220349e45819699b73901fa9827eefbb27fb6a16e089ef8b16e1d220342f172"
		},
		"insight-distill-write-actions.storeCandidate.6754f6ee4b": {
			"file": "packages/sno-station-mem/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "storeCandidate",
			"line": 516,
			"column": 3,
			"file_hash": "f220349e45819699b73901fa9827eefbb27fb6a16e089ef8b16e1d220342f172"
		},
		"insight-distill-write-actions.handleSupport.c98c47eeb9": {
			"file": "packages/sno-station-mem/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleSupport",
			"line": 552,
			"column": 2,
			"file_hash": "f220349e45819699b73901fa9827eefbb27fb6a16e089ef8b16e1d220342f172"
		},
		"insight-distill-write-actions.handleContextualize.bd66df2159": {
			"file": "packages/sno-station-mem/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleContextualize",
			"line": 612,
			"column": 2,
			"file_hash": "f220349e45819699b73901fa9827eefbb27fb6a16e089ef8b16e1d220342f172"
		},
		"insight-distill-write-actions.handleContradict.c6164031da": {
			"file": "packages/sno-station-mem/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleContradict",
			"line": 689,
			"column": 2,
			"file_hash": "f220349e45819699b73901fa9827eefbb27fb6a16e089ef8b16e1d220342f172"
		},
		"profile-section-writer.deferLifecycleRetirement.f94b354ff4": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "deferLifecycleRetirement",
			"line": 372,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"memory.profile.task.completed": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 510,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"memory.profile.section.completed": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 540,
			"column": 2,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"memory.profile.failed": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 551,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.28936dcd3c": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 721,
			"column": 4,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.e3afdfb6d8": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 793,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.80241da6d8": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 848,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.recheckProfileRetirements.613c569527": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "recheckProfileRetirements",
			"line": 1022,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.mergeProfileSection.c707285ef3": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "mergeProfileSection",
			"line": 1129,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.writeEpisodicSafetyNet.ae69446388": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "writeEpisodicSafetyNet",
			"line": 1425,
			"column": 2,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.capRetireByNameWorkItems.3c47653418": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "capRetireByNameWorkItems",
			"line": 1663,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.writeProfileRow.3e3e26a255": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "writeProfileRow",
			"line": 1701,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.planProfileConflicts.e5bcea94ce": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2109,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.planProfileConflicts.97b6a2e824": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2175,
			"column": 5,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.planProfileConflicts.b4962bc7f0": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2195,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.logProfileConflictFenceRejection.b0669b40b3": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "logProfileConflictFenceRejection",
			"line": 2219,
			"column": 2,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"profile-section-writer.adjudicateSafely.d3f7ab0ac5": {
			"file": "packages/sno-station-mem/src/engine/extraction/profile-section-writer.ts",
			"function": "adjudicateSafely",
			"line": 2266,
			"column": 3,
			"file_hash": "9137ea6a8727e4c01e8bcb408a4ba29e893a8de7ab3faf1e693d4e063dc6224e"
		},
		"language.detector.unavailable": {
			"file": "packages/sno-station-mem/src/engine/i18n/detector.ts",
			"function": "markDetectorBroken",
			"line": 29,
			"column": 2,
			"file_hash": "8e2684d21cff346fe7fee29f2e16dba3f160a9c6a4064a1042e4a9c3b7851096"
		},
		"registry.loadLocale.aad78d489e": {
			"file": "packages/sno-station-mem/src/engine/i18n/registry.ts",
			"function": "loadLocale",
			"line": 58,
			"column": 3,
			"file_hash": "8c0b60cdfd3adb61659aefe98068c0ccfa6f9f34a28a728d5ded5ae7e5612e8f"
		},
		"observability.emit.failed": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "PluginObservability.tryEmit",
			"line": 163,
			"column": 4,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"adapter.<anonymous callback>.82f49c57a7": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 187,
			"column": 7,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"observability.background.paused": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "PluginObservability.registerOrphanedTask",
			"line": 221,
			"column": 4,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"observability.background.queue_full": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "PluginObservability.trackBestEffort",
			"line": 260,
			"column": 4,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"observability.background.cooldown": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "PluginObservability.trackBestEffort",
			"line": 271,
			"column": 4,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"observability.background.orphan_limit": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "PluginObservability.trackBestEffort",
			"line": 282,
			"column": 4,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"observability.background.timed_out": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "PluginObservability.runBackgroundTask",
			"line": 331,
			"column": 7,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"adapter.<anonymous callback>.f036514cb8": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 376,
			"column": 9,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"adapter.<anonymous callback>.9aedc01548": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 415,
			"column": 9,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"adapter.<anonymous callback>.52f64c2607": {
			"file": "packages/sno-station-mem/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 459,
			"column": 9,
			"file_hash": "30762e3ba38297add8d17b0d5543dcd2c956bd1b4306af4bdd9fed2eae972ae7"
		},
		"observability.bestEffort.failed": {
			"file": "packages/sno-station-mem/src/engine/observability/best-effort.ts",
			"function": "bestEffort",
			"line": 22,
			"column": 15,
			"file_hash": "82b7a3fa2be5a35b3fd30de697730da947208e3c97f7ad5d1c8fd86ebe13bf52"
		},
		"observability.bestEffortSync.failed": {
			"file": "packages/sno-station-mem/src/engine/observability/best-effort.ts",
			"function": "bestEffortSync",
			"line": 39,
			"column": 15,
			"file_hash": "82b7a3fa2be5a35b3fd30de697730da947208e3c97f7ad5d1c8fd86ebe13bf52"
		},
		"runtime.process.started": {
			"file": "packages/sno-station-mem/src/engine/observability/runtime-diagnostics.ts",
			"function": "emitRuntimeStartSnapshot",
			"line": 77,
			"column": 2,
			"file_hash": "ab05bd0f4263ebd1e0ef126b204471dca01c7c528ff4c891f313613be731a11d"
		},
		"memory.spend.stat.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 39,
			"column": 4,
			"file_hash": "e2eb4a5920c03d8b13c31fb6f80439481ae062ad8e60ba66bc90451ef37713f9"
		},
		"memory.spend.stream.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 103,
			"column": 3,
			"file_hash": "e2eb4a5920c03d8b13c31fb6f80439481ae062ad8e60ba66bc90451ef37713f9"
		},
		"memory.spend.rows.invalid": {
			"file": "packages/sno-station-mem/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 109,
			"column": 26,
			"file_hash": "e2eb4a5920c03d8b13c31fb6f80439481ae062ad8e60ba66bc90451ef37713f9"
		},
		"memory.learning.lock.close.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 102,
			"column": 6,
			"file_hash": "e10fffde88b7f68430f54b9dc2c2d406e385f5d018aa3c6d63db92206ccda13d"
		},
		"memory.learning.lock.cleanup.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 107,
			"column": 6,
			"file_hash": "e10fffde88b7f68430f54b9dc2c2d406e385f5d018aa3c6d63db92206ccda13d"
		},
		"memory.learning.lock.stat.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 121,
			"column": 6,
			"file_hash": "e10fffde88b7f68430f54b9dc2c2d406e385f5d018aa3c6d63db92206ccda13d"
		},
		"memory.learning.lock.stale.cleanup.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 130,
			"column": 6,
			"file_hash": "e10fffde88b7f68430f54b9dc2c2d406e385f5d018aa3c6d63db92206ccda13d"
		},
		"memory.learning.history.read.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/learning-file-maintenance.ts",
			"function": "nextLearningId",
			"line": 152,
			"column": 4,
			"file_hash": "e10fffde88b7f68430f54b9dc2c2d406e385f5d018aa3c6d63db92206ccda13d"
		},
		"memory.learning.ensure.read.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/learning-file-maintenance.ts",
			"function": "ensureLearningFile",
			"line": 172,
			"column": 4,
			"file_hash": "e10fffde88b7f68430f54b9dc2c2d406e385f5d018aa3c6d63db92206ccda13d"
		},
		"memory.learning.append.read.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/learning-file-maintenance.ts",
			"function": "appendSelfImprovementEntry",
			"line": 302,
			"column": 6,
			"file_hash": "e10fffde88b7f68430f54b9dc2c2d406e385f5d018aa3c6d63db92206ccda13d"
		},
		"memory.audit.append.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/runtime-audit-log.ts",
			"function": "enqueueAuditWrite",
			"line": 309,
			"column": 4,
			"file_hash": "0ff1193c7e57c13fcf2b97a29902d3553736be6bc4b658e0c9ed2e46950a67f9"
		},
		"memory.session.file.stat.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/session-summary-storage.ts",
			"function": "sortFileNamesByMtimeDesc",
			"line": 33,
			"column": 6,
			"file_hash": "26017157533f8032867762c085a780ea17376df3f14dfa71e67767ef9cdd41b7"
		},
		"memory.session.read.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionMessages",
			"line": 135,
			"column": 4,
			"file_hash": "26017157533f8032867762c085a780ea17376df3f14dfa71e67767ef9cdd41b7"
		},
		"memory.session.rows.invalid": {
			"file": "packages/sno-station-mem/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionMessages",
			"line": 141,
			"column": 40,
			"file_hash": "26017157533f8032867762c085a780ea17376df3f14dfa71e67767ef9cdd41b7"
		},
		"memory.session.reset.discovery.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionContentWithResetFallback",
			"line": 179,
			"column": 4,
			"file_hash": "26017157533f8032867762c085a780ea17376df3f14dfa71e67767ef9cdd41b7"
		},
		"memory.session.previous.discovery.failed": {
			"file": "packages/sno-station-mem/src/engine/operations/session-summary-storage.ts",
			"function": "findPreviousSessionFile",
			"line": 238,
			"column": 4,
			"file_hash": "26017157533f8032867762c085a780ea17376df3f14dfa71e67767ef9cdd41b7"
		},
		"stale-memory-demotion.runStaleDemotion.e86f004935": {
			"file": "packages/sno-station-mem/src/engine/operations/stale-memory-demotion.ts",
			"function": "runStaleDemotion",
			"line": 96,
			"column": 4,
			"file_hash": "6499dc5053c4f8844944385d702e9f6e5ac5335e5c11e1fcbd0fcd7348f94b07"
		},
		"stale-memory-demotion.runStaleDemotion.d7a77107bb": {
			"file": "packages/sno-station-mem/src/engine/operations/stale-memory-demotion.ts",
			"function": "runStaleDemotion",
			"line": 108,
			"column": 2,
			"file_hash": "6499dc5053c4f8844944385d702e9f6e5ac5335e5c11e1fcbd0fcd7348f94b07"
		},
		"memory.provider.canonical.discovery.degraded": {
			"file": "packages/sno-station-mem/src/engine/provider/canonical-memory-corpus.ts",
			"function": "listCanonicalMemoryFiles",
			"line": 242,
			"column": 40,
			"file_hash": "98864e9d570e5e009e233047974d69c8cb756d7598f7d50d2b087328f9a40f93"
		},
		"memory.provider.manager.resolved": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.getMemorySearchManager",
			"line": 153,
			"column": 5,
			"file_hash": "59bf9a8bf44a0a311a4ae559891747ad04bb08eda8be272e3ae30930978949c9"
		},
		"memory.provider.manager.close.skipped": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeMemorySearchManager",
			"line": 171,
			"column": 5,
			"file_hash": "59bf9a8bf44a0a311a4ae559891747ad04bb08eda8be272e3ae30930978949c9"
		},
		"memory.provider.manager.close.failed": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeMemorySearchManager",
			"line": 189,
			"column": 5,
			"file_hash": "59bf9a8bf44a0a311a4ae559891747ad04bb08eda8be272e3ae30930978949c9"
		},
		"memory.provider.managers.shutdown.completed": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeAllMemorySearchManagers",
			"line": 217,
			"column": 5,
			"file_hash": "59bf9a8bf44a0a311a4ae559891747ad04bb08eda8be272e3ae30930978949c9"
		},
		"memory.provider.search.completed": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-search-manager.ts",
			"function": "MemClawProviderSearchManager.search",
			"line": 199,
			"column": 4,
			"file_hash": "3cdcc506932cb36d59e797ef928f9c74319bbf3d9e8708763db51142ec5adce1"
		},
		"memory.provider.read.completed": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-search-manager.ts",
			"function": "MemClawProviderSearchManager.readFile",
			"line": 258,
			"column": 4,
			"file_hash": "3cdcc506932cb36d59e797ef928f9c74319bbf3d9e8708763db51142ec5adce1"
		},
		"memory.provider.status.completed": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-search-manager.ts",
			"function": "MemClawProviderSearchManager.status",
			"line": 285,
			"column": 3,
			"file_hash": "3cdcc506932cb36d59e797ef928f9c74319bbf3d9e8708763db51142ec5adce1"
		},
		"memory.provider.status.failed": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-search-manager.ts",
			"function": "MemClawProviderSearchManager.status",
			"line": 317,
			"column": 4,
			"file_hash": "3cdcc506932cb36d59e797ef928f9c74319bbf3d9e8708763db51142ec5adce1"
		},
		"memory.provider.manager.closed": {
			"file": "packages/sno-station-mem/src/engine/provider/provider-search-manager.ts",
			"function": "MemClawProviderSearchManager.close",
			"line": 388,
			"column": 3,
			"file_hash": "3cdcc506932cb36d59e797ef928f9c74319bbf3d9e8708763db51142ec5adce1"
		},
		"reflection.daily-log-generator.onRetryLog.b52810f5af": {
			"file": "packages/sno-station-mem/src/engine/reflection/daily-log-generator.ts",
			"function": "onRetryLog",
			"line": 214,
			"column": 25,
			"file_hash": "5683e22cc2d624801e067e1d1cbba47887e3b052c7cdadb7c902c64ba0f6906c"
		},
		"reflection.daily-log-generator.onRetryLog.977c99d43c": {
			"file": "packages/sno-station-mem/src/engine/reflection/daily-log-generator.ts",
			"function": "onRetryLog",
			"line": 215,
			"column": 8,
			"file_hash": "5683e22cc2d624801e067e1d1cbba47887e3b052c7cdadb7c902c64ba0f6906c"
		},
		"reflection.daily-log-generator.generateReflectionText.c0c554e65c": {
			"file": "packages/sno-station-mem/src/engine/reflection/daily-log-generator.ts",
			"function": "generateReflectionText",
			"line": 245,
			"column": 4,
			"file_hash": "5683e22cc2d624801e067e1d1cbba47887e3b052c7cdadb7c902c64ba0f6906c"
		},
		"memory.reflection.command.completed": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-command-hooks.ts",
			"function": "createRunMemoryReflection",
			"line": 118,
			"column": 4,
			"file_hash": "c700ccdb0e9ccf1a3c874ff61cca2e95c61bb237b5ca4d58d7f78e4a3341a7dd"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.be803e8310": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 210,
			"column": 4,
			"file_hash": "c700ccdb0e9ccf1a3c874ff61cca2e95c61bb237b5ca4d58d7f78e4a3341a7dd"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.2a047c8826": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 239,
			"column": 3,
			"file_hash": "c700ccdb0e9ccf1a3c874ff61cca2e95c61bb237b5ca4d58d7f78e4a3341a7dd"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.55c5adf2a5": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 243,
			"column": 3,
			"file_hash": "c700ccdb0e9ccf1a3c874ff61cca2e95c61bb237b5ca4d58d7f78e4a3341a7dd"
		},
		"reflection.reflection-command-hooks.appendGovernanceEntries.805fa046d0": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-command-hooks.ts",
			"function": "appendGovernanceEntries",
			"line": 389,
			"column": 4,
			"file_hash": "c700ccdb0e9ccf1a3c874ff61cca2e95c61bb237b5ca4d58d7f78e4a3341a7dd"
		},
		"reflection.reflection-injection-hooks.registerInheritedRulesHook.43c14eb8b9": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerInheritedRulesHook",
			"line": 164,
			"column": 5,
			"file_hash": "e33c0f0f072d08ef5fd1642e502615919595333a2e84b9757fc2eed4ef95814c"
		},
		"reflection.reflection-injection-hooks.registerDerivedFocusHook.d23bb07c04": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerDerivedFocusHook",
			"line": 186,
			"column": 6,
			"file_hash": "e33c0f0f072d08ef5fd1642e502615919595333a2e84b9757fc2eed4ef95814c"
		},
		"reflection.reflection-injection-hooks.registerDerivedFocusHook.bbe1a0ae1e": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerDerivedFocusHook",
			"line": 222,
			"column": 5,
			"file_hash": "e33c0f0f072d08ef5fd1642e502615919595333a2e84b9757fc2eed4ef95814c"
		},
		"reflection.reflection-injection-hooks.registerV3SliceHook.d23bb07c04": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerV3SliceHook",
			"line": 266,
			"column": 6,
			"file_hash": "e33c0f0f072d08ef5fd1642e502615919595333a2e84b9757fc2eed4ef95814c"
		},
		"reflection.reflection-injection-hooks.registerV3SliceHook.1800747d30": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerV3SliceHook",
			"line": 292,
			"column": 5,
			"file_hash": "e33c0f0f072d08ef5fd1642e502615919595333a2e84b9757fc2eed4ef95814c"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.d4cb1a8408": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 106,
			"column": 3,
			"file_hash": "0a22869c00d19fba98cd195029f16721295c3cb64266eaf22a68cce760f7b3af"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.4f891b1d21": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 110,
			"column": 3,
			"file_hash": "0a22869c00d19fba98cd195029f16721295c3cb64266eaf22a68cce760f7b3af"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.78a7536d17": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 163,
			"column": 6,
			"file_hash": "0a22869c00d19fba98cd195029f16721295c3cb64266eaf22a68cce760f7b3af"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.38fe983443": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 246,
			"column": 4,
			"file_hash": "0a22869c00d19fba98cd195029f16721295c3cb64266eaf22a68cce760f7b3af"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.b692a46de7": {
			"file": "packages/sno-station-mem/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 255,
			"column": 3,
			"file_hash": "0a22869c00d19fba98cd195029f16721295c3cb64266eaf22a68cce760f7b3af"
		},
		"reflection.session-serial-guard.runWithSerialGuard.edb3193695": {
			"file": "packages/sno-station-mem/src/engine/reflection/session-serial-guard.ts",
			"function": "runWithSerialGuard",
			"line": 110,
			"column": 3,
			"file_hash": "8d778721a75a993cf13ce9261ab7424f2bb1f976939daabaa237ad6610ea6470"
		},
		"reflection.session-serial-guard.runWithSerialGuard.2e95bc0994": {
			"file": "packages/sno-station-mem/src/engine/reflection/session-serial-guard.ts",
			"function": "runWithSerialGuard",
			"line": 116,
			"column": 3,
			"file_hash": "8d778721a75a993cf13ce9261ab7424f2bb1f976939daabaa237ad6610ea6470"
		},
		"access-tracker.destroy.5991e0f580": {
			"file": "packages/sno-station-mem/src/engine/retrieval/access-tracker.ts",
			"function": "destroy",
			"line": 320,
			"column": 4,
			"file_hash": "d00bda4a936fe912107f0fda0b8c0ffc6d36aa56cdee59ddeca46fff695d52cf"
		},
		"access-tracker.doFlush.b3bb3939f2": {
			"file": "packages/sno-station-mem/src/engine/retrieval/access-tracker.ts",
			"function": "doFlush",
			"line": 367,
			"column": 6,
			"file_hash": "d00bda4a936fe912107f0fda0b8c0ffc6d36aa56cdee59ddeca46fff695d52cf"
		},
		"access-tracker.doFlush.f82865a307": {
			"file": "packages/sno-station-mem/src/engine/retrieval/access-tracker.ts",
			"function": "doFlush",
			"line": 382,
			"column": 4,
			"file_hash": "d00bda4a936fe912107f0fda0b8c0ffc6d36aa56cdee59ddeca46fff695d52cf"
		},
		"access-tracker.buildAccessDelta.4ac8f20936": {
			"file": "packages/sno-station-mem/src/engine/retrieval/access-tracker.ts",
			"function": "buildAccessDelta",
			"line": 427,
			"column": 5,
			"file_hash": "d00bda4a936fe912107f0fda0b8c0ffc6d36aa56cdee59ddeca46fff695d52cf"
		},
		"query_manifest.capture.written": {
			"file": "packages/sno-station-mem/src/engine/retrieval/query-manifest-capture-cli.ts",
			"function": "main",
			"line": 220,
			"column": 3,
			"file_hash": "3b17e1d61c86c401a11f8330653f8e8d8a9458137ec699ec5473dc2c99ec8c77"
		},
		"query_manifest.capture.failed": {
			"file": "packages/sno-station-mem/src/engine/retrieval/query-manifest-capture-cli.ts",
			"function": "<module>",
			"line": 227,
			"column": 2,
			"file_hash": "3b17e1d61c86c401a11f8330653f8e8d8a9458137ec699ec5473dc2c99ec8c77"
		},
		"memory.retrieval.started": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 40,
			"column": 3,
			"file_hash": "d1e59f0983c4a635818187534b9b225b43d9e9c5b5f6d4604370b83994239929"
		},
		"memory.retrieval.completed": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 172,
			"column": 4,
			"file_hash": "d1e59f0983c4a635818187534b9b225b43d9e9c5b5f6d4604370b83994239929"
		},
		"memory.retrieval.failed": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 184,
			"column": 4,
			"file_hash": "d1e59f0983c4a635818187534b9b225b43d9e9c5b5f6d4604370b83994239929"
		},
		"memory.retrieval.traced.completed": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieveWithTrace",
			"line": 259,
			"column": 4,
			"file_hash": "d1e59f0983c4a635818187534b9b225b43d9e9c5b5f6d4604370b83994239929"
		},
		"memory.retrieval.traced.failed": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieveWithTrace",
			"line": 267,
			"column": 4,
			"file_hash": "d1e59f0983c4a635818187534b9b225b43d9e9c5b5f6d4604370b83994239929"
		},
		"memory.retrieval.tier.failed": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-execution.ts",
			"function": "evaluateTopKTierTransitions",
			"line": 336,
			"column": 5,
			"file_hash": "d1e59f0983c4a635818187534b9b225b43d9e9c5b5f6d4604370b83994239929"
		},
		"retrieval.retriever-rerank.rerank.6fbc6b3a22": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 88,
			"column": 4,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-rerank.runBatch.76d7d1fac6": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 165,
			"column": 6,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-rerank.runBatch.4429b8bd8a": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 181,
			"column": 6,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-rerank.rerank.7847c6248a": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 284,
			"column": 4,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-rerank.rerank.4af9c17c75": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 302,
			"column": 5,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-rerank.rerank.2c5fc67dbf": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 308,
			"column": 5,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-rerank.rerankLightweight.70eb2031f1": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerankLightweight",
			"line": 380,
			"column": 4,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-rerank.rerankLightweight.7e8d0eee29": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerankLightweight",
			"line": 385,
			"column": 3,
			"file_hash": "5c2d12703769e26f186acbac66c5c156915b747c0807b874408a24e42c5b27e9"
		},
		"retrieval.retriever-search-modes.aggregationComplete.5a3b7f9337": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-search-modes.ts",
			"function": "aggregationComplete",
			"line": 71,
			"column": 3,
			"file_hash": "8464808294c66327ccf26940ecba80586ede7ec0966bc98cc37da7c7ab9dae70"
		},
		"retrieval.retriever-search-modes.precisionRecall.97b8770f50": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 245,
			"column": 4,
			"file_hash": "8464808294c66327ccf26940ecba80586ede7ec0966bc98cc37da7c7ab9dae70"
		},
		"retrieval.retriever-search-modes.precisionRecall.c20ade60c4": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 253,
			"column": 4,
			"file_hash": "8464808294c66327ccf26940ecba80586ede7ec0966bc98cc37da7c7ab9dae70"
		},
		"retrieval.retriever-search-modes.precisionRecall.aaf0b2eb17": {
			"file": "packages/sno-station-mem/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 305,
			"column": 3,
			"file_hash": "8464808294c66327ccf26940ecba80586ede7ec0966bc98cc37da7c7ab9dae70"
		},
		"scope-helpers.resolveScopeFilter.0d7f91dae7": {
			"file": "packages/sno-station-mem/src/engine/security/scope-helpers.ts",
			"function": "resolveScopeFilter",
			"line": 54,
			"column": 3,
			"file_hash": "487bea22ee29eb2d672cebc3e2539a2b610cac383e2ca343a96ca76539b2c264"
		},
		"scope-helpers.resolveScopeFilter.720935590d": {
			"file": "packages/sno-station-mem/src/engine/security/scope-helpers.ts",
			"function": "resolveScopeFilter",
			"line": 67,
			"column": 4,
			"file_hash": "487bea22ee29eb2d672cebc3e2539a2b610cac383e2ca343a96ca76539b2c264"
		},
		"scope-identity.isSystemBypassId.1d89371f35": {
			"file": "packages/sno-station-mem/src/engine/security/scope-identity.ts",
			"function": "isSystemBypassId",
			"line": 36,
			"column": 3,
			"file_hash": "c4ff9321ed73720f7c698ee0a0042fefc7c9ebdf11f5c682cc442b9b56f59ac7"
		},
		"memory-telemetry-events.<anonymous callback>.23cfef2d08": {
			"file": "packages/sno-station-mem/src/engine/telemetry/memory-telemetry-events.ts",
			"function": "<anonymous callback>",
			"line": 99,
			"column": 4,
			"file_hash": "4843ab1132d2f846e8151b3cad9ebfce6b3b2294df37a5ca52c3f0ad47496c18"
		},
		"memory.usage.accept.failed": {
			"file": "packages/sno-station-mem/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.tryAcceptUsage",
			"line": 113,
			"column": 4,
			"file_hash": "f7bec01e0048489cf8498cac89ddc91b8a1ed9e2c8064ee4314752a592b1f841"
		},
		"memory.usage.flush.claim_failed": {
			"file": "packages/sno-station-mem/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 147,
			"column": 4,
			"file_hash": "f7bec01e0048489cf8498cac89ddc91b8a1ed9e2c8064ee4314752a592b1f841"
		},
		"memory.usage.flush.empty": {
			"file": "packages/sno-station-mem/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 159,
			"column": 4,
			"file_hash": "f7bec01e0048489cf8498cac89ddc91b8a1ed9e2c8064ee4314752a592b1f841"
		},
		"memory.usage.flush.rollback": {
			"file": "packages/sno-station-mem/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 214,
			"column": 4,
			"file_hash": "f7bec01e0048489cf8498cac89ddc91b8a1ed9e2c8064ee4314752a592b1f841"
		},
		"memory.usage.flush.completed": {
			"file": "packages/sno-station-mem/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 232,
			"column": 3,
			"file_hash": "f7bec01e0048489cf8498cac89ddc91b8a1ed9e2c8064ee4314752a592b1f841"
		},
		"shared.llm-client.resolveRequestTransport.8f631601af": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "resolveRequestTransport",
			"line": 357,
			"column": 4,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"shared.llm-client.resolveRequestTransport.ffa933b519": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "resolveRequestTransport",
			"line": 363,
			"column": 4,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.host.request.completed": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 408,
			"column": 6,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.client.host_cancelled": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 426,
			"column": 5,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.client.host_error": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 435,
			"column": 5,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"shared.llm-client.requestContent.ff17976562": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 475,
			"column": 5,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.client.raw_pipeline_failed": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 498,
			"column": 5,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.client.chat_pipeline_failed": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 526,
			"column": 4,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.client.empty_reply": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 539,
			"column": 4,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"shared.llm-client.requestContentRetryingEmpty.cd874fefff": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "requestContentRetryingEmpty",
			"line": 564,
			"column": 4,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.client.json.deadline_exhausted": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 586,
			"column": 7,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"shared.llm-client.completeJson.e04c8e7e82": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 601,
			"column": 5,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.client.json.request_failed": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 606,
			"column": 5,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"shared.llm-client.completeText.ffa933b519": {
			"file": "packages/sno-station-mem/src/model/llm-client.ts",
			"function": "completeText",
			"line": 625,
			"column": 5,
			"file_hash": "ded5290cfd2e93b49dc848b0e4dcb702399a459b0620ced287f2dca26148eee7"
		},
		"llm.transport.request.completed": {
			"file": "packages/sno-station-mem/src/model/llm-provider-transport.ts",
			"function": "observeRequest",
			"line": 57,
			"column": 4,
			"file_hash": "8b30365792d76b61e37e67b94130163eeafd247fe1a70766b3be7d3449e438af"
		},
		"sidecar.main.startup.failed": {
			"file": "packages/sno-station-mem/src/sidecar/main.ts",
			"function": "<module>",
			"line": 22,
			"column": 2,
			"file_hash": "ce28c62c19966bc690e30943fcae0432a630b1c5fa20e49e219c572a1d413dc2"
		},
		"rem-batch-executor.onStageError.d5f24d50d3": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "onStageError",
			"line": 382,
			"column": 6,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.runRemBatchJobUnlocked.55c52b91cf": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runRemBatchJobUnlocked",
			"line": 516,
			"column": 5,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"sidecar.batch.completed": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runRemBatchJobUnlocked",
			"line": 587,
			"column": 4,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.openBatchRuntime.86fa720e8f": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "openBatchRuntime",
			"line": 663,
			"column": 3,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.onProviderResponse.df4f2d4fa1": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "onProviderResponse",
			"line": 691,
			"column": 5,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.runUpdate.dbf2a836db": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 953,
			"column": 3,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.runUpdate.7dfc387204": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 1026,
			"column": 4,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.runUpdate.7ffc737c24": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 1068,
			"column": 4,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.runReplace.e1e35e40e9": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2380,
			"column": 3,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.runReplace.de3a5f3ce3": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2578,
			"column": 4,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.runReplace.e4be8cfe8f": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2820,
			"column": 4,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.buildRemReplaceCandidateQueue.25aa1a67a6": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "buildRemReplaceCandidateQueue",
			"line": 3123,
			"column": 3,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-batch-executor.reserveReplaceStage.4e67e45fd5": {
			"file": "packages/sno-station-mem/src/sidecar/rem-batch-executor.ts",
			"function": "reserveReplaceStage",
			"line": 3566,
			"column": 2,
			"file_hash": "425ae0fcb4d4522e477507259553065a61ae6846ce1e06cf0a947ab2efa7dc75"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.1d59077a5c": {
			"file": "packages/sno-station-mem/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 161,
			"column": 4,
			"file_hash": "c354b772636db9da4eedb15b264fc6e8b70bbd5822d0daf9d534a6831d4a8096"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.ebe1cdd204": {
			"file": "packages/sno-station-mem/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 173,
			"column": 5,
			"file_hash": "c354b772636db9da4eedb15b264fc6e8b70bbd5822d0daf9d534a6831d4a8096"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.46669e66ff": {
			"file": "packages/sno-station-mem/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 183,
			"column": 5,
			"file_hash": "c354b772636db9da4eedb15b264fc6e8b70bbd5822d0daf9d534a6831d4a8096"
		},
		"sidecar.trigger.dispatch.accepted": {
			"file": "packages/sno-station-mem/src/sidecar/rem-trigger.ts",
			"function": "dispatchRemWave",
			"line": 308,
			"column": 3,
			"file_hash": "c354b772636db9da4eedb15b264fc6e8b70bbd5822d0daf9d534a6831d4a8096"
		},
		"sidecar.trigger.audit_read.failed": {
			"file": "packages/sno-station-mem/src/sidecar/rem-trigger.ts",
			"function": "applyCompletedBaselines",
			"line": 327,
			"column": 3,
			"file_hash": "c354b772636db9da4eedb15b264fc6e8b70bbd5822d0daf9d534a6831d4a8096"
		},
		"sidecar.trigger.audit_records.skipped": {
			"file": "packages/sno-station-mem/src/sidecar/rem-trigger.ts",
			"function": "applyCompletedBaselines",
			"line": 407,
			"column": 3,
			"file_hash": "c354b772636db9da4eedb15b264fc6e8b70bbd5822d0daf9d534a6831d4a8096"
		},
		"server.<anonymous callback>.5eb5a60e6b": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "<anonymous callback>",
			"line": 123,
			"column": 3,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.<anonymous callback>.47c4662916": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "recordRequest",
			"line": 157,
			"column": 4,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.<anonymous callback>.a7a2656a08": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "<anonymous callback>",
			"line": 189,
			"column": 6,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.startLockedRemSidecar.96a92b085b": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "startLockedRemSidecar",
			"line": 219,
			"column": 2,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"sidecar.shutdown.completed": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "startLockedRemSidecar.stop",
			"line": 244,
			"column": 5,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.routeRequest.0ea180a77c": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "routeRequest",
			"line": 314,
			"column": 3,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.runChassisJob.e7639bd8fc": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "runChassisJob",
			"line": 521,
			"column": 6,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"sidecar.job.completed": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "runChassisJob",
			"line": 546,
			"column": 4,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.persistCompletedJob.bc6b30658e": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "persistCompletedJob",
			"line": 578,
			"column": 4,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.persistCompletedJob.a959322a6a": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "persistCompletedJob",
			"line": 597,
			"column": 4,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.persistCompletedJob.8dde75d5b4": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "persistCompletedJob",
			"line": 617,
			"column": 2,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.failNonTerminalJob.cf84e07c6d": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "failNonTerminalJob",
			"line": 692,
			"column": 3,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"server.recoverInterruptedJobs.15309ea841": {
			"file": "packages/sno-station-mem/src/sidecar/server.ts",
			"function": "recoverInterruptedJobs",
			"line": 717,
			"column": 4,
			"file_hash": "2b79139ef4cf4c5dfbd2b9fadafe46b7178c4ccd4da387670c24b15b55ca6617"
		},
		"active-task-carrier-backfill.backfillActiveTaskCarriers.facdae917f": {
			"file": "packages/sno-station-mem/src/store/active-task-carrier-backfill.ts",
			"function": "backfillActiveTaskCarriers",
			"line": 191,
			"column": 2,
			"file_hash": "912a5febe337314519a3cab7454c674464660afc4ea6c6e944aa3726a381c607"
		},
		"active-task-carrier-backfill.<anonymous callback>.0bf95b1f61": {
			"file": "packages/sno-station-mem/src/store/active-task-carrier-backfill.ts",
			"function": "<anonymous callback>",
			"line": 214,
			"column": 3,
			"file_hash": "912a5febe337314519a3cab7454c674464660afc4ea6c6e944aa3726a381c607"
		},
		"backup.pruneOldBackups.1dca69b51b": {
			"file": "packages/sno-station-mem/src/store/backup.ts",
			"function": "pruneOldBackups",
			"line": 78,
			"column": 3,
			"file_hash": "928f059364c11e2d1bfb2ec84d832bd390e37928ac49d37b6048fffb82925ee4"
		},
		"backup.runBackup.ca114973f1": {
			"file": "packages/sno-station-mem/src/store/backup.ts",
			"function": "runBackup",
			"line": 122,
			"column": 2,
			"file_hash": "928f059364c11e2d1bfb2ec84d832bd390e37928ac49d37b6048fffb82925ee4"
		},
		"connection.ensureFtsHealthy.ad5a3ffcd6": {
			"file": "packages/sno-station-mem/src/store/connection.ts",
			"function": "ensureFtsHealthy",
			"line": 214,
			"column": 3,
			"file_hash": "957ecf6245bb540e568abf6e29911b3998623ee65a96b7661399cbb6d458c383"
		},
		"connection.loadSimpleTokenizer.778ee7da6c": {
			"file": "packages/sno-station-mem/src/store/connection.ts",
			"function": "loadSimpleTokenizer",
			"line": 244,
			"column": 2,
			"file_hash": "957ecf6245bb540e568abf6e29911b3998623ee65a96b7661399cbb6d458c383"
		},
		"connection.initDb.ee37a0a971": {
			"file": "packages/sno-station-mem/src/store/connection.ts",
			"function": "initDb",
			"line": 349,
			"column": 2,
			"file_hash": "957ecf6245bb540e568abf6e29911b3998623ee65a96b7661399cbb6d458c383"
		},
		"connection.initDb.e23d8ab40c": {
			"file": "packages/sno-station-mem/src/store/connection.ts",
			"function": "initDb",
			"line": 394,
			"column": 3,
			"file_hash": "957ecf6245bb540e568abf6e29911b3998623ee65a96b7661399cbb6d458c383"
		},
		"data-bootstrap.bootstrapDataLayout.4fc42585ae": {
			"file": "packages/sno-station-mem/src/store/data-bootstrap.ts",
			"function": "bootstrapDataLayout",
			"line": 79,
			"column": 3,
			"file_hash": "b99e7ba4ad9fefad673bbc7149ed2b3b103e06cc8b4fc46f7d984b6267fc0f5f"
		},
		"data-bootstrap.bootstrapDataLayout.4af3189946": {
			"file": "packages/sno-station-mem/src/store/data-bootstrap.ts",
			"function": "bootstrapDataLayout",
			"line": 109,
			"column": 2,
			"file_hash": "b99e7ba4ad9fefad673bbc7149ed2b3b103e06cc8b4fc46f7d984b6267fc0f5f"
		},
		"maintenance.recoverDerivedFts.753697bd94": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 173,
			"column": 2,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.recoverDerivedFts.2cf5f62053": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 190,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.recoverDerivedFts.c07ad948a2": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 201,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.failClosed.b9166d3fe2": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "failClosed",
			"line": 234,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.failClosed.dd7955e647": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "failClosed",
			"line": 241,
			"column": 2,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.747b7cbef0": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 308,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.db1242ce1c": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 342,
			"column": 4,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.4ae162dc73": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 350,
			"column": 4,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.c72575daaa": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 390,
			"column": 4,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.ef7a1e225c": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 407,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.90f01cc543": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 419,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.3a7c9e73cf": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 432,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.11beb09895": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 444,
			"column": 3,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.runMaintenancePass.6a1e15dc18": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 452,
			"column": 2,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.tick.e111b66415": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "tick",
			"line": 496,
			"column": 4,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.tick.6bd3e0102c": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "tick",
			"line": 505,
			"column": 4,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.<anonymous callback>.f90713a2e3": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "<anonymous callback>",
			"line": 533,
			"column": 5,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"maintenance.startMaintenanceTimer.06c1e98584": {
			"file": "packages/sno-station-mem/src/store/maintenance.ts",
			"function": "startMaintenanceTimer",
			"line": 552,
			"column": 2,
			"file_hash": "925a4b47bb564234eb8191ebbdb7d30d1fd20a0acb3913cd97a3a905ba23ea1d"
		},
		"memory-store-admin-api.delete.5a8c32b1ed": {
			"file": "packages/sno-station-mem/src/store/memory-store-admin-api.ts",
			"function": "delete",
			"line": 57,
			"column": 3,
			"file_hash": "b9cf5b493c8aa49a3dd1d8694ee75af5de94279d41588dab9b6b62617aed79be"
		},
		"memory-store-admin-api.deleteMany.e73022fb31": {
			"file": "packages/sno-station-mem/src/store/memory-store-admin-api.ts",
			"function": "deleteMany",
			"line": 101,
			"column": 3,
			"file_hash": "b9cf5b493c8aa49a3dd1d8694ee75af5de94279d41588dab9b6b62617aed79be"
		},
		"memory-store-admin-api.bulkDelete.2631f303e5": {
			"file": "packages/sno-station-mem/src/store/memory-store-admin-api.ts",
			"function": "bulkDelete",
			"line": 167,
			"column": 3,
			"file_hash": "b9cf5b493c8aa49a3dd1d8694ee75af5de94279d41588dab9b6b62617aed79be"
		},
		"memory-store-admin-api.<anonymous callback>.130719fdd0": {
			"file": "packages/sno-station-mem/src/store/memory-store-admin-api.ts",
			"function": "<anonymous callback>",
			"line": 263,
			"column": 5,
			"file_hash": "b9cf5b493c8aa49a3dd1d8694ee75af5de94279d41588dab9b6b62617aed79be"
		},
		"memory-store-admin-api.closeSqlite.61a563b112": {
			"file": "packages/sno-station-mem/src/store/memory-store-admin-api.ts",
			"function": "closeSqlite",
			"line": 316,
			"column": 4,
			"file_hash": "b9cf5b493c8aa49a3dd1d8694ee75af5de94279d41588dab9b6b62617aed79be"
		},
		"memory-store-atomic-extraction-ledger-api.reopenAtomicExtractionChunk.e05258e34b": {
			"file": "packages/sno-station-mem/src/store/memory-store-atomic-extraction-ledger-api.ts",
			"function": "reopenAtomicExtractionChunk",
			"line": 315,
			"column": 4,
			"file_hash": "050c1bfe61e55eaaf25b87754c996842b8672ddd1272342a2d882820e67f32bf"
		},
		"memory-store-backfill.backfillMissingChunks.7094298b4a": {
			"file": "packages/sno-station-mem/src/store/memory-store-backfill.ts",
			"function": "backfillMissingChunks",
			"line": 40,
			"column": 6,
			"file_hash": "907db880162b2e37c19430db16f272cd70020f0289de485c32d188b39ddacfeb"
		},
		"memory-store-backfill.<anonymous callback>.c483e84a68": {
			"file": "packages/sno-station-mem/src/store/memory-store-backfill.ts",
			"function": "<anonymous callback>",
			"line": 110,
			"column": 6,
			"file_hash": "907db880162b2e37c19430db16f272cd70020f0289de485c32d188b39ddacfeb"
		},
		"memory-store-backfill.<anonymous callback>.c4019a929d": {
			"file": "packages/sno-station-mem/src/store/memory-store-backfill.ts",
			"function": "<anonymous callback>",
			"line": 129,
			"column": 5,
			"file_hash": "907db880162b2e37c19430db16f272cd70020f0289de485c32d188b39ddacfeb"
		},
		"memory-store-base.<anonymous callback>.3dd5e75e4f": {
			"file": "packages/sno-station-mem/src/store/memory-store-base.ts",
			"function": "<anonymous callback>",
			"line": 984,
			"column": 3,
			"file_hash": "f61e0c528432f8afe1f283050ae098422b7e3705a6f971bd00bde4fc1699db86"
		},
		"memory-store-chunk-search.searchChunksSemantic.7d889feb61": {
			"file": "packages/sno-station-mem/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 202,
			"column": 6,
			"file_hash": "7b0c91d2c5f1d7170262fc9c5ce7461995a690c154b3508de0b4d12294be015b"
		},
		"memory-store-chunk-search.searchChunksSemantic.fa074292e0": {
			"file": "packages/sno-station-mem/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 226,
			"column": 4,
			"file_hash": "7b0c91d2c5f1d7170262fc9c5ce7461995a690c154b3508de0b4d12294be015b"
		},
		"memory-store-chunk-search.searchChunksKeyword.26628a27c1": {
			"file": "packages/sno-station-mem/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksKeyword",
			"line": 335,
			"column": 4,
			"file_hash": "7b0c91d2c5f1d7170262fc9c5ce7461995a690c154b3508de0b4d12294be015b"
		},
		"memory-store-chunk-search.searchChunksKeyword.36ca2cc1d7": {
			"file": "packages/sno-station-mem/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksKeyword",
			"line": 348,
			"column": 4,
			"file_hash": "7b0c91d2c5f1d7170262fc9c5ce7461995a690c154b3508de0b4d12294be015b"
		},
		"memory-store-persistence-api.store.8fd6a993e7": {
			"file": "packages/sno-station-mem/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 116,
			"column": 3,
			"file_hash": "be0afa21c07f97e4119715bc499713835903e0729e3bb938eeb9114cea460623"
		},
		"memory-store-persistence-api.store.2f479e68bf": {
			"file": "packages/sno-station-mem/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 192,
			"column": 5,
			"file_hash": "be0afa21c07f97e4119715bc499713835903e0729e3bb938eeb9114cea460623"
		},
		"memory-store-persistence-api.store.14bfc8e321": {
			"file": "packages/sno-station-mem/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 210,
			"column": 4,
			"file_hash": "be0afa21c07f97e4119715bc499713835903e0729e3bb938eeb9114cea460623"
		},
		"memory-store-persistence-api.<anonymous callback>.b07cd1be28": {
			"file": "packages/sno-station-mem/src/store/memory-store-persistence-api.ts",
			"function": "<anonymous callback>",
			"line": 232,
			"column": 6,
			"file_hash": "be0afa21c07f97e4119715bc499713835903e0729e3bb938eeb9114cea460623"
		},
		"memory-store-persistence-api.<anonymous callback>.087a18a049": {
			"file": "packages/sno-station-mem/src/store/memory-store-persistence-api.ts",
			"function": "<anonymous callback>",
			"line": 246,
			"column": 5,
			"file_hash": "be0afa21c07f97e4119715bc499713835903e0729e3bb938eeb9114cea460623"
		},
		"memory-store-persistence-api.supersede.77de7ddab1": {
			"file": "packages/sno-station-mem/src/store/memory-store-persistence-api.ts",
			"function": "supersede",
			"line": 761,
			"column": 3,
			"file_hash": "be0afa21c07f97e4119715bc499713835903e0729e3bb938eeb9114cea460623"
		},
		"memory-store-read-api.getMemoryMetadata.35e63c5534": {
			"file": "packages/sno-station-mem/src/store/memory-store-read-api.ts",
			"function": "getMemoryMetadata",
			"line": 190,
			"column": 4,
			"file_hash": "cad1d0496b84a863719632bb22ff330704bacf3fc7b0107491380a19c5c12dbf"
		},
		"memory-store-rem-api.applyRemTextVersion.6422a9ebd1": {
			"file": "packages/sno-station-mem/src/store/memory-store-rem-api.ts",
			"function": "applyRemTextVersion",
			"line": 83,
			"column": 5,
			"file_hash": "dac099c2a68d1f2d9a7d51ae8dd3fc40e60b104564150e666fa8f3f169242a9f"
		},
		"memory-store-rem-api.applyTransaction.47fe85179a": {
			"file": "packages/sno-station-mem/src/store/memory-store-rem-api.ts",
			"function": "applyTransaction",
			"line": 204,
			"column": 3,
			"file_hash": "dac099c2a68d1f2d9a7d51ae8dd3fc40e60b104564150e666fa8f3f169242a9f"
		},
		"memory-store-search-api.searchSemantic.a8cee42447": {
			"file": "packages/sno-station-mem/src/store/memory-store-search-api.ts",
			"function": "searchSemantic",
			"line": 268,
			"column": 3,
			"file_hash": "7d17c6915458de14e46c041f8d4867a09b32adf9a967f0415bcb36713e74d19b"
		},
		"memory-store-search-api.searchKeyword.f4293a3f14": {
			"file": "packages/sno-station-mem/src/store/memory-store-search-api.ts",
			"function": "searchKeyword",
			"line": 322,
			"column": 3,
			"file_hash": "7d17c6915458de14e46c041f8d4867a09b32adf9a967f0415bcb36713e74d19b"
		},
		"memory-store-search-api.attachSnippets.896a3e960a": {
			"file": "packages/sno-station-mem/src/store/memory-store-search-api.ts",
			"function": "attachSnippets",
			"line": 375,
			"column": 5,
			"file_hash": "7d17c6915458de14e46c041f8d4867a09b32adf9a967f0415bcb36713e74d19b"
		},
		"memory-store-update-api.update.31162cf4e4": {
			"file": "packages/sno-station-mem/src/store/memory-store-update-api.ts",
			"function": "update",
			"line": 182,
			"column": 3,
			"file_hash": "544058914df3038d76c6fa8fbdbeb024f4fe8e3bd25b3727effabfe346b3f5e3"
		},
		"memory-store-update-api.updateTier.feb5a5165b": {
			"file": "packages/sno-station-mem/src/store/memory-store-update-api.ts",
			"function": "updateTier",
			"line": 442,
			"column": 3,
			"file_hash": "544058914df3038d76c6fa8fbdbeb024f4fe8e3bd25b3727effabfe346b3f5e3"
		},
		"memory-store-update-api.updateMetadata.6e33353e47": {
			"file": "packages/sno-station-mem/src/store/memory-store-update-api.ts",
			"function": "updateMetadata",
			"line": 470,
			"column": 3,
			"file_hash": "544058914df3038d76c6fa8fbdbeb024f4fe8e3bd25b3727effabfe346b3f5e3"
		},
		"memory-store-update-api.resolveReflectionItem.f1d6aa0eab": {
			"file": "packages/sno-station-mem/src/store/memory-store-update-api.ts",
			"function": "resolveReflectionItem",
			"line": 500,
			"column": 3,
			"file_hash": "544058914df3038d76c6fa8fbdbeb024f4fe8e3bd25b3727effabfe346b3f5e3"
		},
		"memory-store-update-api.applyMetadataDeltas.49983b35b4": {
			"file": "packages/sno-station-mem/src/store/memory-store-update-api.ts",
			"function": "applyMetadataDeltas",
			"line": 551,
			"column": 3,
			"file_hash": "544058914df3038d76c6fa8fbdbeb024f4fe8e3bd25b3727effabfe346b3f5e3"
		},
		"memory-store-update-api.applyMetadataDelta.6961c06549": {
			"file": "packages/sno-station-mem/src/store/memory-store-update-api.ts",
			"function": "applyMetadataDelta",
			"line": 588,
			"column": 3,
			"file_hash": "544058914df3038d76c6fa8fbdbeb024f4fe8e3bd25b3727effabfe346b3f5e3"
		},
		"memory-store-write-validation.shapeAlarm.3383666e9c": {
			"file": "packages/sno-station-mem/src/store/memory-store-write-validation.ts",
			"function": "shapeAlarm",
			"line": 108,
			"column": 2,
			"file_hash": "c51c1ec11aad2499c3b9082c1c6cfad15b8a6b5f92a92a9ac798aedc429a2a83"
		},
		"rem-sqlite-adapter.mutateAttempt.4c4b5764ca": {
			"file": "packages/sno-station-mem/src/store/rem-sqlite-adapter.ts",
			"function": "mutateAttempt",
			"line": 485,
			"column": 6,
			"file_hash": "1220e9ac39731b8860a0c17ee4092d65d2e4905979a6e2942f57282605d8c618"
		},
		"unplaced-candidate-migration.migrateUnplacedCandidates.c87865ef90": {
			"file": "packages/sno-station-mem/src/store/unplaced-candidate-migration.ts",
			"function": "migrateUnplacedCandidates",
			"line": 116,
			"column": 2,
			"file_hash": "4f4e25d32151e7fbd24e5f9ac093cc83c29e6e7e7ea51201916fdb4187c318aa"
		}
	}
};
