// Generated by scripts/build-log-catalog.ts.
import type { LogSiteCatalog } from "@snoai/utils";
export const logSiteCatalog: LogSiteCatalog = {
	"build_id": "add960508d6c89dcc61634ebe4f773a56ee948f0fc159345bf1851c700193ae5",
	"sites": {
		"memory.recall.budget.checked": {
			"file": "packages/memory/src/engine/bindings/memory-recall-tool.ts",
			"function": "execute",
			"line": 370,
			"column": 6,
			"file_hash": "1c90be71c591b1310acf7f6169b48eba460cf20d1c47fb433a9d8bdd00eb3213"
		},
		"memory.recall.completed": {
			"file": "packages/memory/src/engine/bindings/memory-recall-tool.ts",
			"function": "execute",
			"line": 424,
			"column": 5,
			"file_hash": "1c90be71c591b1310acf7f6169b48eba460cf20d1c47fb433a9d8bdd00eb3213"
		},
		"memory.tool.operation.failed": {
			"file": "packages/memory/src/engine/bindings/memory-tool-results.ts",
			"function": "makeResult",
			"line": 22,
			"column": 15,
			"file_hash": "ee320af446188c11d6dad1a99b05d663d2d58d5c78c2b46414d87336ed809f3e"
		},
		"memory.capture.local.write.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "runLocalFirstCapture",
			"line": 106,
			"column": 4,
			"file_hash": "847967d07524e2f9e6cb63e811af74d619dde675204022295ad6c97af3040110"
		},
		"memory.capture.local.completed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "runLocalFirstCapture",
			"line": 117,
			"column": 2,
			"file_hash": "847967d07524e2f9e6cb63e811af74d619dde675204022295ad6c97af3040110"
		},
		"memory.capture.hook.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "onAgentEnd",
			"line": 241,
			"column": 3,
			"file_hash": "847967d07524e2f9e6cb63e811af74d619dde675204022295ad6c97af3040110"
		},
		"memory.capture.hook.completed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-ambient-learning-hook.ts",
			"function": "onAgentEnd",
			"line": 252,
			"column": 3,
			"file_hash": "847967d07524e2f9e6cb63e811af74d619dde675204022295ad6c97af3040110"
		},
		"memory.auto_recall.query.limited": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 134,
			"column": 3,
			"file_hash": "1bb931b5dd26bbb5d4eab5d2591832d1c16ff22e876d3ef11b864181171f9bb4"
		},
		"memory.auto_recall.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 301,
			"column": 4,
			"file_hash": "1bb931b5dd26bbb5d4eab5d2591832d1c16ff22e876d3ef11b864181171f9bb4"
		},
		"memory.auto_recall.completed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "onBeforeAgentStart",
			"line": 310,
			"column": 3,
			"file_hash": "1bb931b5dd26bbb5d4eab5d2591832d1c16ff22e876d3ef11b864181171f9bb4"
		},
		"memory.auto_recall.telemetry.skipped": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "recordAutoRecallUsage",
			"line": 332,
			"column": 4,
			"file_hash": "1bb931b5dd26bbb5d4eab5d2591832d1c16ff22e876d3ef11b864181171f9bb4"
		},
		"memory.auto_recall.telemetry.failed": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-auto-recall-hook.ts",
			"function": "recordAutoRecallUsage",
			"line": 367,
			"column": 4,
			"file_hash": "1bb931b5dd26bbb5d4eab5d2591832d1c16ff22e876d3ef11b864181171f9bb4"
		},
		"plugin.sno-station-mem-insight-distill-factory.buildInsightDistiller.8b084be5ca": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 50,
			"column": 3,
			"file_hash": "c8718a4fe10ce5857ee97ecc0ea0e595c27144c0ecec2b72a6c554634628a264"
		},
		"plugin.sno-station-mem-insight-distill-factory.buildInsightDistiller.6cdc733c64": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 57,
			"column": 3,
			"file_hash": "c8718a4fe10ce5857ee97ecc0ea0e595c27144c0ecec2b72a6c554634628a264"
		},
		"sno-station-mem-insight-distill-factory.buildInsightDistiller.847c5ab779": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 61,
			"column": 3,
			"file_hash": "c8718a4fe10ce5857ee97ecc0ea0e595c27144c0ecec2b72a6c554634628a264"
		},
		"plugin.sno-station-mem-insight-distill-factory.buildInsightDistiller.888f96bfef": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-insight-distill-factory.ts",
			"function": "buildInsightDistiller",
			"line": 112,
			"column": 3,
			"file_hash": "c8718a4fe10ce5857ee97ecc0ea0e595c27144c0ecec2b72a6c554634628a264"
		},
		"plugin.sno-station-mem-runtime-mode.runObserveLifecycleTask.d1856ccb13": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-runtime-mode.ts",
			"function": "runObserveLifecycleTask",
			"line": 55,
			"column": 6,
			"file_hash": "2e88dd384e6b1ec9d35acf4bd2a4d9adf45138811b637b662febf9f6615c0f68"
		},
		"plugin.sno-station-mem-runtime-mode.auditMissingHookAgentIdentity.f06795892a": {
			"file": "packages/memory/src/engine/bindings/sno-station-mem-runtime-mode.ts",
			"function": "auditMissingHookAgentIdentity",
			"line": 122,
			"column": 2,
			"file_hash": "2e88dd384e6b1ec9d35acf4bd2a4d9adf45138811b637b662febf9f6615c0f68"
		},
		"memdump.main.failed": {
			"file": "packages/memory/src/engine/diagnostics/memdump.ts",
			"function": "<module>",
			"line": 224,
			"column": 3,
			"file_hash": "9dc654cc610022fb628e886506e3c738b5f70fbfd2361ab2021c6c287d033638"
		},
		"trace.appendQaTrace.164bcaddd4": {
			"file": "packages/memory/src/engine/eval/trace.ts",
			"function": "appendQaTrace",
			"line": 141,
			"column": 3,
			"file_hash": "589f50cdd81ed6fdea43a516231b739ac2cd8ede8ef55c039b3dc6d103fbf0f1"
		},
		"trace.writeConfigSnapshot.completed": {
			"file": "packages/memory/src/engine/eval/trace.ts",
			"function": "writeConfigSnapshot",
			"line": 225,
			"column": 4,
			"file_hash": "589f50cdd81ed6fdea43a516231b739ac2cd8ede8ef55c039b3dc6d103fbf0f1"
		},
		"extraction.atomic-extraction-gauntlet.runAtomicExtractionGauntlet.365701f979": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-gauntlet.ts",
			"function": "runAtomicExtractionGauntlet",
			"line": 216,
			"column": 3,
			"file_hash": "5eff966a46b157425288ddd28391fc796cbcc201299450a9313d11794a45652e"
		},
		"extraction.atomic-extraction-reply.invalid_time": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "wireTimeSchema",
			"line": 90,
			"column": 2,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.projectRecord.327508ac5f": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 145,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.omitted_time": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 152,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.projectRecord.aac5440fc2": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 157,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.projectRecord.b92c90f285": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "projectRecord",
			"line": 164,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.salvage_ids": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "parseAtomicCaptureReply",
			"line": 318,
			"column": 4,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.salvage_spans": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "parseAtomicCaptureReply",
			"line": 323,
			"column": 4,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-extraction-reply.unresolved_enrichment_time": {
			"file": "packages/memory/src/engine/extraction/atomic-extraction-reply.ts",
			"function": "warnUnresolvedEnrichmentTime",
			"line": 349,
			"column": 3,
			"file_hash": "090ab63c76950a7f85119c50ba2486b686609ff0ae09fceaa10c22a4c1a48ad8"
		},
		"extraction.atomic-generic-extractor.enrichAtomicBatch": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "enrichAtomicBatch",
			"line": 237,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.7456414b06": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 462,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.a373dfa454": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 470,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.dc917b09a1": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 485,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.5264647de8": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 494,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.5f797c1175": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 570,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicNumericTurnSweep.fdcb677e24": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "runAtomicNumericTurnSweep",
			"line": 572,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicGenericExtractionPass.cce4a719a3": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "captureAtomicWindow",
			"line": 793,
			"column": 4,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-generic-extractor.runAtomicGenericExtractionPass.98a701bd95": {
			"file": "packages/memory/src/engine/extraction/atomic-generic-extractor.ts",
			"function": "captureAtomicWindow",
			"line": 817,
			"column": 3,
			"file_hash": "aabe5eae533241f2c0714d619228586ec021df2bfc4de385d980794c5bde4ed9"
		},
		"extraction.atomic-memory-extraction.extractAndPersist.7e1c9d2660": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "extractAndPersist",
			"line": 698,
			"column": 4,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"memory.capture.completed": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "extractAndPersist",
			"line": 851,
			"column": 4,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.readStandingSubjectCandidates.b88c6fb3aa": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "readStandingSubjectCandidates",
			"line": 989,
			"column": 5,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.reaskStandingSubjects.1288498dec": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "reaskStandingSubjects",
			"line": 1243,
			"column": 4,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.reaskStandingSubjects.2b8785b171": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "reaskStandingSubjects",
			"line": 1252,
			"column": 2,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.runAtomicMemoryExtraction.304a5a8d5c": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1522,
			"column": 3,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.over_token_ceiling": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1604,
			"column": 3,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.runAtomicMemoryExtraction.0d9673d494": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1671,
			"column": 4,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"memory.extraction.window.completed": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "runAtomicMemoryExtraction",
			"line": 1689,
			"column": 3,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.judgeArrivalRetirementPair.call_failed": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "judgeArrivalRetirementPair",
			"line": 1726,
			"column": 3,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-memory-extraction.judgeArrivalRetirementPair.reply_invalid": {
			"file": "packages/memory/src/engine/extraction/atomic-memory-extraction.ts",
			"function": "judgeArrivalRetirementPair",
			"line": 1734,
			"column": 3,
			"file_hash": "f6954375488142a443df2d450815f58d8b83434b778da5c1209f9962980eed2f"
		},
		"extraction.atomic-progress-boundary.salvage_decisions": {
			"file": "packages/memory/src/engine/extraction/atomic-progress-boundary.ts",
			"function": "parseProgressTurns",
			"line": 27,
			"column": 3,
			"file_hash": "c57ad88dba4fde39aaf635b57e556a8380c7cc9252d655de32a43045e402abc1"
		},
		"extraction.atomic-subject-guard.runAtomicSubjectGuard.037dc017c1": {
			"file": "packages/memory/src/engine/extraction/atomic-subject-guard.ts",
			"function": "runAtomicSubjectGuard",
			"line": 277,
			"column": 3,
			"file_hash": "573e80974a2d733677afbb5e5249b18676cf80cc2ab8d16f13f8a892836ab5c7"
		},
		"extraction.atomic-subject-guard.runAtomicSubjectGuard.7fbb9c4f6d": {
			"file": "packages/memory/src/engine/extraction/atomic-subject-guard.ts",
			"function": "runAtomicSubjectGuard",
			"line": 296,
			"column": 3,
			"file_hash": "573e80974a2d733677afbb5e5249b18676cf80cc2ab8d16f13f8a892836ab5c7"
		},
		"b-profile-section-dictionary-provider.restoreCachedSectionDictionary.a4518aedd5": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "restoreCachedSectionDictionary",
			"line": 252,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.ac5ddcab10": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 292,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.a8ecb1a4f2": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 322,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-dictionary-provider.loadRemoteSectionDictionary.15ee874f33": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-dictionary-provider.ts",
			"function": "loadRemoteSectionDictionary",
			"line": 345,
			"column": 3,
			"file_hash": "c2c58be70654d49d54d1c959a7ddbca41061e45d3e9da9fb6deb728d57cc4ae8"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.b452a7657e": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 94,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.4494531e35": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 116,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.5276d7dfea": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 125,
			"column": 4,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.1acb6c65f8": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 141,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.d8bb76de51": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 150,
			"column": 4,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.runBProfileSectionRekey.ce06a215a3": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "runBProfileSectionRekey",
			"line": 175,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.<anonymous callback>.9cc8218e54": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "<anonymous callback>",
			"line": 196,
			"column": 3,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.assertPlanReconciles.03748b5c20": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "assertPlanReconciles",
			"line": 890,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.assertCanonicalPlanReconciles.2ad72089d1": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "assertCanonicalPlanReconciles",
			"line": 902,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"b-profile-section-rekey.throwReconciliationError.b59b599311": {
			"file": "packages/memory/src/engine/extraction/b-profile-section-rekey.ts",
			"function": "throwReconciliationError",
			"line": 912,
			"column": 2,
			"file_hash": "5e1afda5e2bf616c55ed3aad3baac2474cc008db02cbfe260824214aac200176"
		},
		"date-resolution.model_unavailable": {
			"file": "packages/memory/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 83,
			"column": 3,
			"file_hash": "50e5a2ee0b405e2d835fe11ea1c68bd2513c52d4dd52df52160a2a31ce4f869b"
		},
		"date-resolution.resolveMemoryDate.1224fa35b2": {
			"file": "packages/memory/src/engine/extraction/date-resolution.ts",
			"function": "resolveMemoryDate",
			"line": 91,
			"column": 2,
			"file_hash": "50e5a2ee0b405e2d835fe11ea1c68bd2513c52d4dd52df52160a2a31ce4f869b"
		},
		"embedding-provider-client.<anonymous callback>.3c8d5ee192": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 73,
			"column": 3,
			"file_hash": "ca77ad6b2ebc7b2af4cdb4ab49d9ad9beddda3c1f4608f93c981b4da5373979b"
		},
		"embedding-provider-client.embed.ab60111378": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embed",
			"line": 174,
			"column": 3,
			"file_hash": "ca77ad6b2ebc7b2af4cdb4ab49d9ad9beddda3c1f4608f93c981b4da5373979b"
		},
		"embedding-provider-client.embedDirect.c6998ac2fb": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedDirect",
			"line": 207,
			"column": 4,
			"file_hash": "ca77ad6b2ebc7b2af4cdb4ab49d9ad9beddda3c1f4608f93c981b4da5373979b"
		},
		"embedding-provider-client.embedMany.8ffe2fb365": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedMany",
			"line": 225,
			"column": 3,
			"file_hash": "ca77ad6b2ebc7b2af4cdb4ab49d9ad9beddda3c1f4608f93c981b4da5373979b"
		},
		"embedding-provider-client.embedMany.71b35eadaf": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "embedMany",
			"line": 244,
			"column": 4,
			"file_hash": "ca77ad6b2ebc7b2af4cdb4ab49d9ad9beddda3c1f4608f93c981b4da5373979b"
		},
		"embedding-provider-client.<anonymous callback>.32cc9ec43e": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 295,
			"column": 5,
			"file_hash": "ca77ad6b2ebc7b2af4cdb4ab49d9ad9beddda3c1f4608f93c981b4da5373979b"
		},
		"embedding-provider-client.<anonymous callback>.d7a3f8337c": {
			"file": "packages/memory/src/engine/extraction/embedding-provider-client.ts",
			"function": "<anonymous callback>",
			"line": 302,
			"column": 5,
			"file_hash": "ca77ad6b2ebc7b2af4cdb4ab49d9ad9beddda3c1f4608f93c981b4da5373979b"
		},
		"extraction.extraction-text-sanitizer.boundSectionContent.ceiling": {
			"file": "packages/memory/src/engine/extraction/extraction-text-sanitizer.ts",
			"function": "boundSectionContent",
			"line": 48,
			"column": 2,
			"file_hash": "57c114de4c1c67ea85455288b3892f1153173e64b1b967fd95eb1e50e2924a81"
		},
		"insight-distill-write-actions.sessionTimestampField.29d4b22da7": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "sessionTimestampField",
			"line": 417,
			"column": 3,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.storeCandidate.138415ce64": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "storeCandidate",
			"line": 508,
			"column": 3,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.storeCandidate.6754f6ee4b": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "storeCandidate",
			"line": 519,
			"column": 3,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.handleSupport.c98c47eeb9": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleSupport",
			"line": 555,
			"column": 2,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.handleContextualize.bd66df2159": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleContextualize",
			"line": 615,
			"column": 2,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"insight-distill-write-actions.handleContradict.c6164031da": {
			"file": "packages/memory/src/engine/extraction/insight-distill-write-actions.ts",
			"function": "handleContradict",
			"line": 692,
			"column": 2,
			"file_hash": "2fc18e01d9ad1b25cfdf0987a7b06ecf50217cb79426e1af9dbbeb065d7d577d"
		},
		"profile-section-writer.deferLifecycleRetirement.f94b354ff4": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "deferLifecycleRetirement",
			"line": 323,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"memory.profile.task.completed": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 451,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"memory.profile.section.completed": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 481,
			"column": 2,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"memory.profile.failed": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdate",
			"line": 492,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.28936dcd3c": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 676,
			"column": 4,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.e3afdfb6d8": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 749,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.runProfileSectionUpdateOnce.80241da6d8": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "runProfileSectionUpdateOnce",
			"line": 805,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.recheckProfileRetirements.613c569527": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "recheckProfileRetirements",
			"line": 982,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.mergeProfileSection.c707285ef3": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "mergeProfileSection",
			"line": 1087,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.writeEpisodicSafetyNet.ae69446388": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "writeEpisodicSafetyNet",
			"line": 1390,
			"column": 2,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.capRetireByNameWorkItems.3c47653418": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "capRetireByNameWorkItems",
			"line": 1630,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.writeProfileRow.3e3e26a255": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "writeProfileRow",
			"line": 1668,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.planProfileConflicts.e5bcea94ce": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2139,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.planProfileConflicts.97b6a2e824": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2205,
			"column": 5,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.planProfileConflicts.b4962bc7f0": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "planProfileConflicts",
			"line": 2225,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.logProfileConflictFenceRejection.b0669b40b3": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "logProfileConflictFenceRejection",
			"line": 2249,
			"column": 2,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"profile-section-writer.adjudicateSafely.d3f7ab0ac5": {
			"file": "packages/memory/src/engine/extraction/profile-section-writer.ts",
			"function": "adjudicateSafely",
			"line": 2297,
			"column": 3,
			"file_hash": "c6f09c85bd637ab5057e9026271189f8e560c8cc7ed1d9e4ac353f3641a83aa3"
		},
		"language.detector.unavailable": {
			"file": "packages/memory/src/engine/i18n/detector.ts",
			"function": "markDetectorBroken",
			"line": 29,
			"column": 2,
			"file_hash": "784d4695bcd424b2b7e55ec1cf7f4e698c6767b45a45eceeac6aa82578541a22"
		},
		"registry.loadLocale.aad78d489e": {
			"file": "packages/memory/src/engine/i18n/registry.ts",
			"function": "loadLocale",
			"line": 58,
			"column": 3,
			"file_hash": "d06faf72925fb311d6439b3fe47c44d3df19ce8b7ddfe4f8a6b4710103455f8e"
		},
		"group-maintenance.stale-keying": {
			"file": "packages/memory/src/engine/maintenance/group-crud-maintenance.ts",
			"function": "updateKeyedRow",
			"line": 259,
			"column": 23,
			"file_hash": "63030db6ae823438d0a24ef9221b786a184a49df185f78ef86b4879ab770d068"
		},
		"group-maintenance.stale-merge": {
			"file": "packages/memory/src/engine/maintenance/group-crud-maintenance.ts",
			"function": "mergeSplitEntities",
			"line": 567,
			"column": 5,
			"file_hash": "63030db6ae823438d0a24ef9221b786a184a49df185f78ef86b4879ab770d068"
		},
		"memory.group_crud.host_calls_skipped": {
			"file": "packages/memory/src/engine/maintenance/run-group-crud-maintenance.ts",
			"function": "main",
			"line": 49,
			"column": 4,
			"file_hash": "468a46b98be70be90ccd6d2cef2468e5e3ee3d5272774839723319297b94a6f3"
		},
		"observability.emit.failed": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "PluginObservability.tryEmit",
			"line": 126,
			"column": 4,
			"file_hash": "8bf0aabdc5d8220ec5cfbbe70a5a75d0ae4a538aa24918f410166748ba47d8d1"
		},
		"adapter.<anonymous callback>.82f49c57a7": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 150,
			"column": 7,
			"file_hash": "8bf0aabdc5d8220ec5cfbbe70a5a75d0ae4a538aa24918f410166748ba47d8d1"
		},
		"observability.background.timed_out": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "PluginObservability.runBackgroundTask",
			"line": 204,
			"column": 7,
			"file_hash": "8bf0aabdc5d8220ec5cfbbe70a5a75d0ae4a538aa24918f410166748ba47d8d1"
		},
		"adapter.<anonymous callback>.f036514cb8": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 241,
			"column": 9,
			"file_hash": "8bf0aabdc5d8220ec5cfbbe70a5a75d0ae4a538aa24918f410166748ba47d8d1"
		},
		"adapter.<anonymous callback>.9aedc01548": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 280,
			"column": 9,
			"file_hash": "8bf0aabdc5d8220ec5cfbbe70a5a75d0ae4a538aa24918f410166748ba47d8d1"
		},
		"adapter.<anonymous callback>.52f64c2607": {
			"file": "packages/memory/src/engine/observability/adapter.ts",
			"function": "<anonymous callback>",
			"line": 322,
			"column": 9,
			"file_hash": "8bf0aabdc5d8220ec5cfbbe70a5a75d0ae4a538aa24918f410166748ba47d8d1"
		},
		"observability.bestEffort.failed": {
			"file": "packages/memory/src/engine/observability/best-effort.ts",
			"function": "bestEffort",
			"line": 23,
			"column": 3,
			"file_hash": "fadc0065ebbb451c41b27b4371383815f97eefcb845bab26d36a2cffd2ad0540"
		},
		"observability.bestEffortSync.failed": {
			"file": "packages/memory/src/engine/observability/best-effort.ts",
			"function": "bestEffortSync",
			"line": 40,
			"column": 3,
			"file_hash": "fadc0065ebbb451c41b27b4371383815f97eefcb845bab26d36a2cffd2ad0540"
		},
		"runtime.process.started": {
			"file": "packages/memory/src/engine/observability/runtime-diagnostics.ts",
			"function": "emitRuntimeStartSnapshot",
			"line": 68,
			"column": 2,
			"file_hash": "663569d9c483cb5e211ead6fd78b68292451b1cf990bbe933d95d33fa8a65496"
		},
		"memory.operation.aborted": {
			"file": "packages/memory/src/engine/operation-cancellation.ts",
			"function": "withMemoryOperation",
			"line": 25,
			"column": 25,
			"file_hash": "2aab77e9affc53a0cbdad2c64a90cfe8eba5e702debfe6603302e778ab07bed9"
		},
		"memory.spend.stat.failed": {
			"file": "packages/memory/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 39,
			"column": 4,
			"file_hash": "d84c2c09924ba4013d03677cb00d8748394ff903d87bf215c6845378e1f4c186"
		},
		"memory.spend.stream.failed": {
			"file": "packages/memory/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 103,
			"column": 3,
			"file_hash": "d84c2c09924ba4013d03677cb00d8748394ff903d87bf215c6845378e1f4c186"
		},
		"memory.spend.rows.invalid": {
			"file": "packages/memory/src/engine/operations/daily-spend-estimator.ts",
			"function": "readEstimatedSpendToday",
			"line": 109,
			"column": 26,
			"file_hash": "d84c2c09924ba4013d03677cb00d8748394ff903d87bf215c6845378e1f4c186"
		},
		"memory.jsonl.read.failed": {
			"file": "packages/memory/src/engine/operations/jsonl-lines.ts",
			"function": "readJsonlLines",
			"line": 15,
			"column": 3,
			"file_hash": "d3833ca8d82845c46163b92ce720917961a6dd543676bb57ff0e53930a17cba8"
		},
		"memory.learning.lock.close.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 105,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.lock.cleanup.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 110,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.lock.stat.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 124,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.lock.stale.cleanup.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "withAppendLock",
			"line": 133,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.history.read.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "nextLearningId",
			"line": 155,
			"column": 4,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.ensure.read.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "ensureLearningFile",
			"line": 175,
			"column": 4,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.learning.append.read.failed": {
			"file": "packages/memory/src/engine/operations/learning-file-maintenance.ts",
			"function": "appendSelfImprovementEntry",
			"line": 306,
			"column": 6,
			"file_hash": "575a39212b864bef8799ec75052b1772e5ee2b7cbedbcadfca988818225113f0"
		},
		"memory.audit.append.failed": {
			"file": "packages/memory/src/engine/operations/runtime-audit-log.ts",
			"function": "enqueueAuditWrite",
			"line": 297,
			"column": 4,
			"file_hash": "0c6396aee17b5450a4a285cdaee2241a30f49e4a822899a8bd17554dbe939825"
		},
		"memory.audit.detail.unknown": {
			"file": "packages/memory/src/engine/operations/runtime-audit-log.ts",
			"function": "prepareAuditEntry",
			"line": 356,
			"column": 4,
			"file_hash": "0c6396aee17b5450a4a285cdaee2241a30f49e4a822899a8bd17554dbe939825"
		},
		"memory.audit.sync.failed": {
			"file": "packages/memory/src/engine/operations/runtime-audit-log.ts",
			"function": "appendAuditEntrySync",
			"line": 406,
			"column": 3,
			"file_hash": "0c6396aee17b5450a4a285cdaee2241a30f49e4a822899a8bd17554dbe939825"
		},
		"memory.session.file.stat.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "sortFileNamesByMtimeDesc",
			"line": 33,
			"column": 6,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.read.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionMessages",
			"line": 135,
			"column": 4,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.rows.invalid": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionMessages",
			"line": 141,
			"column": 40,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.reset.discovery.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "readSessionContentWithResetFallback",
			"line": 179,
			"column": 4,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"memory.session.previous.discovery.failed": {
			"file": "packages/memory/src/engine/operations/session-summary-storage.ts",
			"function": "findPreviousSessionFile",
			"line": 238,
			"column": 4,
			"file_hash": "930eb36391d3f064f4ab80e18d9be6f16a8e70058d8cd404af5d83035f1fe6b6"
		},
		"stale-memory-demotion.runStaleDemotion.e86f004935": {
			"file": "packages/memory/src/engine/operations/stale-memory-demotion.ts",
			"function": "runStaleDemotion",
			"line": 96,
			"column": 4,
			"file_hash": "a30813cb8831d3d79008b715c8b51163020c607296cf67a3e1beffed82995718"
		},
		"stale-memory-demotion.runStaleDemotion.d7a77107bb": {
			"file": "packages/memory/src/engine/operations/stale-memory-demotion.ts",
			"function": "runStaleDemotion",
			"line": 108,
			"column": 2,
			"file_hash": "a30813cb8831d3d79008b715c8b51163020c607296cf67a3e1beffed82995718"
		},
		"memory.provider.canonical.discovery.degraded": {
			"file": "packages/memory/src/engine/provider/canonical-memory-corpus.ts",
			"function": "listCanonicalMemoryFiles",
			"line": 243,
			"column": 40,
			"file_hash": "9f11af337ab01fec185f3a6401346d3e98757259425ac413c762e7416b3843a7"
		},
		"memory.provider.manager.resolved": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.getMemorySearchManager",
			"line": 161,
			"column": 5,
			"file_hash": "840cf247d61d150af6e6ebba37b55c1f2d6597ff5dd7e93ec17272ed95db22ec"
		},
		"memory.provider.manager.close.skipped": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeMemorySearchManager",
			"line": 179,
			"column": 5,
			"file_hash": "840cf247d61d150af6e6ebba37b55c1f2d6597ff5dd7e93ec17272ed95db22ec"
		},
		"memory.provider.manager.close.failed": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeMemorySearchManager",
			"line": 197,
			"column": 5,
			"file_hash": "840cf247d61d150af6e6ebba37b55c1f2d6597ff5dd7e93ec17272ed95db22ec"
		},
		"memory.provider.managers.shutdown.completed": {
			"file": "packages/memory/src/engine/provider/provider-registration.ts",
			"function": "createMemoryRuntime.closeAllMemorySearchManagers",
			"line": 225,
			"column": 5,
			"file_hash": "840cf247d61d150af6e6ebba37b55c1f2d6597ff5dd7e93ec17272ed95db22ec"
		},
		"memory.provider.search.completed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.search",
			"line": 200,
			"column": 4,
			"file_hash": "1950a9e460ee0b7633ffe2733e07e81a8c6b9e30c31d01b6ab7183f565494472"
		},
		"memory.provider.read.completed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.readFile",
			"line": 259,
			"column": 4,
			"file_hash": "1950a9e460ee0b7633ffe2733e07e81a8c6b9e30c31d01b6ab7183f565494472"
		},
		"memory.provider.status.completed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.status",
			"line": 286,
			"column": 3,
			"file_hash": "1950a9e460ee0b7633ffe2733e07e81a8c6b9e30c31d01b6ab7183f565494472"
		},
		"memory.provider.status.failed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.status",
			"line": 318,
			"column": 4,
			"file_hash": "1950a9e460ee0b7633ffe2733e07e81a8c6b9e30c31d01b6ab7183f565494472"
		},
		"memory.provider.manager.closed": {
			"file": "packages/memory/src/engine/provider/provider-search-manager.ts",
			"function": "SnoStationMemProviderSearchManager.close",
			"line": 389,
			"column": 3,
			"file_hash": "1950a9e460ee0b7633ffe2733e07e81a8c6b9e30c31d01b6ab7183f565494472"
		},
		"reflection.daily-log-generator.onRetryLog.b52810f5af": {
			"file": "packages/memory/src/engine/reflection/daily-log-generator.ts",
			"function": "onRetryLog",
			"line": 225,
			"column": 25,
			"file_hash": "de5a5befbd25f92a514005be34636e618994a99273504a3b1e89eed3892d13ea"
		},
		"reflection.daily-log-generator.onRetryLog.977c99d43c": {
			"file": "packages/memory/src/engine/reflection/daily-log-generator.ts",
			"function": "onRetryLog",
			"line": 226,
			"column": 8,
			"file_hash": "de5a5befbd25f92a514005be34636e618994a99273504a3b1e89eed3892d13ea"
		},
		"reflection.daily-log-generator.generateReflectionText.c0c554e65c": {
			"file": "packages/memory/src/engine/reflection/daily-log-generator.ts",
			"function": "generateReflectionText",
			"line": 256,
			"column": 4,
			"file_hash": "de5a5befbd25f92a514005be34636e618994a99273504a3b1e89eed3892d13ea"
		},
		"memory.reflection.command.completed": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "createRunMemoryReflection",
			"line": 131,
			"column": 4,
			"file_hash": "d7688cc110b0a656f30af82f9b54c0720e1bb0875e5f7bef9c3d647c8ce458f8"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.be803e8310": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 224,
			"column": 4,
			"file_hash": "d7688cc110b0a656f30af82f9b54c0720e1bb0875e5f7bef9c3d647c8ce458f8"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.2a047c8826": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 259,
			"column": 3,
			"file_hash": "d7688cc110b0a656f30af82f9b54c0720e1bb0875e5f7bef9c3d647c8ce458f8"
		},
		"reflection.reflection-command-hooks.runMemoryReflectionBody.55c5adf2a5": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "runMemoryReflectionBody",
			"line": 264,
			"column": 3,
			"file_hash": "d7688cc110b0a656f30af82f9b54c0720e1bb0875e5f7bef9c3d647c8ce458f8"
		},
		"reflection.reflection-command-hooks.appendGovernanceEntries.805fa046d0": {
			"file": "packages/memory/src/engine/reflection/reflection-command-hooks.ts",
			"function": "appendGovernanceEntries",
			"line": 413,
			"column": 4,
			"file_hash": "d7688cc110b0a656f30af82f9b54c0720e1bb0875e5f7bef9c3d647c8ce458f8"
		},
		"reflection.reflection-injection-hooks.registerInheritedRulesHook.43c14eb8b9": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerInheritedRulesHook",
			"line": 165,
			"column": 5,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerDerivedFocusHook.d23bb07c04": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerDerivedFocusHook",
			"line": 187,
			"column": 6,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerDerivedFocusHook.bbe1a0ae1e": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerDerivedFocusHook",
			"line": 223,
			"column": 5,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerV3SliceHook.d23bb07c04": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerV3SliceHook",
			"line": 267,
			"column": 6,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-injection-hooks.registerV3SliceHook.1800747d30": {
			"file": "packages/memory/src/engine/reflection/reflection-injection-hooks.ts",
			"function": "registerV3SliceHook",
			"line": 293,
			"column": 5,
			"file_hash": "6da906e42b96ce7dd623208ecc4995400ef18ab9d558bb75c50ef5d66768a398"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.d4cb1a8408": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 108,
			"column": 3,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.4f891b1d21": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 112,
			"column": 3,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.78a7536d17": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 165,
			"column": 6,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.38fe983443": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 250,
			"column": 4,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.reflection-mapped-memory-loop.runMappedMemoryLoop.b692a46de7": {
			"file": "packages/memory/src/engine/reflection/reflection-mapped-memory-loop.ts",
			"function": "runMappedMemoryLoop",
			"line": 259,
			"column": 3,
			"file_hash": "2d0a1b6d307e89e73cab473bd0706b06f372b7bc521ee8fe7c9def0dca7560be"
		},
		"reflection.session-serial-guard.runWithSerialGuard.edb3193695": {
			"file": "packages/memory/src/engine/reflection/session-serial-guard.ts",
			"function": "runWithSerialGuard",
			"line": 110,
			"column": 3,
			"file_hash": "50db48c1a6e6c6a14c3531b8f63160466c4d77e55131511be793d58668a3a1a8"
		},
		"reflection.session-serial-guard.runWithSerialGuard.2e95bc0994": {
			"file": "packages/memory/src/engine/reflection/session-serial-guard.ts",
			"function": "runWithSerialGuard",
			"line": 116,
			"column": 3,
			"file_hash": "50db48c1a6e6c6a14c3531b8f63160466c4d77e55131511be793d58668a3a1a8"
		},
		"rem.stage.journal.failed": {
			"file": "packages/memory/src/engine/rem/runner.ts",
			"function": "runRemStages",
			"line": 41,
			"column": 4,
			"file_hash": "87abefc5c865c82a6946d21e0d0e6faa50aa09f6d1ccf58db5103b3994a49674"
		},
		"access-tracker.destroy.5991e0f580": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "destroy",
			"line": 320,
			"column": 4,
			"file_hash": "c5a760fcfcad52c7e75ebcfae55e4a82fcaaa06edf49fa9626e5b4dfd373604d"
		},
		"access-tracker.doFlush.b3bb3939f2": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "doFlush",
			"line": 367,
			"column": 6,
			"file_hash": "c5a760fcfcad52c7e75ebcfae55e4a82fcaaa06edf49fa9626e5b4dfd373604d"
		},
		"access-tracker.doFlush.f82865a307": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "doFlush",
			"line": 382,
			"column": 4,
			"file_hash": "c5a760fcfcad52c7e75ebcfae55e4a82fcaaa06edf49fa9626e5b4dfd373604d"
		},
		"access-tracker.buildAccessDelta.4ac8f20936": {
			"file": "packages/memory/src/engine/retrieval/access-tracker.ts",
			"function": "buildAccessDelta",
			"line": 427,
			"column": 5,
			"file_hash": "c5a760fcfcad52c7e75ebcfae55e4a82fcaaa06edf49fa9626e5b4dfd373604d"
		},
		"query_manifest.capture.written": {
			"file": "packages/memory/src/engine/retrieval/query-manifest-capture-cli.ts",
			"function": "main",
			"line": 221,
			"column": 3,
			"file_hash": "583a26fb917a72d8fd5c5c71a042f74ec3fba6eb72e29de1d017df289d7e80f7"
		},
		"query_manifest.capture.failed": {
			"file": "packages/memory/src/engine/retrieval/query-manifest-capture-cli.ts",
			"function": "<module>",
			"line": 228,
			"column": 2,
			"file_hash": "583a26fb917a72d8fd5c5c71a042f74ec3fba6eb72e29de1d017df289d7e80f7"
		},
		"memory.retrieval.started": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 41,
			"column": 3,
			"file_hash": "4d3003c2fb293fb46140c7df579672c38d8c59863846d8fd92a065d2eaa99760"
		},
		"memory.retrieval.completed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 173,
			"column": 4,
			"file_hash": "4d3003c2fb293fb46140c7df579672c38d8c59863846d8fd92a065d2eaa99760"
		},
		"memory.retrieval.failed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieve",
			"line": 185,
			"column": 4,
			"file_hash": "4d3003c2fb293fb46140c7df579672c38d8c59863846d8fd92a065d2eaa99760"
		},
		"memory.retrieval.traced.completed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieveWithTrace",
			"line": 260,
			"column": 4,
			"file_hash": "4d3003c2fb293fb46140c7df579672c38d8c59863846d8fd92a065d2eaa99760"
		},
		"memory.retrieval.traced.failed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "retrieveWithTrace",
			"line": 268,
			"column": 4,
			"file_hash": "4d3003c2fb293fb46140c7df579672c38d8c59863846d8fd92a065d2eaa99760"
		},
		"memory.retrieval.tier.failed": {
			"file": "packages/memory/src/engine/retrieval/retriever-execution.ts",
			"function": "evaluateTopKTierTransitions",
			"line": 337,
			"column": 5,
			"file_hash": "4d3003c2fb293fb46140c7df579672c38d8c59863846d8fd92a065d2eaa99760"
		},
		"retrieval.retriever-rerank.rerank.6fbc6b3a22": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 192,
			"column": 4,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.rerank.query_over_window": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 240,
			"column": 4,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.rerank.candidate_over_ceiling": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 255,
			"column": 4,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.runBatch.over_window_repair": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 338,
			"column": 8,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.runBatch.76d7d1fac6": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 348,
			"column": 7,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.runBatch.4429b8bd8a": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "runBatch",
			"line": 363,
			"column": 7,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.rerank.7847c6248a": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 477,
			"column": 4,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.rerank.4af9c17c75": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 502,
			"column": 5,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.rerank.2c5fc67dbf": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerank",
			"line": 509,
			"column": 5,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.rerankLightweight.70eb2031f1": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerankLightweight",
			"line": 581,
			"column": 4,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-rerank.rerankLightweight.7e8d0eee29": {
			"file": "packages/memory/src/engine/retrieval/retriever-rerank.ts",
			"function": "rerankLightweight",
			"line": 586,
			"column": 3,
			"file_hash": "5ca7fe65274ede0d07a15fdb933148602eff829742a97766561066e18e522b48"
		},
		"retrieval.retriever-search-modes.aggregationComplete.5a3b7f9337": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "aggregationComplete",
			"line": 72,
			"column": 3,
			"file_hash": "0296fc257c172cc5445e71248becaf1128dc12116eb668b4e90bbb81891c1f8f"
		},
		"retrieval.retriever-search-modes.precisionRecall.97b8770f50": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 248,
			"column": 4,
			"file_hash": "0296fc257c172cc5445e71248becaf1128dc12116eb668b4e90bbb81891c1f8f"
		},
		"retrieval.retriever-search-modes.precisionRecall.c20ade60c4": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 256,
			"column": 4,
			"file_hash": "0296fc257c172cc5445e71248becaf1128dc12116eb668b4e90bbb81891c1f8f"
		},
		"retrieval.retriever-search-modes.precisionRecall.aaf0b2eb17": {
			"file": "packages/memory/src/engine/retrieval/retriever-search-modes.ts",
			"function": "precisionRecall",
			"line": 308,
			"column": 3,
			"file_hash": "0296fc257c172cc5445e71248becaf1128dc12116eb668b4e90bbb81891c1f8f"
		},
		"scope-helpers.resolveScopeFilter.0d7f91dae7": {
			"file": "packages/memory/src/engine/security/scope-helpers.ts",
			"function": "resolveScopeFilter",
			"line": 54,
			"column": 3,
			"file_hash": "ec85e30d2a1a110e7844fe4af9ae9c19e47f503ab04444ed9a5ae3bdec71b506"
		},
		"scope-helpers.resolveScopeFilter.720935590d": {
			"file": "packages/memory/src/engine/security/scope-helpers.ts",
			"function": "resolveScopeFilter",
			"line": 67,
			"column": 4,
			"file_hash": "ec85e30d2a1a110e7844fe4af9ae9c19e47f503ab04444ed9a5ae3bdec71b506"
		},
		"scope-identity.isSystemBypassId.1d89371f35": {
			"file": "packages/memory/src/engine/security/scope-identity.ts",
			"function": "isSystemBypassId",
			"line": 36,
			"column": 3,
			"file_hash": "0df23c80fb2db236266fe91a2904be6d2a7cf6bf6e28baae36fb9669a995352e"
		},
		"memory-telemetry-events.<anonymous callback>.23cfef2d08": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-events.ts",
			"function": "<anonymous callback>",
			"line": 104,
			"column": 4,
			"file_hash": "6d6fc8c3985f667d57a2f9701bffb62b5902b82f1ef52a68837de45644b82a9d"
		},
		"memory.usage.accept.failed": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.tryAcceptUsage",
			"line": 114,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.claim_failed": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 148,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.empty": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 160,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.rollback": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 215,
			"column": 4,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"memory.usage.flush.completed": {
			"file": "packages/memory/src/engine/telemetry/memory-telemetry-outbox.ts",
			"function": "MemoryTelemetryUsageOutbox.flushPending",
			"line": 233,
			"column": 3,
			"file_hash": "5cfaf7cb5c2db9ad3aba1a4fd43777f22db48756e76844ad82ee4c1e5093e8d0"
		},
		"observe.ledger.failed": {
			"file": "packages/memory/src/engine/telemetry/observe-ledger.ts",
			"function": "forwardObserveLedger",
			"line": 58,
			"column": 7,
			"file_hash": "d55aceca369305bdba14768ebdeb98c0654b3d67817e01884d82d754f11294a8"
		},
		"shared.llm-client.resolveRequestTransport.8f631601af": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "resolveRequestTransport",
			"line": 375,
			"column": 4,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"shared.llm-client.resolveRequestTransport.ffa933b519": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "resolveRequestTransport",
			"line": 381,
			"column": 4,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.host.request.completed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 430,
			"column": 6,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.host_cancelled": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 448,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.host_error": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 462,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"shared.llm-client.requestContent.ff17976562": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 495,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.raw_pipeline_failed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 518,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.chat_pipeline_failed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 546,
			"column": 4,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.empty_reply": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContent",
			"line": 560,
			"column": 4,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"shared.llm-client.requestContentRetryingEmpty.cd874fefff": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContentRetryingEmpty",
			"line": 601,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.fallback.answered": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContentWithHostFallback",
			"line": 654,
			"column": 6,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.fallback.failed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "requestContentWithHostFallback",
			"line": 671,
			"column": 3,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.json.deadline_exhausted": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 699,
			"column": 7,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"shared.llm-client.completeJson.e04c8e7e82": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 715,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.client.json.request_failed": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeJson",
			"line": 721,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"shared.llm-client.completeText.ffa933b519": {
			"file": "packages/memory/src/model/llm-client.ts",
			"function": "completeText",
			"line": 744,
			"column": 5,
			"file_hash": "2850b18a21f73dfa4afeac50f388e8057e1e2c4c110ddccfd9eb2b8d7e3c07e0"
		},
		"llm.transport.request.completed": {
			"file": "packages/memory/src/model/llm-provider-transport.ts",
			"function": "observeRequest",
			"line": 68,
			"column": 4,
			"file_hash": "7ba41a4716e6e6253bb9a6c89443cad659429a9bf924d7c30a7139ed434b8af2"
		},
		"memory.host.degraded": {
			"file": "packages/memory/src/model/registered-agent-port.ts",
			"function": "run",
			"line": 34,
			"column": 17,
			"file_hash": "b477adf0a693cdfa03376f058f63864ae082e91e3348c8b676a63d9c4176a95f"
		},
		"sidecar.config.failed": {
			"file": "packages/memory/src/sidecar/config.ts",
			"function": "reportConfigFailure",
			"line": 77,
			"column": 2,
			"file_hash": "f84a3886922b58d5787d049ce2febb72218344a4a5686c629498b8bd63b7a136"
		},
		"sidecar.main.startup.failed": {
			"file": "packages/memory/src/sidecar/main.ts",
			"function": "<module>",
			"line": 20,
			"column": 3,
			"file_hash": "fe128214b9e5234beb2929a3e3d1cc01e2df1968eb4063760df5ba3976daf042"
		},
		"memory.sidecar.request.failed": {
			"file": "packages/memory/src/sidecar/memory-routes.ts",
			"function": "serveMemoryRoute",
			"line": 50,
			"column": 4,
			"file_hash": "efc5a940d2ef8da20eed0d7b459b96391a0f1180016fdc6a948b9ca45ec3210f"
		},
		"memory.sidecar.engine.message": {
			"file": "packages/memory/src/sidecar/memory-runtime.ts",
			"function": "engineLog",
			"line": 61,
			"column": 2,
			"file_hash": "0d430d0388646ffdb1b74e3ca447b78ffb63c80adbf431c8f585ff68aa6a94c8"
		},
		"memory.sidecar.model.prepare.failed": {
			"file": "packages/memory/src/sidecar/memory-runtime.ts",
			"function": "prepareModel",
			"line": 118,
			"column": 4,
			"file_hash": "0d430d0388646ffdb1b74e3ca447b78ffb63c80adbf431c8f585ff68aa6a94c8"
		},
		"memory.sidecar.pending_capture.failed": {
			"file": "packages/memory/src/sidecar/memory-runtime.ts",
			"function": "replayPendingCaptures",
			"line": 135,
			"column": 5,
			"file_hash": "0d430d0388646ffdb1b74e3ca447b78ffb63c80adbf431c8f585ff68aa6a94c8"
		},
		"memory.sidecar.usage.failed": {
			"file": "packages/memory/src/sidecar/memory-runtime.ts",
			"function": "<anonymous callback>",
			"line": 420,
			"column": 5,
			"file_hash": "0d430d0388646ffdb1b74e3ca447b78ffb63c80adbf431c8f585ff68aa6a94c8"
		},
		"rem-batch-executor.onStageError.d5f24d50d3": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "onStageError",
			"line": 371,
			"column": 6,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.runRemBatchJobUnlocked.55c52b91cf": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runRemBatchJobUnlocked",
			"line": 509,
			"column": 5,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"sidecar.batch.completed": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runRemBatchJobUnlocked",
			"line": 580,
			"column": 4,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.openBatchRuntime.86fa720e8f": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "openBatchRuntime",
			"line": 646,
			"column": 3,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.onProviderResponse.df4f2d4fa1": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "onProviderResponse",
			"line": 668,
			"column": 5,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.runUpdate.dbf2a836db": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 927,
			"column": 3,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.runUpdate.7dfc387204": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 1002,
			"column": 4,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.runUpdate.7ffc737c24": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runUpdate",
			"line": 1046,
			"column": 4,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.runReplace.e1e35e40e9": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2369,
			"column": 3,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.runReplace.de3a5f3ce3": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2577,
			"column": 4,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.runReplace.e4be8cfe8f": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2823,
			"column": 4,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"memory.rem.refusal.release_failed": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "runReplace",
			"line": 2949,
			"column": 6,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.buildRemReplaceCandidateQueue.25aa1a67a6": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "buildRemReplaceCandidateQueue",
			"line": 3170,
			"column": 3,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.buildRemReplaceCandidateQueue.lookup_failed": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "buildRemReplaceCandidateQueue",
			"line": 3252,
			"column": 3,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-batch-executor.reserveReplaceStage.4e67e45fd5": {
			"file": "packages/memory/src/sidecar/rem-batch-executor.ts",
			"function": "reserveReplaceStage",
			"line": 3699,
			"column": 2,
			"file_hash": "ad8eeca5951c191803460e8042961c1279810b2a5498248a0e32d32f878efde1"
		},
		"rem-job-store.load.invalid-line": {
			"file": "packages/memory/src/sidecar/rem-job-store.ts",
			"function": "load",
			"line": 316,
			"column": 5,
			"file_hash": "e776f04d46e9e25fa74aea87a6074f7c8e34acd4362808f4ddfb675430e4927f"
		},
		"rem.journal.failed": {
			"file": "packages/memory/src/sidecar/rem-job-store.ts",
			"function": "reportFailure",
			"line": 366,
			"column": 3,
			"file_hash": "e776f04d46e9e25fa74aea87a6074f7c8e34acd4362808f4ddfb675430e4927f"
		},
		"memory.rem.trigger.state.unavailable": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 141,
			"column": 3,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.1d59077a5c": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 169,
			"column": 4,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.ebe1cdd204": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 181,
			"column": 5,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"rem-trigger.evaluateRemAutomaticTriggers.46669e66ff": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 191,
			"column": 5,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"memory.rem.trigger.state.write.failed": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "evaluateRemAutomaticTriggers",
			"line": 212,
			"column": 18,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"sidecar.trigger.dispatch.accepted": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "dispatchRemWave",
			"line": 339,
			"column": 3,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"sidecar.trigger.audit_read.failed": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "applyCompletedBaselines",
			"line": 358,
			"column": 3,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"sidecar.trigger.audit_records.skipped": {
			"file": "packages/memory/src/sidecar/rem-trigger.ts",
			"function": "applyCompletedBaselines",
			"line": 451,
			"column": 3,
			"file_hash": "927f701577db98fba11d8cb5e250f84e1d430cd40ecc52b5270e5993df69b231"
		},
		"sidecar.duplicate.exit": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "bindSidecarSocket",
			"line": 147,
			"column": 6,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.<anonymous callback>.5eb5a60e6b": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "<anonymous callback>",
			"line": 206,
			"column": 3,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.<anonymous callback>.47c4662916": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "recordRequest",
			"line": 242,
			"column": 4,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.<anonymous callback>.a7a2656a08": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "<anonymous callback>",
			"line": 282,
			"column": 5,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"sidecar.discovery.published": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "publishDiscovery",
			"line": 312,
			"column": 30,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"sidecar.discovery.failed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "publishDiscovery",
			"line": 317,
			"column": 4,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.startLockedRemSidecar.96a92b085b": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startLockedRemSidecar",
			"line": 340,
			"column": 2,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"sidecar.shutdown.timeout": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startRemSidecar.stop",
			"line": 375,
			"column": 7,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"sidecar.shutdown.task.running": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startRemSidecar.stop",
			"line": 383,
			"column": 8,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"sidecar.shutdown.completed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "startRemSidecar.stop",
			"line": 398,
			"column": 5,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.routeRequest.0ea180a77c": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "routeRequest",
			"line": 480,
			"column": 3,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.runChassisJob.e7639bd8fc": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "runChassisJob",
			"line": 679,
			"column": 6,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"sidecar.job.completed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "runChassisJob",
			"line": 704,
			"column": 4,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.failNonTerminalJob.cf84e07c6d": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "failNonTerminalJob",
			"line": 774,
			"column": 3,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"server.recoverInterruptedJobs.15309ea841": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "recoverInterruptedJobs",
			"line": 809,
			"column": 4,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"sidecar.operation.failed": {
			"file": "packages/memory/src/sidecar/server.ts",
			"function": "reportSidecarFailure",
			"line": 985,
			"column": 2,
			"file_hash": "a544e93aaf0d6a6f2c16990c2d2e1ea664ed11a4886e6dabce03cc2519501c0b"
		},
		"active-task-carrier-backfill.backfillActiveTaskCarriers.facdae917f": {
			"file": "packages/memory/src/store/active-task-carrier-backfill.ts",
			"function": "backfillActiveTaskCarriers",
			"line": 221,
			"column": 2,
			"file_hash": "08a4ad11a94a5dc4ee8766a4a286179658d761754063faae7bae4ce8f06084d0"
		},
		"active-task-carrier-backfill.<anonymous callback>.0bf95b1f61": {
			"file": "packages/memory/src/store/active-task-carrier-backfill.ts",
			"function": "<anonymous callback>",
			"line": 245,
			"column": 3,
			"file_hash": "08a4ad11a94a5dc4ee8766a4a286179658d761754063faae7bae4ce8f06084d0"
		},
		"backup.pruneOldBackups.1dca69b51b": {
			"file": "packages/memory/src/store/backup.ts",
			"function": "removeBackups",
			"line": 97,
			"column": 3,
			"file_hash": "a93ea8f2c18e1fb7c2ce116c66ca59d99453e380f0fcdf693cd83c3fa12aa0e9"
		},
		"backup.runBackup.ca114973f1": {
			"file": "packages/memory/src/store/backup.ts",
			"function": "runBackup",
			"line": 186,
			"column": 2,
			"file_hash": "a93ea8f2c18e1fb7c2ce116c66ca59d99453e380f0fcdf693cd83c3fa12aa0e9"
		},
		"storage.vector.configuration.mismatch": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "ensureChunkVecTable",
			"line": 167,
			"column": 4,
			"file_hash": "89ac3d5abf6e5b0af9a10c49caca50fafc5a825e6bc71358939d33131c06e87a"
		},
		"connection.loadSimpleTokenizer.778ee7da6c": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "loadSimpleTokenizer",
			"line": 221,
			"column": 2,
			"file_hash": "89ac3d5abf6e5b0af9a10c49caca50fafc5a825e6bc71358939d33131c06e87a"
		},
		"connection.initDb.ee37a0a971": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "initDb",
			"line": 286,
			"column": 2,
			"file_hash": "89ac3d5abf6e5b0af9a10c49caca50fafc5a825e6bc71358939d33131c06e87a"
		},
		"storage.setup.failed": {
			"file": "packages/memory/src/store/connection.ts",
			"function": "retrySetup",
			"line": 301,
			"column": 5,
			"file_hash": "89ac3d5abf6e5b0af9a10c49caca50fafc5a825e6bc71358939d33131c06e87a"
		},
		"data-bootstrap.bootstrapDataLayout.4fc42585ae": {
			"file": "packages/memory/src/store/data-bootstrap.ts",
			"function": "bootstrapDataLayout",
			"line": 64,
			"column": 3,
			"file_hash": "0c90ad3563f3e96ecb6ba02bd0d4133d7f4803b021aa58e915e4924906828920"
		},
		"data-bootstrap.bootstrapDataLayout.4af3189946": {
			"file": "packages/memory/src/store/data-bootstrap.ts",
			"function": "bootstrapDataLayout",
			"line": 89,
			"column": 2,
			"file_hash": "0c90ad3563f3e96ecb6ba02bd0d4133d7f4803b021aa58e915e4924906828920"
		},
		"maintenance.recoverDerivedFts.753697bd94": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 217,
			"column": 2,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.recoverDerivedFts.2cf5f62053": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 234,
			"column": 3,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.recoverDerivedFts.c07ad948a2": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recoverDerivedFts",
			"line": 245,
			"column": 3,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.failClosed.dd7955e647": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "recordIntegrityFailure",
			"line": 268,
			"column": 2,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.runMaintenancePass.747b7cbef0": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 353,
			"column": 3,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.runMaintenancePass.c72575daaa": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 377,
			"column": 4,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.runMaintenancePass.ef7a1e225c": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 394,
			"column": 3,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.runMaintenancePass.90f01cc543": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 406,
			"column": 3,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.runMaintenancePass.3a7c9e73cf": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 419,
			"column": 3,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.runMaintenancePass.11beb09895": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 433,
			"column": 3,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.runMaintenancePass.6a1e15dc18": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "runMaintenancePass",
			"line": 441,
			"column": 2,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.tick.e111b66415": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "tick",
			"line": 499,
			"column": 4,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.tick.6bd3e0102c": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "tick",
			"line": 508,
			"column": 4,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.<anonymous callback>.f90713a2e3": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "<anonymous callback>",
			"line": 539,
			"column": 5,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"maintenance.startMaintenanceTimer.06c1e98584": {
			"file": "packages/memory/src/store/maintenance.ts",
			"function": "startMaintenanceTimer",
			"line": 558,
			"column": 2,
			"file_hash": "73b9a580a13f7d016c4e11a2a70c0e3687d9ff7b3a660e1fbcc7e452aa682d6d"
		},
		"memory-store-admin-api.delete.5a8c32b1ed": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "delete",
			"line": 57,
			"column": 3,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.deleteMany.e73022fb31": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "deleteMany",
			"line": 101,
			"column": 3,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.bulkDelete.2631f303e5": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "bulkDelete",
			"line": 167,
			"column": 3,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.<anonymous callback>.130719fdd0": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "<anonymous callback>",
			"line": 263,
			"column": 5,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-admin-api.closeSqlite.61a563b112": {
			"file": "packages/memory/src/store/memory-store-admin-api.ts",
			"function": "closeSqlite",
			"line": 312,
			"column": 4,
			"file_hash": "00e80abc5a25228e2d113f9f97f8c3704dcd5f8037134f745a35b2f3d2ecc0bd"
		},
		"memory-store-atomic-extraction-ledger-api.reopenAtomicExtractionChunk.e05258e34b": {
			"file": "packages/memory/src/store/memory-store-atomic-extraction-ledger-api.ts",
			"function": "reopenAtomicExtractionChunk",
			"line": 315,
			"column": 4,
			"file_hash": "b43bc6512fd75096a2c9711cd913d46da9b7ce65744917765b6c9828ff929f9d"
		},
		"memory-store-backfill.backfillMissingChunks.7094298b4a": {
			"file": "packages/memory/src/store/memory-store-backfill.ts",
			"function": "backfillMissingChunks",
			"line": 40,
			"column": 6,
			"file_hash": "c246982a9fc8dcd6ef9e198727f7a1cd11655e4c982a96571b9748032fa132cb"
		},
		"memory-store-backfill.<anonymous callback>.c483e84a68": {
			"file": "packages/memory/src/store/memory-store-backfill.ts",
			"function": "<anonymous callback>",
			"line": 110,
			"column": 6,
			"file_hash": "c246982a9fc8dcd6ef9e198727f7a1cd11655e4c982a96571b9748032fa132cb"
		},
		"memory-store-backfill.<anonymous callback>.c4019a929d": {
			"file": "packages/memory/src/store/memory-store-backfill.ts",
			"function": "<anonymous callback>",
			"line": 129,
			"column": 5,
			"file_hash": "c246982a9fc8dcd6ef9e198727f7a1cd11655e4c982a96571b9748032fa132cb"
		},
		"memory-store-base.<anonymous callback>.3dd5e75e4f": {
			"file": "packages/memory/src/store/memory-store-base.ts",
			"function": "<anonymous callback>",
			"line": 989,
			"column": 3,
			"file_hash": "311266ce9352ffce02294f308a4a0892bf9f41bfafb0a91c7fd6af3df4cc6758"
		},
		"storage.vector.search.unavailable": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 158,
			"column": 4,
			"file_hash": "7a811ca0d5fa66404c9e6d47b6b2960eabf124fdfcadf5aad429a69b1ea6db68"
		},
		"memory-store-chunk-search.searchChunksSemantic.7d889feb61": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 209,
			"column": 6,
			"file_hash": "7a811ca0d5fa66404c9e6d47b6b2960eabf124fdfcadf5aad429a69b1ea6db68"
		},
		"memory-store-chunk-search.searchChunksSemantic.fa074292e0": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksSemantic",
			"line": 233,
			"column": 4,
			"file_hash": "7a811ca0d5fa66404c9e6d47b6b2960eabf124fdfcadf5aad429a69b1ea6db68"
		},
		"memory-store-chunk-search.searchChunksKeyword.26628a27c1": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksKeyword",
			"line": 341,
			"column": 4,
			"file_hash": "7a811ca0d5fa66404c9e6d47b6b2960eabf124fdfcadf5aad429a69b1ea6db68"
		},
		"memory-store-chunk-search.searchChunksKeyword.36ca2cc1d7": {
			"file": "packages/memory/src/store/memory-store-chunk-search.ts",
			"function": "searchChunksKeyword",
			"line": 354,
			"column": 4,
			"file_hash": "7a811ca0d5fa66404c9e6d47b6b2960eabf124fdfcadf5aad429a69b1ea6db68"
		},
		"memory-store-persistence-api.store.8fd6a993e7": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 116,
			"column": 3,
			"file_hash": "430b6a412d57613587ee3cbc6ce1f053e970e72d64289ff053e158755b0295cf"
		},
		"memory-store-persistence-api.store.2f479e68bf": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 194,
			"column": 5,
			"file_hash": "430b6a412d57613587ee3cbc6ce1f053e970e72d64289ff053e158755b0295cf"
		},
		"memory-store-persistence-api.store.14bfc8e321": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "store",
			"line": 212,
			"column": 4,
			"file_hash": "430b6a412d57613587ee3cbc6ce1f053e970e72d64289ff053e158755b0295cf"
		},
		"memory-store-persistence-api.<anonymous callback>.b07cd1be28": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "<anonymous callback>",
			"line": 234,
			"column": 6,
			"file_hash": "430b6a412d57613587ee3cbc6ce1f053e970e72d64289ff053e158755b0295cf"
		},
		"memory-store-persistence-api.<anonymous callback>.087a18a049": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "<anonymous callback>",
			"line": 248,
			"column": 5,
			"file_hash": "430b6a412d57613587ee3cbc6ce1f053e970e72d64289ff053e158755b0295cf"
		},
		"memory-store-persistence-api.supersede.77de7ddab1": {
			"file": "packages/memory/src/store/memory-store-persistence-api.ts",
			"function": "supersede",
			"line": 766,
			"column": 3,
			"file_hash": "430b6a412d57613587ee3cbc6ce1f053e970e72d64289ff053e158755b0295cf"
		},
		"memory-store-read-api.getMemoryMetadata.35e63c5534": {
			"file": "packages/memory/src/store/memory-store-read-api.ts",
			"function": "getMemoryMetadata",
			"line": 190,
			"column": 4,
			"file_hash": "8d4e8ffa32b180ea4829cdc611bef9b8d34c142dc535e8e6e810f0718110f96d"
		},
		"memory-store-rem-api.applyRemTextVersion.6422a9ebd1": {
			"file": "packages/memory/src/store/memory-store-rem-api.ts",
			"function": "applyRemTextVersion",
			"line": 83,
			"column": 5,
			"file_hash": "8030b5f86b34eacaaf0498154daf8e6c03b31253581360f663f753a4305dfdfd"
		},
		"memory-store-rem-api.applyTransaction.47fe85179a": {
			"file": "packages/memory/src/store/memory-store-rem-api.ts",
			"function": "applyTransaction",
			"line": 207,
			"column": 3,
			"file_hash": "8030b5f86b34eacaaf0498154daf8e6c03b31253581360f663f753a4305dfdfd"
		},
		"memory-store-search-api.searchSemantic.a8cee42447": {
			"file": "packages/memory/src/store/memory-store-search-api.ts",
			"function": "searchSemantic",
			"line": 268,
			"column": 3,
			"file_hash": "34c9c5ce9d0a4dfbb1d4746082b595a1de3f0fa02d92547a89826f5989a011a5"
		},
		"memory-store-search-api.searchKeyword.f4293a3f14": {
			"file": "packages/memory/src/store/memory-store-search-api.ts",
			"function": "searchKeyword",
			"line": 322,
			"column": 3,
			"file_hash": "34c9c5ce9d0a4dfbb1d4746082b595a1de3f0fa02d92547a89826f5989a011a5"
		},
		"memory-store-search-api.attachSnippets.896a3e960a": {
			"file": "packages/memory/src/store/memory-store-search-api.ts",
			"function": "attachSnippets",
			"line": 375,
			"column": 5,
			"file_hash": "34c9c5ce9d0a4dfbb1d4746082b595a1de3f0fa02d92547a89826f5989a011a5"
		},
		"memory-store-update-api.update.31162cf4e4": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "update",
			"line": 184,
			"column": 3,
			"file_hash": "ebe44b344697e032caa4cf347b400e9af859d01814b1a7fdd846f069b6163987"
		},
		"memory-store-update-api.updateTier.feb5a5165b": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "updateTier",
			"line": 452,
			"column": 3,
			"file_hash": "ebe44b344697e032caa4cf347b400e9af859d01814b1a7fdd846f069b6163987"
		},
		"memory-store-update-api.updateMetadata.6e33353e47": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "updateMetadata",
			"line": 480,
			"column": 3,
			"file_hash": "ebe44b344697e032caa4cf347b400e9af859d01814b1a7fdd846f069b6163987"
		},
		"memory-store-update-api.resolveReflectionItem.f1d6aa0eab": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "resolveReflectionItem",
			"line": 510,
			"column": 3,
			"file_hash": "ebe44b344697e032caa4cf347b400e9af859d01814b1a7fdd846f069b6163987"
		},
		"memory-store-update-api.applyMetadataDeltas.49983b35b4": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "applyMetadataDeltas",
			"line": 561,
			"column": 3,
			"file_hash": "ebe44b344697e032caa4cf347b400e9af859d01814b1a7fdd846f069b6163987"
		},
		"memory-store-update-api.applyMetadataDelta.6961c06549": {
			"file": "packages/memory/src/store/memory-store-update-api.ts",
			"function": "applyMetadataDelta",
			"line": 598,
			"column": 3,
			"file_hash": "ebe44b344697e032caa4cf347b400e9af859d01814b1a7fdd846f069b6163987"
		},
		"memory-store-write-validation.shapeAlarm.3383666e9c": {
			"file": "packages/memory/src/store/memory-store-write-validation.ts",
			"function": "shapeAlarm",
			"line": 110,
			"column": 2,
			"file_hash": "ca90c6b0300952883746aeb7dbb2898f0fd2473c547083175750629e2c969ba7"
		},
		"rem-sqlite-adapter.mutateAttempt.4c4b5764ca": {
			"file": "packages/memory/src/store/rem-sqlite-adapter.ts",
			"function": "mutateAttempt",
			"line": 478,
			"column": 6,
			"file_hash": "cc6c194e3f1c2b6e50b6e7a5b7d067d607bea8bb586b22398bdae52ffc821f6b"
		}
	}
};
